### ISSUE TITLE
Document PID

### ISSUE THREAD

**Issue by strichter** [pybricks/support#1]
While I have lots of software development experience, I am only doing robotics with EV3 for fun with my kids. And I have no idea what PID is and the quick google results did not give me the tight intro I was looking for.

(I am a chemist and physicist by training, so the Calculus explanation will do. ;-)

**Comment by laurensvalk** [comment]
> so the Calculus explanation will do

In that case, [this might get you started](http://ctms.engin.umich.edu/CTMS/index.php?example=Introduction&section=ControlPID) for now. Equation (1) has the basic idea. In speed control (`run`, `run_time`), the error `e` is the speed error. In position control (`run_angle`, `run_target`), `e` is the angle error.

A simplified version is intended to be eventually included on the "More about Motors" page.

**Comment by laurensvalk** [comment]
The implementation is very different though, avoiding almost all numerical differentiation and integration steps. On the other hand, this brings it closer to the theory than most numerical PID implementations :)

**Comment by strichter** [comment]
BTW, the link helped me to get the idea.

**Comment by laurensvalk** [comment]
Sounds good. I'm thinking I'll leave this issue open until we've documented it in the docs.
