### ISSUE TITLE
Can't save from Pybricks Code

### ISSUE THREAD

**Issue by ZPhilo** [pybricks/support#101]
**Describe the bug**
Used to work before, but now when I try to save a program, Chrome Canary pops a window telling me that it blocked the file as it can be dangerous. I can force it to save the file in the download manager, but it's annoying...

**Screenshots**
![Capture](https://user-images.githubusercontent.com/5137285/87806762-aab63800-c857-11ea-84bd-51c17e1e5dde.PNG)

**Comment by dlech** [comment]
This is a web browser security "feature" so not something that we can "fix". However it can be worked around by enabling the "Ask where to save each file before downloading" setting.

![image](https://user-images.githubusercontent.com/963645/87808511-732b9980-c81f-11ea-8438-b11608861321.png)

**Comment by ZPhilo** [comment]
Thanks David, but...
- "Ask where to save ..." was and is still enabled
- I changed nothing in my configuration (or the folder where I download the files), but "suddendly" I have this problem (even if I load an old file that was saved previously, it fails if I try to save it again).
As said previously it's only annoying since we I can force Chrome to save anyway - or I can use cut/paste in a text editor...

**Comment by dlech** [comment]
Bummer, that is annoying.

There is hope for the future though: https://web.dev/native-file-system/

**Comment by ZPhilo** [comment]
> 
> There is hope for the future though: https://web.dev/native-file-system/

Ah - another good reason to long for this, my favorite LDraw parts editor will use that in its next version ;)

**Comment by ZPhilo** [comment]
Problem seems to have solved itself, probably afer machine reboot (I did restart Chrome, but not my machine when I posted this)

**Comment by laurensvalk** [comment]
> Problem seems to have solved itself

This sounds good. We'll close it until it occurs again. Thanks for reporting!
