### ISSUE TITLE
[Question] Running Motor.run_until_stalled in Pybricks 2.0 (EV3 MicroPython)

### ISSUE THREAD

**Issue by oemtas** [pybricks/support#1015]
**Describe the bug**
I get `The requested operation is not valid in the current state` when running motor.run_until_stalled(-999, Stop.BRAKE, 5)

**Screenshots**
![image](https://user-images.githubusercontent.com/107840884/228257017-b5a94e41-a266-4227-b554-84eaec72b3d0.png)
![image](https://user-images.githubusercontent.com/107840884/228257110-c321e729-f11b-4203-9130-63771462dfe9.png)

**Comment by oemtas** [comment]
To your information: The Motor is not used in a Drivebase

**Comment by laurensvalk** [comment]
Thanks for reporting. Can you share your full program please?

Or a small program where this happens?

**Comment by oemtas** [comment]
```
#!/usr/bin/env pybricks-micropython
from pybricks.ev3devices import Motor, ColorSensor
from pybricks.hubs import EV3Brick
from pybricks.parameters import Port, Color, Stop
from pybricks.robotics import DriveBase

ev3 = EV3Brick()
motor = Motor(Port.A)
wheel_right = Motor(Port.B)
wheel_left = Motor(Port.C)

drivebase = DriveBase(left_motor=wheel_left, right_motor=wheel_right, wheel_diameter=50, axle_track=210)
drivebase.settings(straight_speed=999, turn_rate=999)

def run():
    drivebase.straight(50)
    //Happens here
    #motor.run_until_stalled(-999, Stop.BRAKE, 5)

run()
```

**Comment by laurensvalk** [comment]
I think you need to use a higher value for the `duty_limit` than `5`. Perhaps try something like `30`.

**Comment by oemtas** [comment]
Okay, worked. Thank you

**Comment by laurensvalk** [comment]
Glad to help!
