### ISSUE TITLE
Starting program failed: Failed to execute child process "/home/robot/ev3python/BarcodeTester\BarcodeReader" (No such file or directory)

### ISSUE THREAD

**Issue by green4ja** [pybricks/support#1016]
**Describe the bug**
After changing literally nothing about how my folders and directories are pathed. I created a new folder within my ev3python parent folder used for holding my BarcodeReader code in the BarcodeTester folder. Every time I try to run the file in run&debug mode or just on the actual ev3 mindstorm, the terminal outputs this:

`Starting: brickrun -r --directory="/home/robot/ev3python" "/home/robot/ev3python/BarcodeTester\BarcodeReader"
Starting program failed: Failed to execute child process "/home/robot/ev3python/BarcodeTester\BarcodeReader" (No such file or directory)
Exited with error code 1.`

**Context**
I was just trying to test out the barcode reading code with my color sensor.

**Screenshots**
![image](https://user-images.githubusercontent.com/129229043/228375013-26eed81f-baa9-4e73-af72-c6e007e72228.png)
![image](https://user-images.githubusercontent.com/129229043/228375150-86ce9d33-b9ca-4649-ae30-30da96d1c50b.png)
![image](https://user-images.githubusercontent.com/129229043/228375221-cd38e875-85d6-4125-8f86-b39a90cea05b.png)

**Comment by green4ja** [comment]
**More Info**
Quick bit of info, I don't have the slightest clue about how directories and folders and file paths work in vscode, and 99% of the time they are the source of my errors and lead to me spending endless time trying to figure out a problem I have no clue how to solve.

**Directory Info**
The directory for the folder with the file I'm trying to run is:
`C:\Users\jag10\Desktop\Stuff for Python Robot\ev3python\BarcodeTester`
(Also, please let me know if this is an incorrect way of doing things, but everytime when I go to work on my code for these robot files in vscode, I click Open Folder, then chose my ev3python folder that has all my subfolders with the code files in them.)

**Screenshot**
This is the screenshot of the inside of ev3python folder:
![image](https://user-images.githubusercontent.com/129229043/228378154-35144fdb-bc5a-425f-8a85-cb814fc8fafd.png)

**Comment by dlech** [comment]
Can you share your `.vscode/launch.json` file? I suspect you need to replace `\\` with `/` in the `"program"` listed there.

**Comment by green4ja** [comment]
Wait why was this closed? I still don't know what to change?

**Comment by dlech** [comment]
It was closed automatically because I just pushed a fix and I didn't have time to comment yet to explain. 😄 

Please try updating the `ev3dev-browser` to v1.2.1.

The `${relativeFile}` variable includes the Windows path separator which doesn't work on EV3 since it is running Linux. So I added a fix to automatically convert the path separators.

**Comment by green4ja** [comment]
I checked my extensions and ev3dev-browser is on v1.2.1. Also I don't really know how to incorporate your fix into my code.

**Comment by dlech** [comment]
Did you try running the program again now that the extension has been updated? You should not have to change anything in your code.

**Comment by green4ja** [comment]
I'm currently trying to turn on my robot to run the program directly to the robot but of course for the first time my robot has been stuck on a timed out message the last 3 boots.

**Comment by green4ja** [comment]
It works now! Thank you so much!

**Comment by dlech** [comment]
Great! Thanks for confirming!
