### ISSUE TITLE
[Bug] hub.output no longer available in Pybricksdev

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#1037]
**Describe the bug**
`PybricksHub.output` used a contain the `stdout` output, which was used to save the result of the motor testsL
https://github.com/pybricks/pybricks-micropython/blob/2beddbcd724714944e9fd36db3f99fb9d7a9e77f/tests/motors/run_test.py#L39

What is the new way to obtain this data?

There appears to be `_stdout_buf`, but it is empty after the script completes.

**Comment by dlech** [comment]
Oops, I didn't see that it was being used anywhere in pybricksdev so assumed it wasn't being used. I replaced it with `_stdout_line_queue` to make it awaitable for the new `read_line()` function but also made that mutually exclusive with printing the lines. We can just put `output` back too.

**Comment by laurensvalk** [comment]
Thanks!
