### ISSUE TITLE
[Bug] middle-clicking to close programs on Linux pastes selection into open program

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#1046]
**Describe the bug**
Occasionally, the script gets in a bad state. From what I can tell, several scripts got merged.

![image](https://user-images.githubusercontent.com/12326241/234291936-d75f5ea5-5da4-453a-9c00-873ac753692d.png)

**To reproduce**
Haven't found a consistent approach. If I had to guess, this happens only when closing quite a few tabs fairly quickly. (Mouse on first one, repeatedly click middle button.)

**Comment by laurensvalk** [comment]
Found it! Closing by middle-click has the side effect of paste-last-selection which is also done with middle click.

See demo below. So, depending on what was selected, this can feel like "multiple scripts merging" even if something else is happening.

For what it's worth, separate from this issue, my vote would be to disable paste-last-selection-by-middle-click altogether. I always disable in in VS Code too. It happens way too often accidentally while scrolling/moving.

https://user-images.githubusercontent.com/12326241/234357855-aba7ef45-314d-4649-8191-d487d579b739.mp4

**Comment by dlech** [comment]
Nice find. I didn't even know that was a feature.

**Comment by dlech** [comment]
Where/how do you disable this in VS Code? Web searches tell me this is a Linux feature rather than a VS Code feature.

**Comment by laurensvalk** [comment]
I think you're right. I must be confusing it with some other VSCode feature I have disabled.

**Comment by laurensvalk** [comment]
FWIW, I found that other setting, and it is indeed somewhat related:

I set `"editor.emptySelectionClipboard": false,` so that `CTRL+C` with no selection doesn't copy the line.

Sometimes I accidentally press `CTRL+C` when I mean to paste. But by default the clipboard content is now overridden so you have to start over. I suppose my Pybricks Code scripts aren't that big so it hasn't been as much of a nuissance.

**Comment by dlech** [comment]
It looks like `editor.selectionClipboard` is the option. https://github.com/microsoft/vscode/issues/14610#issuecomment-256778712

Although that doesn't actually seem to fix the problem.
