### ISSUE TITLE
[Bug] stdin inserts extra 0x06 at start of every write command

### ISSUE THREAD

**Issue by Novakasa** [pybricks/support#1052]
**Describe the bug**
It looks like for every `PybricksHub.write` command, the hub receives an extra `0x06` character in the beginning, using most recent pybricksdev and beta firmware.

Seems like the 0x06 is the `Command.WRITE_STDIN` const. I would have expected this to be filtered out on the hub side.

Also, `PybricksHub.write_line` only adds `\n` as a newline. I'm not sure about this, but I would have expected `\r\n` since it's also the stdout format. `write_line` also adds the extra `0x06` at the start

**To reproduce**
Firmware: `Pybricks MicroPython v3.3.0b4 on 2023-04-21; Powered Up City Hub with STM32F030RC`
pybricksdev `1.0.0a45`

PC program:
```python

import asyncio
from pybricksdev.ble import find_device
from pybricksdev.connections.pybricks import PybricksHub

async def main():
    dev = await find_device()
    print(dev)
    hub = PybricksHub()
    await hub.connect(dev)
    print("connected!")
    await hub.run("ble-server/hub_programs/test_stdin_hub.py", print_output=True, wait=False)
    await asyncio.sleep(0.5)
    print("writing line...")
    await hub.write(b"012345\r\n")
    print("writing line...")
    await hub.write(b"hello\r\n")
    print("writing line...")
    await hub.write(b"\r\n")
    await asyncio.sleep(5.0)
    await hub.disconnect()

    print("OK!")

asyncio.run(main())
```

hub program:
```python
# NOTE: Run this program with the latest
# firmware provided via https://beta.pybricks.com/

from pybricks.tools import wait

# Standard MicroPython modules
from usys import stdin, stdout
from uselect import poll

keyboard = poll()
keyboard.register(stdin)
buffer = bytearray()

for _ in range(3):
    while True:

        if keyboard.poll(50):
            byte = stdin.buffer.read(1)[0]
            print(byte, end=" ")
            buffer.append(byte)
            if buffer[-2:] == b"\r\n":
                print("\nline received")
                print(str(buffer))
                buffer = bytearray()
                break

wait(100)
```

Output:
```
2F:AC:DC:65:90:53: city-blue
connected!
100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 388/388 [00:00<00:00, 1.11kB/s]
writing line...
writing line...
6 48 49 50 51 52 53 13 10
line received
bytearray(b'\x06012345\r\n')
writing line...
6 104 101 108 108 111 13 10
line received
bytearray(b'\x06hello\r\n')
6 13 10 
line received
bytearray(b'\x06\r\n')
OK!
```

**Expected behavior**
I am expecting no extra 0x06 at the beginning of stdin for each write command.

**Comment by dlech** [comment]
> for every `PybricksHub.write` command, the hub receives an extra `0x06` character in the beginning

Thanks for reporting. Not sure how I missed this when testing.


> I'm not sure about this, but I would have expected `\r\n`

I expected the same too, but it caused problems and was changed in https://github.com/pybricks/pybricksdev/commit/a08db5fa59909997fb816b7cb19ec38e14315cc3.
