### ISSUE TITLE
how to install the numpy package on ev3 now

### ISSUE THREAD

**Issue by Nikolay-Zagrebin** [pybricks/support#1072]
**Question**
how to install the numpy package on ev3?

**Context**
previously, it was possible to install the command
robot@ev3dev:~$ sudo apt-get install python3-numpy

an error is coming out now

**Comment by Nikolay-Zagrebin** [comment]
maybe I asked a question in the wrong section. I probably should have gone to ev3dev

**Comment by dlech** [comment]
Yes, please post the exact error message on the ev3dev issues. I'm guessing you forgot to run `sudo apt update` first or the EV3 is not connected to the Internet.

**Comment by Nikolay-Zagrebin** [comment]
I figured it out, Debian moved everything to the archive.
To solve the problem, add a new line to the sources.list file
deb http://archive.debian.org/debian stretch main contrib non-free

**Comment by laurensvalk** [comment]
Thank you!
