### ISSUE TITLE
I cannot connect from the web.

### ISSUE THREAD

**Issue by ben7147** [pybricks/support#1092]
InstanceId        : USB\VID_0CF3&PID_E300\6&1753EE65&0&2
MAC               : 8030498BD4FA
DriverDescription : Qualcomm Atheros QCA61x4 Bluetooth
DriverVersion     : 10.0.0.1076
ErrorRecovery     : None
ScoType           : InBand

**Comment by dlech** [comment]
I don't understand the problem. Can you give the exact steps with screenshots that show how to reproduce the problem?

**Comment by ben7147** [comment]
I solved the problem, thanks.
