### ISSUE TITLE
ColorLightMatrix broken in current beta

### ISSUE THREAD

**Issue by lc-jrx** [pybricks/support#1098]
Method ".off()" gives back an error "TypeError: extra keyword arguments given"
![REPL_screenshot](https://github.com/pybricks/support/assets/133227013/385b1f92-49f3-4fc2-aecc-6037976c4746)

**Comment by laurensvalk** [comment]
Thanks for the report! We'll work on a fix.

**Comment by lc-jrx** [comment]
Thx a lot. And holy! That was a fast reply.

**Comment by laurensvalk** [comment]
> That was a fast reply.

The best way to get a developer's attention is to tell them they broke something in the code :smile:  (and I did!)

**Comment by laurensvalk** [comment]
This has been fixed and should be coming in the next beta release.

As a workaround in the mean time, you can set the color to Color.NONE to turn the lights off.

**Comment by lc-jrx** [comment]
Thx a lot! I'm rolled back to the current release. So everything is working as expected.
