### ISSUE TITLE
[Feature] Support for Firefox

### ISSUE THREAD

**Issue by tiagorangel2011** [pybricks/support#1110]
**Is your feature request related to a problem? Please describe.**
It would be great to have Firefox support. I'm using code.pybricks.com

**Describe the solution you'd like**
Ability to use firefox on code.pybricks.com or beta.pybricks.com.

**Describe alternatives you've considered**
Check if firefox has implemented Bluetooth API.

**Comment by dlech** [comment]
Mozilla has taken the position that Web Bluetooth is harmful to the web and will not support it for the foreseeable future, so this is not technically possible without forking Firefox, which is not something we have the resources to do.

Reference: https://bugzilla.mozilla.org/show_bug.cgi?id=674737
