### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by XilefTech** [pybricks/support#112]
**Question**
What am I doing wrong with installing packages with pip?

**Context**
I tried to install a lib that I wanted to use in my project. Through an ssh terminal I used pip install <libName> to install it. Everything went fine until I actually wanted to use the lib in my program. Every time, I would try to import it, I would just get the error that it wasn't found and there was no such library

Please note tho: I tried this with more than one lib and it didn't work with all of them - all the same issue, so it's not something library-specific.

**Comment by laurensvalk** [comment]
This isssue appears to have been posted twice, so I'll close #112 and answer in #113.
