### ISSUE TITLE
the console does not work in the newest version

### ISSUE THREAD

**Issue by dlech** [pybricks/support#1130]
### Discussed in https://github.com/orgs/pybricks/discussions/1129

<div type='discussions-op-text'>

<sup>Originally posted by **Potato-eater** July  1, 2023</sup>
in the newest version of the pybricks beta IDE, the console does not work. I couldn't print anything.
![image](https://github.com/pybricks/support/assets/95858994/5fe128fc-3fee-4251-89fc-9b9e9ece0bb2)
it only shows as a black box with nothing inside.</div>

**Comment by BertLindeman** [comment]
Confirmed. Reran the small test program:
```
('cityhub', '3.3.0b7', 'v1.20.0-23-g6c633a8dd on 2023-06-30')
('technichub', '3.3.0b6', 'v1.20.0-23-g6c633a8dd on 2023-06-02')

```
