### ISSUE TITLE
CI Builds have incorrect version number reported

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#1136]
> What are you seeing on this screen?
> 
> ![image](https://user-images.githubusercontent.com/12326241/250550774-e9eb24f6-4d1c-41a7-8e7e-e2bfc955de4a.png)

![image](https://github.com/pybricks/support/assets/8142081/13889575-712b-41f8-a3d1-8b2c76455289)

> Did another try and got this version:
```('technichub', '3.3.0b7', 'v1.20.0-23-g6c633a8dd on 2023-07-03')```

_Originally posted by @BertLindeman in https://github.com/pybricks/support/issues/1131#issuecomment-1618139637_

**Comment by laurensvalk** [comment]
I can confirm, I also got `v1.20.0-23-g6c633a8dd on 2023-07-03` from `technichub-firmware-build-2956-gitef4ae702.zip`.

**Comment by dlech** [comment]
Actually, on second though, this is probably related to MicroPython 1.20 changes on how we override the version macros.

**Comment by laurensvalk** [comment]
> I assume non-master branch builds show the correct version?

I have only tried the nightly (master) links.

**Comment by dlech** [comment]
Fixed by https://github.com/pybricks/pybricks-micropython/commit/1752bec6a4168e36aff102bd0902122f4a397945 and further improved by https://github.com/pybricks/pybricks-micropython/commit/920bd471.
