### ISSUE TITLE
[Doc] Value range / explanation for Motor “profile”

### ISSUE THREAD

**Issue by mahalis** [pybricks/support#1170]
**Describe the issue**
The current documentation for the [Motor](https://docs.pybricks.com/en/latest/pupdevices/motor.html) initializer states:

> A lower value means more precise movement; a larger value means smoother movement. If no value is given, a suitable profile for this motor type will be selected automatically.

It’s unclear what the units are or what a reasonable range of values are.

**Suggested improvement**
Specifying a few example values for different motor types would be helpful (it looks like a bunch of them are defined in `lib/pbio/src/motor/servo_settings.c`, ranging from 10 for the EV3 motors to 20 for some of the Technic ones), as would including this comment from `lib/pbio/include/pbio/servo.h`:

> This is a measure for "precision" (low values) versus "smoothness" (high value), expressed roughly as the allowed deviation (in degrees) from a target angle to be considered on target.

In the course of researching these suggested improvements I’ve answered the question I had… but it might be worth saving future readers that research 🙂

**Comment by laurensvalk** [comment]
Thanks for mentioning this. You also get bonus points for finding the solution in the source code :smile:

**Comment by laurensvalk** [comment]
Revised text:

![image](https://github.com/pybricks/support/assets/12326241/b60fef63-b162-4c83-8a19-2364418b1f2b)

**Comment by laurensvalk** [comment]
Fixed by https://github.com/pybricks/pybricks-api/commit/e7377dff3166bcccd63a5f6b1c175d8ffe90ac83
