### ISSUE TITLE
[Bug] Cant start project

### ISSUE THREAD

**Issue by ihavenoideawhatimdoingh** [pybricks/support#1179]
**Describe the bug**
![image](https://github.com/pybricks/support/assets/140494037/73f2f52f-1cb5-4ecf-952f-670cde4f4f5f)
play button cant be clicked

**To reproduce**
i dont know how to reproduce it.

**Expected behavior**
i expected it to work since i programmed it on my mac and it worked but now it wont work on windows

**Screenshots**
![image](https://github.com/pybricks/support/assets/140494037/b6c5a33b-a93c-487b-91d3-0497a88a8c5d)

**Comment by laurensvalk** [comment]
What happens if you disconnect and connect again?

**Comment by ihavenoideawhatimdoingh** [comment]
> 

same issue

**Comment by ihavenoideawhatimdoingh** [comment]
> What happens if you disconnect and connect again?

do you think it could be because im using chrome?

**Comment by ihavenoideawhatimdoingh** [comment]
> 

nope doesnt work

**Comment by dlech** [comment]
We need logs in order to troubleshoot the problem. Please see https://github.com/orgs/pybricks/discussions/270 for how to collect such logs.

**Comment by dlech** [comment]
Which hub and firmware version are you using?

**Comment by ihavenoideawhatimdoingh** [comment]
> Which hub and firmware version are you using?

inventor hub, latest firmware

**Comment by ihavenoideawhatimdoingh** [comment]
> We need logs in order to troubleshoot the problem. Please see https://github.com/orgs/pybricks/discussions/270 for how to collect such logs.

couldnt be bluetooth issues since it works on my mac, also it wont work (the logs)

**Comment by dlech** [comment]
> latest firmware

So you you are using firmware from https://nightly.link/pybricks/pybricks-micropython/workflows/build/master? What is the exact version?

**Comment by dlech** [comment]
> couldnt be bluetooth issues since it works on my mac, also it wont work (the logs)

The Windows and Mac computers have different Bluetooth adapters, so it could be a Bluetooth issue. Without any logs, I'm afraid we can't really provide any further insight.

**Comment by ihavenoideawhatimdoingh** [comment]
i cant check logs and im using the newest version
