### ISSUE TITLE
Lego City Hub Pybricks firmware installation fails for no reason ``` GATT operation failed for unknown reason. ``` on Chrome Windows 11

### ISSUE THREAD

**Issue by mewohenlo** [pybricks/support#1196]
**Describe the bug**
What is the problem?
So the error message pops up every time I have tried only when the firmware installation percentage reaches 50%   

**To reproduce**
Steps to reproduce the behaviour:
1. Follow all the steps to the city hub firmware installation
2. Release the green power button on the hub.
3. Reaches 50%
4. See error:   ```GATT operation failed for unknown reason.```

**Expected behaviour**
What did you expect to happen instead?
For it to continue until it completes and I can program

**Screenshots**
There is a saying that a picture is worth 1000 words. Screenshots help to identify and solve problems.
![Screenshot 2023-08-04 174223](https://github.com/pybricks/support/assets/117389075/041be1ee-b1e9-4ff1-aa42-f19034a099d2)

**Comment by mewohenlo** [comment]
no still going

**Comment by dlech** [comment]
Make sure you have everything unplugged from the ports and you have fully charged batteries.

If you are still having trouble after that...

Are you using `code.pybricks.com` or `beta.pybricks.com`?

To troubleshoot the issue, we need logs as described in #270 or you can try reaching out to Microsoft as described in https://github.com/pybricks/support/issues/918#issuecomment-1527996980.

You could also try a different Bluetooth adapter. Some work better with Windows than others. 

- https://github.com/pybricks/support/issues/921
- https://github.com/pybricks/support/issues/761

If you have another device with a different supported OS (Android, ChromeOS, Mac), you could try that too.

**Comment by laurensvalk** [comment]
If you have time, the best way to help us solve it is gather logs as described at the [bottom of this post](https://github.com/orgs/pybricks/discussions/270). Thanks!

**Comment by tetaplaun** [comment]
> If you have time, the best way to help us solve it is gather logs as described at the [bottom of this post](https://github.com/orgs/pybricks/discussions/270). Thanks!

Solved by [this](https://github.com/pybricks/support/issues/505#issuecomment-939528098)
The instructions tell you to hold the button until it say to release it. The message appears too late (for me), therefore causing the problem. After reading the mentioned comment, it works.

**Comment by dlech** [comment]
Hopefully fixed by https://github.com/pybricks/pybricks-code/commit/236ad56148e572170aafd8aae0c2292f140465da
