### ISSUE TITLE
I have 3 questions

### ISSUE THREAD

**Issue by ihavenoideawhatimdoingh** [pybricks/support#1203]
1) how would i connect my hub to my ipad

2) how would i connect my hub to my PC via USB

3) how would i save a file to the hub after 1 or 2?

**Comment by laurensvalk** [comment]
iPad isn’t supported because the iOS browsers does not allow Bluetooth connections.

USB isn’t supported on any platform, so I’d recommend using Bluetooth on your PC.

**Comment by ihavenoideawhatimdoingh** [comment]
> iPad isn’t supported because the iOS browsers does not allow Bluetooth connections.
> 
> USB isn’t supported on any platform, so I’d recommend using Bluetooth on your PC.

Well how do i upload a file to my hub like in the mindstorms app?

**Comment by laurensvalk** [comment]
As mentioned above, USB is not supported in Pybricks.

If you prefer to use USB, consider using the original Mindstorms app.

**Comment by laurensvalk** [comment]
Closing as there is no follow-up activity.
