### ISSUE TITLE
[Bug] EV3: motor.control.limits unexpected behaviors at low torque settings

### ISSUE THREAD

**Issue by jaguilar** [pybricks/support#1217]
**Describe the bug**
I get EPERM when setting the control limits even when my motor is stopped.

**To reproduce**
Load the following program on an EV3:

```python
#!/usr/bin/env pybricks-micropython

import math

from pybricks.hubs import EV3Brick
from pybricks.ev3devices import (
    Motor,
    TouchSensor,
    ColorSensor,
    InfraredSensor,
    UltrasonicSensor,
    GyroSensor,
)
from pybricks.parameters import Port, Stop, Direction, Button, Color
from pybricks.tools import wait, StopWatch, DataLog
from pybricks.robotics import DriveBase
from pybricks.media.ev3dev import SoundFile, ImageFile
from pybricks.tools import wait
import _thread

brick = EV3Brick()
calibrating = False

# arm1 = Motor(Port.C)
arm2 = Motor(Port.D)

# arm1.stop()
arm2.control.limits(None, None, 10)
arm2.run_until_stalled(75)
while not arm2.stalled():
    wait(25)
brick.speaker.beep()
```

Result:

```
Starting: brickrun --directory="/home/robot/ev3test" "/home/robot/ev3test/main.py"
----------
Traceback (most recent call last):
  File "/home/robot/ev3test/main.py", line 28, in <module>
OSError: [Errno 1] EPERM: 

The requested operation is not valid in the current state:
--> Check the documentation for required conditions.
--> Check the line in your script that matches
    the line number given in the 'Traceback' above.

```

Changing the torque setting to 40 instead gives motor movement with the expected torque limit, but stall detection never kicks in even when the motor is stuck for several seconds.

**Expected behavior**
The motor should run with a 10 mNm torque setting until it stalls. If such a duty cycle cannot be configured, at least the error condition would ideally be raised explicitly. Also, if the 40mNm torque setting is chosen, stall detection should still work.

**Screenshots**
There is a saying that a picture is worth a 1000 words. Screenshots really help to identify and solve problems.

**Comment by laurensvalk** [comment]
I'm afraid we're no longer updating the 2.0 motor controllers. Much of this has been fixed and improved in V3, but this isn't coming to EV3 in the foreseeable future.
