### ISSUE TITLE
[Bug] colorsensor.hsv(surface) not work

### ISSUE THREAD

**Issue by jkhlouf** [pybricks/support#1232]
[Bug] colorsensor.hsv(surface=False) not work

**Comment by dlech** [comment]
Can you describe what you expected to happen and what actually happened?

**Comment by jkhlouf** [comment]
![IMG_0899](https://github.com/pybricks/support/assets/42026457/848393ea-3e33-42e6-aa8c-440b10c22544)
![IMG_0898](https://github.com/pybricks/support/assets/42026457/ec01ac25-48a4-449e-a8a3-44addf37e9fa)

**Comment by laurensvalk** [comment]
Thanks for reporting! We'll look into it.
