### ISSUE TITLE
[Question] I don't see WinUSB driver'

### ISSUE THREAD

**Issue by Xterplot** [pybricks/support#1248]
**Question**
Where is WinUSB Device?

**Context**
I would like to install the driver for DFU mode in the Large HUB Lego Technic but I cannot find it or I do not have it on my computer.
I can see Universal Serial Bus devices myself, but I don't see WinUSB Device.
My windows 11 has Polish language.

**Screenshots**

https://github.com/pybricks/support/assets/141823466/09d5b7c8-3a5f-495c-9d5c-fd69a8f87fe8

Would it be possible to somehow find this Driver?

If you need more information, write to me and I will try to give it to you.

**Comment by dlech** [comment]
I'm guessing that since you closed the issue, you figured out that you had to select *Microsoft* first.
