### ISSUE TITLE
[Bug] Remote Invocation causes 'Unknown error'

### ISSUE THREAD

**Issue by Vinz1911** [pybricks/support#1268]
Hi there, I tried the latest release today ('primehub', '3.3.0b9', 'v1.20.0-23-g6c633a8dd on 2023-10-26') and discovered this:

**Describe the bug**
Calling the Remote function to create a connection to a Remote ends up in an unknown error

**To reproduce**
Just call:
```python
remote = Remote()
```

which sometimes throw

```bash
RuntimeError: Unknown error
```

**Expected behavior**
That it does not throw this error

**Comment by laurensvalk** [comment]
Does this always happen? Can you share a full script?

The following script seems to work for me:


```python
from pybricks.pupdevices import Remote

remote = Remote()
print("Hello, world!")
```

**Comment by Vinz1911** [comment]
No Sorry, this Happens sometimes and totally random

**Comment by laurensvalk** [comment]
Would you mind trying if it also happens with this (slightly older) builld?

https://github.com/pybricks/pybricks-micropython/actions/runs/6652294240

If it doesn't happen there, I have a hunch what it might be.

**Comment by dlech** [comment]
If my hunch is the same as Laurens' then it should be fixed on the lasted builds too:

https://nightly.link/pybricks/pybricks-micropython/workflows/build/master

**Comment by laurensvalk** [comment]
A lot of Bluetooth code has since been released. I'll close it now, but feel free to re-open if this happens again.
