### ISSUE TITLE
Import commands from Google Colab to Pybricks.

### ISSUE THREAD

**Issue by OptimusPrime321** [pybricks/support#1270]
Let's say I have a simple program on Google Colab that gives the output "forward". I also have a custom-built function on the web IDE that takes inputs. Is there any way I can continuously stream the output from Google Colab onto the function in the web IDE of pybricks ? This is what I want, but doing the same for EV3 on VScode will also help. I want the same thing to happen: output from Google Colab to stream onto the function in VScode continuously.

**Comment by laurensvalk** [comment]
That sounds related to this. Perhaps for inspiration: https://github.com/orgs/pybricks/discussions/1007

**Comment by OptimusPrime321** [comment]
Hi! I think that project is cool! However, I was wondering if you could help me with the question I asked earlier. Also, I was wondering if there's any way to upload PNGs/JPEGs onto the online editor. If you could let me know, that would be great!

**Comment by laurensvalk** [comment]
We don't have any ready made examples for that kind of thing, I'm afraid. The link above is probably the closest to what you're asking.

**Comment by OptimusPrime321** [comment]
Oh, will have to do something on my own then. Thanks for the help!
