### ISSUE TITLE
How to use remote light during an async function

### ISSUE THREAD

**Issue by Jedve** [pybricks/support#1281]
**Question**
How can I change remote light color in a multitask ?

**Context**
When I try to change the Color of the remote connected to a CityHub, it works for the first call and crash on the second one with an error returned:
"OSError: This ressource cannot be used in two tasks at once."
When I do the same with the hub light, it works perfectly.

**Screenshots**
I put here a testing exemple that throw the error:
```python
from pybricks.hubs import CityHub
from pybricks.parameters import Color
from pybricks.pupdevices import Remote
from pybricks.tools import run_task, wait

hub = CityHub()

print('searching for remote...')
remote = Remote(timeout=None)
print(f'remote {remote.name()} found!')


async def change_color(color):
    remote.light.on(color=color)
    

async def main():
    for color in [Color.GREEN, Color.MAGENTA]:
        await change_color(color)
        await wait(1000)

run_task(main())
```

**Comment by laurensvalk** [comment]
The await keyword is missing in front of the on() call within your function.

This has since been added to the docs, but the updated docs haven't made it into a release yet.

**Comment by Jedve** [comment]
@laurensvalk Thank you for your answer.

I tried it and, as a result, I don't get the error but the light color is not updated. Only the Color.GREEN is applied. If I replace the remote by the hub, it works only without the await before calling the on().

```python
async def change_color(color):
    print(f'Change color to {color}')
    await remote.light.on(color=color)
    print(f'Change color to {color} done')
    

async def main():
    for color in [Color.GREEN, Color.MAGENTA]:
        await change_color(color)
        await wait(1000)
```

The result of the added print() let me know that the function is called correctly:
![image](https://github.com/pybricks/support/assets/22894392/963f091d-ff15-430e-b353-26d55fa87188)

But the light is still green.

**Comment by laurensvalk** [comment]
Can you try it using the nightly firmware build? We recently fixed something that could impact this. Thanks!

https://nightly.link/pybricks/pybricks-micropython/workflows/build/master

To install, begin the firmware update as usual, but instead of selecting a hub on the first dialog, select "advanced", and pick the file you downloaded from the link above.

**Comment by Jedve** [comment]
@laurensvalk 
It's working well now with this update. 
Thank you very much for your help.

So now, to use the remote light properly, do I wait for the next official release ?

**Comment by laurensvalk** [comment]
You can keep using the version you just installed if you like. You'll be notified automatically when a new official version becomes available, including this fix.

Glad it worked!

**Comment by mahil** [comment]
I also did install the latest nightly firmware build for the technic hub. But I always have problems when I use remote and async on the technic hub together.
This is just a simple program. The remote is connected just for a short time, and then it is disconnected without any error message.

![Block_Code_Technic_Hub](https://github.com/pybricks/support/assets/3720174/7ffda460-7485-471e-97b0-24c2b557916d)

The same program is running on a move hub without any issues.

**Comment by laurensvalk** [comment]
Thanks @mahil - I've moved your note to a separate issue, which sounds a bit different from the documentation issue which was resolved here.
