### ISSUE TITLE
[Question] pybricks.media module missing in Release 1.0?

### ISSUE THREAD

**Issue by devinbreise** [pybricks/support#13]
Attempt to import the Font class fails.

`from pybricks.media.ev3dev import Font`

Console Output: 
> ImportError: no module named 'pybricks.media'

This was with Release 1.0 downloaded from Lego Education.  Perhaps this module wasn't in that release?

**Comment by laurensvalk** [comment]
That's right, it's new in 2.0.

You can get the beta download from here: https://pybricks.com/downloads/

**Comment by laurensvalk** [comment]
This question has been answered, so we'll close it. It will continue to be available as a closed issue for people who search for related questions.
