### ISSUE TITLE
Pybricks Code Error: "GATT Disconnect" with Control+ Hub

### ISSUE THREAD

**Issue by Vinz1911** [pybricks/support#130]
Hello Everyone,

i wanted to try out pybricks with my new Control+ Hub. But i run into issues with that, the Pybricks Firmware upgrade was done without any problems. But my problem then is, when i want to connect the Hub to the Pybricks Code environment. On connecting the blue flashing LED stops flashing and lights up continuously but the play/stop button are not clickable and a half minute later i got an error: "GATT Server is disconnected. Cannot retrieve services. (Re)connect first with `device.gatt.connect`." The LED still lights up continuously. 

Can someone help me figure out whats wrong here ? 
I tried the latest Chrome Browser. Problem exists on Mac and PC. I also tried possible extensions to enable in chrome://flags 

Thanks and best regards
Vinz

![Pybricks_Error](https://user-images.githubusercontent.com/21056653/93020457-748a0000-f5dd-11ea-90b9-ec90ef77321f.jpg)

**Comment by dlech** [comment]
This should be fixed now. Please see https://github.com/pybricks/support/issues/136#issuecomment-706464049.
