### ISSUE TITLE
Generated Python code for Block `drivebase stop brake` should be `drivebase.brake()`, but is `drivebase.stop()`

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#1328]
### Discussed in https://github.com/orgs/pybricks/discussions/1326

<div type='discussions-op-text'>

<sup>Originally posted by **ggramlich** December 10, 2023</sup>
Currently the following code is generated:
![image](https://github.com/pybricks/support/assets/69276/21e91d04-f536-4277-b260-f52869b8ebde)
![image](https://github.com/pybricks/support/assets/69276/bb482027-b980-4df2-8c47-2765d55f141b)
![image](https://github.com/pybricks/support/assets/69276/79653182-68fa-4b5f-857c-4f5cd566fa30)

Also the documentation for the `hold` option is missing - possibly because the Python translation is not straightforward (pun originally not intended).
![image](https://github.com/pybricks/support/assets/69276/b563dadc-332e-4cdd-a884-dcc35053d28c)
</div>

**Comment by laurensvalk** [comment]
Thanks for reporting. We recently [enabled brake for the drivebase](https://github.com/pybricks/support/issues/881) specifically for this reason, but it hasn't made it into the blocks yet.

For hold, indeed, there is technically not an equivalent, so we made it just drive 0 distance and hold there, which has the same effect.

**Comment by ggramlich** [comment]
@laurensvalk 
Any chance to have the fix for the translation of the option "brake" to `drivebase.brake()` in one of the next updates?
It is not a big deal, I am just a bit worried that the kids might use the option "brake" and then with some update shortly before the competition the behavior of the robot changes slightly.
(I plan to switch to the stable version middle of March anyways.)

**Comment by laurensvalk** [comment]
Thank you. Yes. With the big update for Xbox control out now, I'd like to start fixing as many small issues like these as possible.

**Comment by laurensvalk** [comment]
Fixed and merged. Should be coming out in next release.

**Comment by laurensvalk** [comment]
Thanks for reporting!
