### ISSUE TITLE
[Question] Pybricks on ev3dev installed on a raspberry pi 3 with BrickPi3

### ISSUE THREAD

**Issue by iwanimsand** [pybricks/support#135]
**Question**
Should it possible to run pybricks on ev3dev on a raspberry pi 3 with BrickPi3? Or is it not supported?

**Context**
I tried to run my EV3 motors with a raspberry pi and a BrickPi3. It works with the ev3dev2 library. I would like to use pybricks with this hardware, but the motors not reacting, nothing happens (tried https://github.com/pybricks/pybricks-projects/blob/master/snippets/pup/motor/motor_action_basic.py). The program runs and outputs the print statements, but motors not moving.

**Screenshots**
-

**Comment by dlech** [comment]
No, Pybricks is designed for EV3 only and won't work on Raspberry Pi.
