### ISSUE TITLE
Pybricks Connection Problem

### ISSUE THREAD

**Issue by sjlct123** [pybricks/support#1368]
I want to connect my Lego Mindstorms 51515 Hub to pybricks and install the pybricks firmware but it dosnt work. I can't even install WinUSB driver. It glitches with error code 10. I was doing it on a lg gram 2022 laptop running windows 11.

I expected the firmware to be installed on my hub correctley.

<img width="399" alt="Screenshot 2024-01-05 072125" src="https://github.com/pybricks/support/assets/155669947/9dab3631-ecfb-4e2c-9dd7-50cf03b50bed">

**Comment by dlech** [comment]
Does the device show up in the Windows *Device Manager* as "LEGO Technic Large Hub in DFU Mode"?

Do you have a different computer you could try?

**Comment by sjlct123** [comment]
No it doesn't show up as Lego technic large hub in dfu mode and I don't have any other computers to try it on.

**Comment by dlech** [comment]
Is the Bluetooth light on the hub blinking red (pink)/green/blue/off? If not, then the hub is not in DFU mode and that is the problem. If it is, I would try deleting the device from the Device Manager and start over.

**Comment by sjlct123** [comment]
It was in dfu mode but it didn't show up.

**Comment by dlech** [comment]
Can you share a screenshot of your *Device Manager*? There should be something in there with a :warning: icon if the driver is not loading correctly.

**Comment by sjlct123** [comment]
<img width="161" alt="Screenshot 2024-01-07 065154" src="https://github.com/pybricks/support/assets/155669947/64f3cee8-0299-45fa-8820-05659819930c">

**Comment by dlech** [comment]
If you right-click that and select *Uninstall device* then disconnect the hub and plug it back in (making sure to hold the Bluetooth button to get DFU mode) what does it say?

**Comment by sjlct123** [comment]
It dosen't even show up on device manager anymore.

**Comment by dlech** [comment]
Maybe there is a bad USB cable or something like that?

**Comment by sjlct123** [comment]
I tried a different cable but it still didn't work.

**Comment by dlech** [comment]
On my Windows 11, if I uninstall the device like I mentioned in https://github.com/pybricks/support/issues/1368#issuecomment-1879778338 and then unplug the hub and plug it back in, I see this:

![image](https://github.com/pybricks/support/assets/963645/e422094b-2ecc-4c43-a104-d6a7ae7f95e0)

You are not seeing this after following the same steps?

**Comment by sjlct123** [comment]
Yes.

**Comment by sjlct123** [comment]
I don't think it's my computer. I tried it on another computer but it didn't work. Thank you.

**Comment by laurensvalk** [comment]
This has come up in several other topics. In those cases, using a different (or the original) USB cable fixed it. Let's close this issue until this occurs again. Thanks!
