### ISSUE TITLE
[Question] Blinking blue light when running code standalone CityHub

### ISSUE THREAD

**Issue by wcnvessies** [pybricks/support#137]
I have written a program for the CityHub and it uses the light on the CityHub. If I run the code when the CityHub is connected with a PC it runs fine, no problems. When I run the program standalone from the CityHub, no PC connected it works, but only the light of the CityHub blinks blue due to searching for connectivity. 

How to switch of the blinking blue light and use the light colour as programmed, when the code run as a standalone program?

```
from pybricks.hubs import CityHub
from pybricks.pupdevices import Motor, ColorDistanceSensor
from pybricks.parameters import Port, Stop, Color
from pybricks.tools import wait

# motor
hub = CityHub()
motor   = Motor(Port.A)
motor.reset_angle(0)
sensor  = ColorDistanceSensor(Port.B)

# parameters
speed   = 6*171*10  # [deg/s]
deg     = 180/2.5   # [deg] gear ratio 1:2.5 turn 180 deg
time    = 5*1000    # [sec]

while True:
    if  sensor.distance() <= 30:
        hub.light.on(Color.RED)
        sensor.light.on(Color.RED)
        motor.run_target(speed, deg, then=Stop.BRAKE, wait=True)
        
        wait(time)
        
        motor.run_target(speed, 0, then=Stop.BRAKE, wait=True)
        sensor.light.on(Color.GREEN)
        hub.light.on(Color.GREEN)
```

**Comment by dlech** [comment]
Thanks for the feedback. This is something on our todo list. Currently, Bluetooth advertising doesn't stop when running a program, which is why the light keeps blinking.
