### ISSUE TITLE
[Bug] unpack block does not set globals correctly

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#1410]
> Broadcasting and receiving values work fine, however, the variables won't update in the entire program at once. See my simple program attached. I have two parallell programs running at different intervals. One hub sends the "TriggerDistributor" value (true) by broadcasting. This value won't be changed for about three seconds or so, and then go back to being false. This is picked up by the first print function and shows in the console, however the other print function in the lower program will always print false. This is a problem since I'm using these values in different parts of the program, usually with "wait until" blocks, waiting until the variable becomes true.

<img width="724" alt="Skärmavbild 2024-02-01 kl  22 26 48" src="https://github.com/pybricks/support/assets/31407689/3d3aedd7-d62e-4ae0-9cf3-a1a7a24f661a">

_Originally posted by @JJHackimoto in https://github.com/pybricks/support/discussions/1373#discussioncomment-8339692_

**Comment by laurensvalk** [comment]
This is the correct behavior:

![image](https://github.com/pybricks/support/assets/12326241/0d8a7353-b464-4c2b-9788-9fa9becfc978)

But when we use multitasking with async, it packs that stack of blocks into a function. So to set variables, it has to make them global, but it doesn't:

![image](https://github.com/pybricks/support/assets/12326241/7e25d6af-81d3-4441-bbf7-489932e66a63)

**Comment by laurensvalk** [comment]
This is better! Fix should be coming soon...

![image](https://github.com/pybricks/support/assets/12326241/b43d36c9-c72f-44ef-a734-d3b21e424908)

**Comment by laurensvalk** [comment]
Fix is out. Let me know how it goes :sunglasses: 

![image](https://github.com/pybricks/support/assets/12326241/3ddd5d7f-b259-40f9-b640-16e3803f46e5)

**Comment by BertLindeman** [comment]
> Fix is out. Let me know how it goes 😎


Takes more time, obviously, after "check for update" and "Already up to date":


```
About Pybricks Beta
Pybricks logo
MicroPython for LEGO® Powered Up smart hubs.

v3.3.0 (Pybricks Beta v2.4.0-beta.1)

Copyright (c) 2020-2023 The Pybricks Authors

LEGO® is a trademark of the LEGO Group of companies which does not sponsor, authorize or endorse this site.
```

**Comment by JJHackimoto** [comment]
> Fix is out. Let me know how it goes 😎
> 
> ![image](https://private-user-images.githubusercontent.com/12326241/301798467-3ddd5d7f-b259-40f9-b640-16e3803f46e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4OTcxOTUsIm5iZiI6MTcwNjg5Njg5NSwicGF0aCI6Ii8xMjMyNjI0MS8zMDE3OTg0NjctM2RkZDVkN2YtYjI1OS00MGY5LWI2NDAtMTZlMzgwM2Y0NmU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE4MDEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwNzQ4NGJkNDEyNWQ0YjBlZmI3MGM4YzVkMjFlOWI0MzY2MGU1NmZkODA1NjgzN2U5NzkzMzY3YWMyYjMzMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UQO_JdsoGa2xeaCMbpTS0uoTPV89_6va8Adi712-bjg)

Worked perfectly! Thank you for submitting the report and fixing it so quickly!

**Comment by laurensvalk** [comment]
Glad to hear it. And thank you for raising this. This was easily fixed, but would cause plenty of confusion in multi-tasked broadcasting, which is complex enough when it is working correctly :smile:
