### ISSUE TITLE
[Bug] Block Coding: Logic Block Comparison "<" (less than) shows "left trigger"

### ISSUE THREAD

**Issue by ggramlich** [pybricks/support#1439]
**Describe the bug**
The way the logic block for comparisons with option "< True if left value is smaller" is displayed, is broken since one of the last updates. It shows "left trigger" instead of "<".

**To reproduce**
Pull a comparison block from the Data -> Logic section into the program an switch to "<"

**Expected behavior**
The block should read "3 < 4".
It actually reads "3 left trigger 4"

**Screenshots**
![pybricks_issue_lessthan](https://github.com/pybricks/support/assets/69276/879bc239-5996-424c-92bf-759ec9fa3bb9)

**Comment by laurensvalk** [comment]
Oops! Thanks for catching this.

Looks like I've used the same translation key twice. I wonder what the left trigger is for...

By the way, although we released the blocks originally on the beta channel, you can now switch it to the stable version to avoid surprises like these.

**Comment by laurensvalk** [comment]
This should be fixed in the beta release update coming this week.

**Comment by ggramlich** [comment]
> By the way, although we released the blocks originally on the beta channel, you can now switch it to the stable version to avoid surprises like these.

Is there a way to find out, which stable version of block coding corresponds to which beta version?
The https://github.com/pybricks/pybricks-code/blob/master/CHANGELOG.md does not seem to reflect the current state.

Do we need to deactivate the license key in beta or can we use the same license key for beta and stable?

**Comment by laurensvalk** [comment]
> Is there a way to find out, which stable version of block coding corresponds to which beta version?

This part of the changelog isn't available yet, but we're working on it. Thanks!

> Do we need to deactivate the license key in beta or can we use the same license key for beta and stable?

You can use both at the same time.

[![image](https://github.com/pybricks/support/assets/12326241/f12b9edc-723c-48c9-ba3e-139132a7e685)](https://pybricks.com/premium/)

**Comment by laurensvalk** [comment]
Fix has been released in latest beta.
