### ISSUE TITLE
[Feature] Move Hub build size

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#1453]
**Is your feature request related to a problem? Please describe.**
It's that time of year again where the Move Hub is almost out of space.

This makes it difficult to merge small fixes, e.g. to motor drivers.

I think the Move Hub is pretty much feature complete, so we shouldn't need all that much.

**Describe the solution you'd like**

One of these might work:
- Optimize other code to find space.
- Disable some functionality.
- Reduce user code space (now 4K, which is higher than the 2K we had originally).

**Comment by laurensvalk** [comment]
For context, it's not currently as high as it has been several times previously; we just increased the user space the last time we found a lot of space.

![image](https://github.com/pybricks/support/assets/12326241/ffbd3b4e-e813-4023-9c5b-72722db318c5)

**Comment by dlech** [comment]
There have been quite a few size reductions in upstream MicroPython in the last few releases, so I think the first step should be to update that.

**Comment by laurensvalk** [comment]
Great idea!

**Comment by laurensvalk** [comment]
This should keep Move Hub going for another year or more: https://github.com/pybricks/pybricks-micropython/pull/240

Especially if we only use that space for bug fixes rather than new features.

**Comment by laurensvalk** [comment]
With about 2.8Kb free for future bug fixes even after adding a substantial new feature (the `Car` class), I think this is good enough for this issue.
