### ISSUE TITLE
[Bug] Technic Hub randomly disconnects ``` GATT Error Unknown. ` ``

### ISSUE THREAD

**Issue by Onako2** [pybricks/support#1477]
**Describe the bug**
Technic Hub randomly disconnects when sending the program to the hub. The Spike Prime/Mindstorms Hub works fine. When sending it to the hub it stops at sometimes 1/3 or 1/2

**To reproduce**
1. Click on 'Run this program (F5)'
2. Stop the program
3. Wait a few minutes
4. Click on 'Run this program (F5)'
5. See error

**Expected behavior**
What did you expect to happen instead?
The hub shouldn't disconnect

**Hardware/Software**
- Technic Hub
- Windows 11
- Surface Pro 8(Drivers are up-to-date)
- Google Chrome

**Screenshots**
There is a saying that a picture is worth a 1000 words. Screenshots really help to identify and solve problems.
![image](https://github.com/pybricks/support/assets/79749977/641bb823-f3b1-458a-8c7a-cfa86dc187d0)

**Comment by Onako2** [comment]
I just saw that there is already an issue xD #1473

**Comment by gyenesvi** [comment]
Are you sure you quoted the right issue above? It does not seem to be related.

**Comment by Onako2** [comment]
> Are you sure you quoted the right issue above? It does not seem to be related.

xD Didn't notice it [#1468](https://github.com/pybricks/support/issues/1468)
