### ISSUE TITLE
[Bug] XBOX controller button pressed translated wrong in python

### ISSUE THREAD

**Issue by DanieleBenedettelli** [pybricks/support#1524]
**Describe the bug**
What is the problem?
![pybricks_program_2024-03-07T22_05_26](https://github.com/pybricks/support/assets/47357389/d232ee32-4bcf-4514-92e0-ead0703d9fcf)
The controller button reporter blocks are translated into:
`if "Y" in controller.buttons.pressed():
        lifter.run_target(200, 140, Stop.BRAKE)
        print('up')
    elif "A" in controller.buttons.pressed():
        lifter.run_target(200, 0, Stop.BRAKE)
        print('down')
    else:
        pass`

while the correct code should be:
`if Button.Y in controller.buttons.pressed():
        lifter.run_target(200, 140, Stop.BRAKE)
        print('up')
    elif Button.A in controller.buttons.pressed():
        lifter.run_target(200, 0, Stop.BRAKE)
        print('down')
    else:
        pass`

The translation is wrong for every button of the controller

**Comment by BertLindeman** [comment]
Daniele,

I simulated this at:
```MicroPython for LEGO® Powered Up smart hubs.

v3.4.0b3 (Pybricks Beta v2.4.0-beta.6)

Copyright (c) 2020-2023 The Pybricks Authors
```

![pybricks_program_2024-03-07T22_44_36](https://github.com/pybricks/support/assets/8142081/8e501ac5-60b8-41d5-83fa-05bda92ab9a9)

The python code generated:
```python
from pybricks.iodevices import XboxController
from pybricks.parameters import Button

# Set up all devices.
controller = XboxController()


# The main program starts here.
if Button.Y in controller.buttons.pressed():
    print('Y')
elif Button.A in controller.buttons.pressed():
    print('A')
else:
    pass

```

Are you using the stable code.pybricks.com?

Bert

**Comment by laurensvalk** [comment]
Thanks for reporting @DanieleBenedettelli.

Coincidentally, this was fixed yesterday! Your version might not have reloaded just yet.

![image](https://github.com/pybricks/support/assets/12326241/0a078452-70c7-49cf-8283-c3d05ac64287)

Thanks @BertLindeman for confirming that it was fixed.

**Comment by DanieleBenedettelli** [comment]
Exactly that.
Once SHIFT+F5 reloaded, it worked.

D

Il giorno ven 8 mar 2024 alle ore 08:23 laurensvalk <
***@***.***> ha scritto:

**Comment by laurensvalk** [comment]
Just opening the app again should automatically load it, so you don't even have to wait :smile:
