### ISSUE TITLE
[Feature] Transfer focus to I/O window after starting program

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#155]
**Is your feature request related to a problem? Please describe.**
When pressing the run button in Pybricks Code, the code runs and the cursor/keyboard isn't focused in any pane in particular.

**Describe the solution you'd like**
It would be nice to have it focused in on the standard i/o pane, so that programs that use `input()` or `getchar()` #154  work right away.

**Describe alternatives you've considered**
Manually clicking on it every time.

**Comment by JorgePe** [comment]
Was thinking the same

**Comment by dlech** [comment]
Will this confuse users who don't use the terminal for input? They might expect if they start typing that what they are typing would still be in the code pane (although the cursor would be gone which gives some hint).

Should the program stopping also switch focus back to the code pane?

**Comment by JorgePe** [comment]
It might confuse. Is it possible to define it as an advanced setting, disabled by default?

**Comment by laurensvalk** [comment]
Well, the cursor isn’t currently focused in the editor after clicking run either. It would be nice if it was though.

There’s another problem, which is that the download and run logic is affected by the I/O window for now. So, let’s not change focus to the terminal for now.
