### ISSUE TITLE
[Feature] Add block or method to reset drivebase odometry

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#1550]
**Is your feature request related to a problem? Please describe.**
The `DriveBase.reset()` method is not currently available as a block

**Additional context**
Requested by @MonongahelaCryptidCooperative

**Comment by laurensvalk** [comment]
Proposed block:

![image](https://github.com/pybricks/support/assets/12326241/96689a25-ffbc-4fe3-8ce0-efe709cbc57c)

**Comment by MonongahelaCryptidCooperative** [comment]
Exactly what is needed. With this and the ability to change the shit down
button we should be able to do our FLL block starter pack code without
having to import anything. It will make it much less intimidating for new
teams.

**Comment by laurensvalk** [comment]
@MonongahelaCryptidCooperative - this is now available in the latest beta version.

![image](https://github.com/pybricks/support/assets/12326241/53b537b4-01c8-4de9-a410-3f271be10abc)
