### ISSUE TITLE
[Bug] xbox controller disconnect with pybricks

### ISSUE THREAD

**Issue by WuHank** [pybricks/support#1588]
Please do me a favor.

**Describe the bug**

xbox controller can connect with Microsoft surface go 3, but disconnect with the pybricks

**To reproduce**
1. have update the xbox controller 

2. the version of pybricks is:
MicroPython for LEGO® Powered Up smart hubs.
v3.4.0 (Pybricks Code v2.4.0)

3. type the basic code to ensure it as follow: 

from pybricks.iodevices import XboxController
from pybricks.parameters import Button

# Set up all devices.
xbox = XboxController()

# The main program starts here.
if Button.A in xbox.buttons.pressed():
    print('A')
elif Button.Y in xbox.buttons.pressed():
    print('Y')
else:
    pass

**Expected behavior**

Is the controller problem? 
or the model of the controller can't work?

**Screenshots**
1. xbox controller does conncet with the surface go 3:
![pybricks 02](https://github.com/pybricks/support/assets/166269314/ef933dab-c4ee-43ac-9751-8fcaa15b2107)

2. xbox controller have updated:
![pybricks 03](https://github.com/pybricks/support/assets/166269314/9e41aa9c-027b-42be-8104-d0aa70caec01)

3. The version of Pybricks:
![pybricks 04](https://github.com/pybricks/support/assets/166269314/d1d0c2f9-1420-472a-88eb-7da6c6d21474)

4. The pic of pybricks and the program that tests the connection:
![pybricks 01](https://github.com/pybricks/support/assets/166269314/8bf438f9-3ed0-4d98-96a4-329277021f5a)

Thank you!

**Comment by BertLindeman** [comment]
It will be very hard to see if your xbox controller does connect.

As soon as the xbox controller does connect, the program is ready in milliseconds.
There is no time to see anything.
 
I am not sure:
1. no connection - can be. did you press the connect button on the controller to allow it to connect to the spkie hub?
2. if connected - the program does not allow you time to do anything.

You might add a loop to do this test over and over.

Maybe like this:

![pybricks_program_2024-04-07T07_16_30](https://github.com/pybricks/support/assets/8142081/16e5bad7-6670-42de-bd9a-4cfa90864140)


Or even: 

![pybricks_program_2024-04-07T07_24_27](https://github.com/pybricks/support/assets/8142081/bee8f185-7376-4956-bcbf-43c61fc35f69)

**Comment by WuHank** [comment]
> I am not sure:
> 
> 1. no connection - can be. did you press the connect button on the controller to allow it to connect to the spike hub?

I thought the controller only need to be connected with the surface go 3.
Could you tell me how to confirm the controller does connect with the spike prime?

> 2. if connected - the program does not allow you time to do anything.
> 
> You might add a loop to do this test over and over.

Thank for your help.  
You're so kind!
I also try the Pybricks Beta version.
But it still can't work.
Could you help me?
Thank you!

1. try the Pybricks Beta version
![pybricks 05](https://github.com/pybricks/support/assets/166269314/675a7727-edf0-42a8-80ac-664b2e6d1e40)

2. Thanks for your suggestion.  I fix the code but it still can't work.
![pybricks 06](https://github.com/pybricks/support/assets/166269314/21a94889-bf93-41c9-9ea4-d6cd31b43326)

Thanks a lot!
Please help me!

**Comment by BertLindeman** [comment]
> I thought the controller only need to be connected with the surface go 3.
Could you tell me how to confirm the controller does connect with the spike prime?

The xbox controller does NOT connect to the PC or table or so, it connects to the hub.
In your case the spike hub.



From the pybricks documentation:
```
Xbox Controller Pairing Instructions
[¶](https://docs.pybricks.com/en/latest/iodevices/xboxcontroller.html#xbox-controller-pairing-instructions)

The first time you use a controller with a hub, you will need to pair them: 
Turn the controller on and then press and hold the pairing button on the back of the controller for a few seconds. When you release it, the Xbox button starts flashing more rapidly. 
Then start your program.

When pairing and the connection is succesful, the Xbox button will stop flashing and stay on for as long as the program is running.
```

To confirm the connection is there, you could add a block to change the color of the hub button,
or display some text on the hubs display.
Like this one:
![afbeelding](https://github.com/pybricks/support/assets/8142081/09eec688-ef34-456b-a75e-7f7e983f51c2)

So you would see immediately success.

**Comment by WuHank** [comment]
> So you would see immediately success.

It's amazing!
It works!
Thank you so much!
Have a good day!

**Comment by BertLindeman** [comment]
> > So you would see immediately success.
> 
> It's amazing! It works! Thank you so much! Have a good day!

You make my day! 😄 

It is hard to explain the various blinking of the controller.
Could you explain what made the difference for you?

**Comment by WuHank** [comment]
> Could you explain what made the difference for you?

As my observation, there are 2 modes of blinking.
The rhythm are differents:
1. Before press the pairing button.
The rhythm is triplets.
1st and 2nd beat are flashing.

2. After press the pairing button.
The rhythm is like disco.
It's 4 beat.(also 2 beat, up beat and down beat)

After all, like the manual say.
When pairing and the connection is succesful, the Xbox button will stop flashing.

I'm so happy it finally done.
I almost give up.
Thank you !

**Comment by laurensvalk** [comment]
Glad it worked @WuHank  and thank you @BertLindeman  for helping!
