### ISSUE TITLE
[Question] How do I calibrate the NXT Compass Sensor?

### ISSUE THREAD

**Issue by althonich** [pybricks/support#159]
**Question:**
How do I calibrate the NXT Compass Sensor?

**Context:**
I was (and still am) trying to make a program that allows my robot to go in a straight line with the help of a PID. I noticed that my compass readings are inaccurate and attempted to recalibrate it to get better readings, but I don't know how to do so!

Any help will be greatly appreciated!

**Screenshots:**
![Screenshot 2](https://user-images.githubusercontent.com/73888096/97984381-abc4a280-1e11-11eb-8f2f-b54094189101.png)

Below is the code I have tried...

![Screenshot 1](https://user-images.githubusercontent.com/73888096/97984411-b67f3780-1e11-11eb-816c-0a2fa393d2a2.png)

**Comment by laurensvalk** [comment]
The `Ev3devSensor` class has no `write` method, but you can add one. Have a look at the **second example** [here](https://docs.pybricks.com/en/latest/iodevices.html#pybricks.iodevices.Ev3devSensor).

It shows how you can add a method `get_modes`. It sounds like you want to add a method like `write_command`, which could look something like this:

```python

    def write_command(self, command):
        """Write to the command attribute."""

        # Open the command file.
        with open(self.path + '/command', 'w') as command_file:

            # Write the command.
            command_file.write(command)
```

**Comment by Boss-Chicken** [comment]
> The `Ev3devSensor` class has no `write` method, but you can add one. Have a look at the **second example** [here](https://docs.pybricks.com/en/latest/iodevices.html#pybricks.iodevices.Ev3devSensor).
> 
> It shows how you can add a method `get_modes`. It sounds like you want to add a method like `write_command`, which could look something like this (I have not tested this):
> 
> ```python
>     def write_command(self, command):
>         """Write to the command attribute."""
> 
>         # Open the command file.
>         with open(self.path + '/command', 'w') as command_file:
> 
>             # Write the command.
>             command_file.write(command)
> ```

I don't have much experience messing around with classes, can you please show me how to do it without the classes?

Thanks!

**Comment by laurensvalk** [comment]
Have you looked at the example I linked to? You can add the method shown here just below the `get_modes` method.

**Comment by Boss-Chicken** [comment]
I'll try it out and let you know how it goes, thanks!

**Comment by dlech** [comment]
Is this still a problem?
