### ISSUE TITLE
[Feature] Is there any function like "thread" (not multitask) implement in pybricks with SPIKE Prime?

### ISSUE THREAD

**Issue by a10036gt** [pybricks/support#1609]
In robotics programing, we ofter using thread or multi task to do some staff, for example, WRO RoboSport we have a main task to do, and other task will doing sensor processing, odometry task..., like following image:

![EV3G-Thread](https://github.com/pybricks/support/assets/17724013/042bb011-7766-46d1-a490-4f22d179d130)

Here is the video about robot run: https://youtu.be/a0pwdxfojIo?si=5DHkKBV64Dm3L_QP&t=1384

The Pybricks provide the multitask but it works not well for us, because the task is in while loop and can't get out. We want to import  _thread but it has been remove in firmware.

Is there anyway to doing this kind of function? Following code is a arduino with FreeRTOS, that's the things we want to do:
![image](https://github.com/pybricks/support/assets/17724013/f4ebf5d4-2782-40b1-ba70-a4cd9736bd30)

Thanks!

**Comment by a10036gt** [comment]
And As I know the SPIKE App doing in similar way to solve the thread problem:

Scratch block:
![image](https://github.com/pybricks/support/assets/17724013/10a3d28d-0cd5-4861-9ec4-fa6793ddc154)


Compiled Code:
`# When program starts
async def stack(this):
    while True:
        with this as event:
            await event
            # Control repeat
            for _ in range(10):
                # Light display image on for time
                hub.light_matrix.show([int((int(p) * (global_state[DISPLAY_BRIGHTNESS] / 9)) + 0.5) for p in "9909999099000009000909990"])
                try:
                    await this.wait(2000)
                except scratch._StackStop as ex:
                    hub.light_matrix.clear()
                    raise ex
                hub.light_matrix.clear()
                yield

# When program starts
async def stack_1(this):
    while True:
        with this as event:
            await event
            # Control forever
            while True:
                # Play sound until done
                if tunnel.connected():
                    corr = (global_state[TUNNEL_CORRELATION] + 1) % 255
                    global_state[TUNNEL_CORRELATION] = corr
                    await send_tunnel_data(struct.pack(">BBIBhb", 23, corr, 2365347937, int(global_state[SOUND_VOLUME] + 0.5), int(global_state[SOUND_PITCH] + 0.5), int(global_state[SOUND_PAN] + 0.5)))
                    try:
                        await request_tunnel_data(corr, False)
                    except scratch._StackStop as ex:
                        await send_tunnel_data(struct.pack(">BB", 27, corr))
                        raise ex
                yield

vm = scratch.VM()
vm.add_start(stack)
vm.add_start(stack_1)
vm.run()`

**Comment by laurensvalk** [comment]
Yes, you can do that by just adding another start block:

![image](https://github.com/pybricks/support/assets/12326241/a031421f-26ea-4857-ae1a-f549248c4d5c)

**Comment by a10036gt** [comment]
OK I give a try and it work, but seems if I have any while loop in task, I need add await wait(1), or other task will be block?

**Comment by laurensvalk** [comment]
>  I need add await wait(1), or other task will be block?

This is done for your automatically.

![image](https://github.com/pybricks/support/assets/12326241/7ced0e13-e1a8-43d0-8bc1-2123eba2ecef)

If you have an example where that was not done correctly, please let us know and we'll fix it.

Maybe we'll also add an option to omit the `wait(1)` so advanced users can turn it off. After all, they aren't needed in this example since the loops contain other awaitables.

**Comment by a10036gt** [comment]
I using Python mode not block mode, I mean seems it is necessary to add wait(1) in any loop I use in task? Because When I remove it, seems other task will be block.

**Comment by laurensvalk** [comment]
Yes, it is generally necessary in loops that take a some time (or forever) if they don't already have anything awaitable inside. This is how `async`/`await` works, also in official MicroPython or the standard LEGO firmware.

Having such a wait allows your code on other "tasks" to be executed.

**Comment by a10036gt** [comment]
OK, I see, thanks!
