### ISSUE TITLE
[Feature] Is there any function can directly contorl the PWM of each port?

### ISSUE THREAD

**Issue by a10036gt** [pybricks/support#1613]
Is it possible to implement a "pwm" method to drive the pin 1 and 2?

Not like the motor.dc() command, I want to build a custom sensor but I want using the pwm power at P1 P2 at same time, but due to Auto ID Check function, I can't use motor.dc() command and PUPDevice command at same time, is there any solution?

Thanks!

**Comment by a10036gt** [comment]
Yes I emulating the Powered Up protocol on arduino and STM8.

**Comment by a10036gt** [comment]
That's because we want to using the PWM power (battery power) to driving some heavy load parts, like Pixy 2 Camera or something like that. Because 3v3 may not have that high current to push these devices.

**Comment by a10036gt** [comment]
Like SPIKE Ultrasonic and Color sensor, their LEDs is actually powered by P1 P2 100% PWM.

**Comment by dlech** [comment]
It isn't actually possible to turn on both outputs at the same time. This is the table from the motor driver datasheet.

<img width="586" alt="image" src="https://github.com/pybricks/support/assets/963645/1370df46-c5b6-4ec4-8902-a3e2725ad7da">

The LEGO sensors/lights will bring either P1 or P2 high, but not both at the same time.

If you are using the LEGO UART protocol, then you can set the appropriate flag for the pin you want to use for power in the extended info that is embedded in `INFO_NAME`. See https://github.com/pybricks/technical-info/blob/master/uart-protocol.md#info_name

<img width="426" alt="image" src="https://github.com/pybricks/support/assets/963645/05c53bb4-f92c-4739-9788-97f14d80b532">

**Comment by a10036gt** [comment]
Oh I didn't noticed that appropriate flag before, my bad, I will try to add that into my code, thank you so much!
