### ISSUE TITLE
[Feature] Relax speed cap for external Boost motor

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#1623]
> (...) the speed cap on the external Boost motor is a bit too strict.

_Originally posted by @laurensvalk in https://github.com/pybricks/support/discussions/1620#discussioncomment-9264013_

----- 

This was brought to our attention by @andybellgbc. Thank you!

**Comment by laurensvalk** [comment]
If you are feeling up to it, feel free to change `1000` to `1200` [here](https://github.com/pybricks/pybricks-micropython/blob/79a0e010ac36fb64593d5ef5b213b64f1a03985b/lib/pbio/src/motor/servo_settings.c#L244) by editing/forking via [this link](https://github.com/pybricks/pybricks-micropython/edit/master/lib/pbio/src/motor/servo_settings.c#L244). (Can all be done in the browser, no external tools required). Otherwise no worries, and we'll get this done eventually :)

**Comment by andybellgbc** [comment]
I am a patient man... and a novice coder. I was able to run the Boost motor with no issues at a higher rate this lunchtime.  So I probably won't be forking the project, but will make use of the functions.
