### ISSUE TITLE
The print command causes software crash

### ISSUE THREAD

**Issue by kueden** [pybricks/support#163]
**Describe the bug**
Repeated print commands cause crash of the Technic Hub

**To reproduce**
1. Run the "test.txt" code on the technic hug
2. remote control it with the keyboard
3. after a few commands it freezes
4. removing the print command solves the issue. 

**Expected behavior**
It would be nice to have the print command though.

**Screenshots**

[test.txt](https://github.com/pybricks/support/files/5506588/test.txt)

```python
from pybricks.pupdevices import Motor
from pybricks.parameters import Port, Stop
from pybricks.tools import wait, StopWatch
from pybricks.hubs import TechnicHub
from pybricks.parameters import Color
import math
from pybricks.experimental import getchar


mr = Motor(Port.D)
ml = Motor(Port.C)
watch = StopWatch()
hub=TechnicHub()
x=0
y=0
t0=0



while True:
    c = getchar()
    if c == ord('w'):
        x=x-1
    elif c == ord('r'):
        x=x+1
    elif c == ord('o'):
        y=y+1
    elif c == ord('l'):
        y=y-1
    
        

    lis=[x,y]
    print(lis)
    ml.dc(x)
    mr.dc(y)
    wait(1)
   
```

**Comment by laurensvalk** [comment]
Thanks for the report.

By the way, you can include the code directly in your post instead of attaching it. It works like this:

![image](https://user-images.githubusercontent.com/12326241/98471660-33cdf200-21ee-11eb-81af-64b4d0026f86.png)

**Comment by kueden** [comment]
Thanks, I was wondering how you guys do this. My copy paste attempts failed
miserably.

I really appreciate what you guys are doing and I am happy to contribute.
However I do not want to overload your site with my stuff.

I have another project series working towards an autonomous robot with
spatial orientation written in your python code:
https://rebrickable.com/mocs/MOC-51737/kueden/hom3runn3r-ii/#details

If you want me to share it here let me know.

Markus

laurensvalk <notifications@github.com> schrieb am So., 8. Nov. 2020, 18:15:

**Comment by laurensvalk** [comment]
No problem. You can still edit your initial post to make this change if you like.

Don't worry about overloading - feel free to share! Especially if you want to discuss some Pybricks tips and tricks that others might find useful.

**Comment by dlech** [comment]
possibly related print() bug: #36

**Comment by dlech** [comment]
There have been significant changed made to Bluetooth in firmware v3.0.0b3. Can you please upgrade the firmware and test again?

**Comment by kueden** [comment]
Thanks David

It works perfetly well! No crash after extensive testing.

Thanks for all your help

Markus

**Comment by kueden** [comment]
thanks for this!

**Comment by kueden** [comment]
David
I got it to work, but there is another issue. There is a bug with the
v3.0.0b3. I can connect via blootooth. But the play bottun (F5 for download
and run) does not light up. I played around and got it to work. My original
issue is resolved. However I cannot reproducibly get software to run since
the play button does not show up. Eventually things run. I also learned
playing with it that the "getchar" that I use in all my software (issue
#154) is not available in this new version

So it looks like my minor issue is resolved, but I cannot run my software
any more due to the not active play buttion and the missing getchar
function. Now it is very probable that this is my lack of competence. I
tried on another computer. Same thing.

Thanks for all your help

Markus

**Comment by laurensvalk** [comment]
See #287. It looks like this is affecting more people since a recent update.

**Comment by kueden** [comment]
Thanks

Indeed exactly the same. No rush from my side to get this fixed. If you
could implement the getchar command in this version, this would be
appreciated.

Thanks

Markus

laurensvalk ***@***.***> schrieb am Sa., 3. Apr. 2021, 15:16:

**Comment by laurensvalk** [comment]
`getchar` has been replaced by more standard tools that can do the same thing, and more.

See [this commit message](https://github.com/pybricks/pybricks-micropython/commit/65b8ec05153d8f6c67782249d20db5f03969dbb8) for details. It would be nice to include this in an example at some point.
