### ISSUE TITLE
Communicating between a computer and the hub via bluetooth

### ISSUE THREAD

**Issue by giadefa** [pybricks/support#164]
Is it possible to establish a communication between my computer and the HUB via bluetooth to send commands? At the moment bluetooth seems to be used only to transfer the python program into the hub and remotely start it. It does seem in theory possible to speak to the hub after  the program has started but how?  I have a spike hub and Control+ hub.

**Comment by laurensvalk** [comment]
With some effort, yes, this is already possible. It depends on what you are after. Can you elaborate on your use case?

> establish a communication between my computer and the HUB via bluetooth to send commands

If I interpret this literally, #154 may be what you are after.

We also have a python library to interact with the hub. See also #156 for some hints. Is this closer to what you might need?

**Comment by giadefa** [comment]
I would like to send commands from a normal python3 environmnet under linux  and receive back data from the hub, like motor encoder readings.

**Comment by giadefa** [comment]
#156 seems to be ok to send commands but not to receive data if I read it correctly.

**Comment by laurensvalk** [comment]
Everything that the hub prints is available to read using the hub.output property, so you could send data back that way.

The pybricksdev library is mainly something we’ve been using internally for development, so that’s why it’s not as well documented as the main Pybricks API. It sounds like more people are interested in this too though, so maybe we should document it.

**Comment by giadefa** [comment]
Thanks and by the way pybrick is very nice. I was really happy to see it when it appeared.

**Comment by laurensvalk** [comment]
Thanks! Looking forward to see what you’ll make.

Support for SPIKE Prime is around the corner as well.

**Comment by laurensvalk** [comment]
This use case would be covered by scenario 1 in #262, which is in progress, so we can close this issue.
