### ISSUE TITLE
Is City Hub incompatible with Xbox Controller?

### ISSUE THREAD

**Issue by AlmazKad** [pybricks/support#1685]
**Describe the bug**
Is City Hub incompatible with Xbox Controller?

**To reproduce**
1. Installed Pybricks Firmware on City Hub, used the code from the link:
https://pybricks.com/project/technic-42124-xbox/#running-it-as-a-python-program
2. tried to connect the Xbox Controller, and this happened:
Traceback (most recent call last):
  File "Buggy02.py", line 4, in <module>
ImportError: can't import name XboxController

Then repeated the same thing in the beta version, the result is the same error
But everything works as expected with other hubs

The question is, is City Hub compatible with Xbox Controller?

**Screenshots**
![Снимок экрана 2024-06-23 145522](https://github.com/pybricks/support/assets/173609126/9ecf06f3-7bad-4a09-987d-7769d070d109)

**Comment by BertLindeman** [comment]
You are correct according to the current documentation: 

![afbeelding](https://github.com/pybricks/support/assets/8142081/86a5c689-f094-42d7-84fd-9879c0ef11f2)

Tested with the current beta firmware:
`'cityhub', '3.5.0', 'v1.20.0-23-g6c633a8dd on 2024-04-11'`

**Comment by AlmazKad** [comment]
Oh, thanks, didn't notice this page, my bad

**Comment by laurensvalk** [comment]
Thanks @AlmazKad for asking and @BertLindeman  for answering! I'll close this issue.
