### ISSUE TITLE
[Feature request] add 'turn off' and 'reconnect to last hub' buttons...

### ISSUE THREAD

**Issue by biasedlogic** [pybricks/support#1830]
I'd love to see two buttons added to the web IDE.
1) 'turn the hub off'. While turning the hub on is very easy (just click the button) it takes a loooong press to turn it off and you have to get physically to the hub. So more often than not I fire REPL up and execute TechnicHub().system.shutdown() instead. I'd love to just have an IDE button that'd do just that. Shut the hub remotely down.

2) Reconnect to last. When coding using Technic Hub AND Xbox remote each time you want to change something in the code you have to reconnect. I have a raise SystemExit bound to one controller button, so that I can kick it back remotely into standby and ready for connection, but it takes several clicks to get the IDE connected again. It'd be great if there was a 'reconnect' button that'd just try the last BT MAC address instead of opening the pairing dialogue.

Thanks in advance for consideration!

**Comment by laurensvalk** [comment]
The shorter time out has been implemented. The suggestion for turning off the hub is moved to https://github.com/pybricks/support/issues/1708. Closing this issue. Thanks!
