### ISSUE TITLE
ev3 hi-technic color sensor with pybricks

### ISSUE THREAD

**Issue by chamathkk** [pybricks/support#197]
I am trying to use Hi-technic color sensor with pybricks. is there a module/class I can call with pybricks available currently ?.

**Comment by laurensvalk** [comment]
Yes, you can use the [Ev3devSensor](https://pybricks.github.io/ev3-micropython/iodevices.html#pybricks.iodevices.Ev3devSensor) class.

**Comment by chamathkk** [comment]
Thanks very much for the help. Your suggestion worked perfectly.
