### ISSUE TITLE
[Feature] Support for new 2024 Hub

### ISSUE THREAD

**Issue by rzagelow** [pybricks/support#1986]
**Is your feature request related to a problem? Please describe.**

Would like to program all 3 motors and 6 LEDs in this new hub released in 2024:

https://www.bricklink.com/v2/catalog/catalogitem.page?P=103479c01#T=C&C=86

**Comment by dlech** [comment]
This hub requires cryptographically signed firmware, so unfortunately we won't be able to make 3rd-party firmware for it.
