### ISSUE TITLE
[Bug] Close resolved SyntaxError notifications

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#201]
**Describe the bug**
When a SyntaxError is raised, the notification stays around even after you fix the syntax error.

**To reproduce**
1. Go to Pybricks Code
2. Write a program with a syntax erorr and click run
3. Fix the error and click run again
4. Notification stays around

**Expected behavior**
Old syntax errors should go away when you click run.

**Screenshots**
![image](https://user-images.githubusercontent.com/12326241/103753536-70aa3f80-500b-11eb-8535-0bffd602243a.png)

**Comment by dlech** [comment]
This should be fixed now.

**Comment by BertLindeman** [comment]
Can confirm this is fixed.

I wanted to show the related web version, but the `about box` does not state that precise enough, I think:

![image](https://user-images.githubusercontent.com/8142081/105579898-96647200-5d89-11eb-8e57-faead0f36783.png)

**Comment by dlech** [comment]
The web app has been unversioned up to this point. So the fact that it shows a version at all says that you did in fact get the update.
