### ISSUE TITLE
[Bug] Short Press did not boot stock firmware

### ISSUE THREAD

**Issue by HeyLlama** [pybricks/support#208]
I have "successfully" flashed ('primehub', '3.0.0a13', 'v3.0.0a13-1-g2aa1cfef on 2021-01-08') into my inventor hub. At least the Mindstorms app was saying it was successful.

It did reboot right after flashing but it was booting up pybricks instead of standard firmware as stated in #167 . Tested https://code.pybricks.com/ on Chrome, that works.

I tried both short press and long press. It was all pybricks for some reason. I'm not sure how to access standard firmware to charge the battery...Please help : (

**Comment by HeyLlama** [comment]
https://github.com/pybricks/pybricksdev/blob/master/README_dfu.rst
This saved me. Thank you 🙏

**Comment by laurensvalk** [comment]
Thanks for sharing this.

What happened when you tried a short press (~half a second)? Did Pybricks come on straight away? Or did nothing happen at all?

If you ever feel like trying this again, it would be great to know what happens if you power on by plugging in USB, instead of pressing any buttons. The expected result is the same as a short press, so stock firmware.

For your information, we intend to implement the DFU recovery step in our online app so users won't have to install anything. That's why the Prime Hub / Inventor Hub is not in beta just yet for now.

**Comment by HeyLlama** [comment]
I'll try again tonight now I know how to restore the stock OS :)

Half a second short press didn't boot up anything. Nor does plugging in USB.

One red flag was after flashing Pybricks, my hub rebooted Pybricks instead of stock firmware. I'll let you know if I could reproduce this behaviour.

Cheers

**Comment by laurensvalk** [comment]
I can confirm this. Thanks a lot for highlighting this issue.

**Comment by laurensvalk** [comment]
I think we will update that installation guide with a link to a fixed version that is known to work, instead of the latest build, just in case.

I'm rolling back a few changes to make one that works.

**Comment by HeyLlama** [comment]
Thank you!

**Comment by laurensvalk** [comment]
Can you try it with [this builld](https://github.com/pybricks/pybricks-micropython/suites/1808538282/artifacts/34734192)?

That would be super helpful - thanks!

**Comment by laurensvalk** [comment]
In the top comment you should see the version. Just to make sure, you need
```python
# Version: v3.0.0a13-7-g97e3745a
```

**Comment by HeyLlama** [comment]
Will do! I'll let you know

Cheers

**Comment by HeyLlama** [comment]
Unfortunately, the build you provided did not work either. Same behaviour, no reboot at all this time after the bluetooth light blinked pink-green-blue. No reaction from plugging in USB cable nor short press. Long press does boot Pybricks tho. I'm starting to suspect if this has anything to do with the newest firmware update from MINDSTORMS. Perhaps they changed the bootloader?

**Comment by HeyLlama** [comment]
![image](https://user-images.githubusercontent.com/19368776/104241875-48b44500-542c-11eb-891f-96289be44034.png)
This was the console output from the app.

**Comment by laurensvalk** [comment]
Thanks for looking into this. This is interesting.

Good reason to expedite the work on the easy installer and recovery from within our online app 😄

**Comment by HeyLlama** [comment]
Can't wait for the beta release! Thank you for the hard work 😄

**Comment by HeyLlama** [comment]
![image](https://user-images.githubusercontent.com/19368776/104244443-65eb1280-5430-11eb-9534-955ab9699b05.png)
I ran the download program again and this showed up in the console. Looks like there was an error before the installation program.

**Comment by laurensvalk** [comment]
This is the expected output for the download program. It’s a lot of data that doesn’t do anything by itself.

The installer then reads it as a text file. Line by line instead of all at once to avoid that memory error.

**Comment by HeyLlama** [comment]
Gotcha. Thank you!

**Comment by laurensvalk** [comment]
To get a taste of the easier recovery, check out [this page](https://github.com/devanlai/webdfu).

For vendor ID, choose `0x0694`. After connecting, choose this from the given options:

![image](https://user-images.githubusercontent.com/12326241/104294859-063c4800-54c0-11eb-856a-5293526f1869.png)

You can use the default for everything else.

The only caveat is that some sort of USB driver must already be installed or access to the USB device must be given. For Windows [this one](https://zadig.akeo.ie/) works.

**Comment by danielgaertner** [comment]
Hello, my name is Daniel. I am a beginner and I flash the pybricks firmware on my lego inventor hub with the original lego software for use in Linux. The dual boot dosn't work any more with the new firmware from pybricks. Can you tell me easy and exact steps to flash a new firmware on the inventor hub with dual boot, or restore the original lego firmware. Thank you!

**Comment by laurensvalk** [comment]
Thanks Daniel. Yes, we’ll give you step by step instructions. Specifically which OS do you have?

I’m also going to temporarily close the beta on the dual boot, until we document the restore step a bit better. Thank you both for highlighting this.

**Comment by HeyLlama** [comment]
> Hello, my name is Daniel. I am a beginner and I flash the pybricks firmware on my lego inventor hub with the original lego software for use in Linux. The dual boot dosn't work any more with the new firmware from pybricks. Can you tell me easy and exact steps to flash a new firmware on the inventor hub with dual boot, or restore the original lego firmware. Thank you!

Hi Daniel, I'm running MacOS so if you have other unix based system this method should work too.

Follow the steps to install pybricksdev
https://github.com/pybricks/pybricksdev

Make sure poetry and pyenv are installed. And you'd need dfu-util too. I’d recommend homebrew for installing these packages: https://brew.sh/

Pick a newer firmware (1.0ish) from the firmware folder and download (.bin), rename to a simpler name if you will
https://github.com/gpdaniels/spike-prime

This shows you how to get into DFU mode
https://github.com/gpdaniels/spike-prime/blob/master/firmware/README.md

To check if your hub is connected, use this command:
sudo dfu-util --list

Finally, to restore the stock firmware:
https://github.com/pybricks/pybricksdev/blob/master/README_dfu.rst

Remark: remember to cd into pybricksdev before calling the restore command

**Comment by laurensvalk** [comment]
Thanks for helping out @HeyLlama --- much appreciated.

If you want to try it, I'm curious to hear if the web page above works on Mac. I've confirmed it on Windows and Linux. And it seems a bit easier than installing `pybricksdev` for most people.

**Comment by laurensvalk** [comment]
Daniel, feel free to ask if you need any additional help.

**Comment by HeyLlama** [comment]
Hmm...I can't seem to find 0x0694 in the Vendor ID list on MacOS. Hub was indeed in DFU mode since I see it in the dfu-util --list
OS version is Catalina 10.15.7
Chrome version 87.0.4280.141

**Comment by laurensvalk** [comment]
You can just type it in. The listed devices (dapboot, mbed) are only (apparently frequently used) suggestions.

**Comment by danielgaertner** [comment]
Yes I need more help! I tried to install poetry and a runtime error appares!
daniel@PC-Stift:~$ poetry install

  RuntimeError

  Poetry could not find a pyproject.toml file in /home/daniel or its parents

  at .local/lib/python3.8/site-packages/poetry/core/factory.py:367 in locate
      363│             if poetry_file.exists():
      364│                 return poetry_file
      365│ 
      366│         else:
    → 367│             raise RuntimeError(
      368│                 "Poetry could not find a pyproject.toml file in {} or its parents".format(
      369│                     cwd
      370│                 )
      371│             )

**Comment by danielgaertner** [comment]
Poetry is now installed correctly! The error above is when I type
poetry run pybricksdev udev | sudo tee /etc/udev/rules.d/99-pybricksdev.rules

**Comment by laurensvalk** [comment]
> Poetry could not find a pyproject.toml file in /home/daniel or its parents

Did you download (or clone) pybricksdev? You need to be in that folder before calling `poetry install`. Then it can find the required files.

**Comment by HeyLlama** [comment]
Hey Daniel! Try this one instead: https://devanlai.github.io/webdfu/dfu-util/ You'd just need the .bin firmware for this one.
Much easier. Thank you! @laurensvalk 
![image](https://user-images.githubusercontent.com/19368776/104374745-5501d600-54f0-11eb-803f-6e2609478617.png)
![image](https://user-images.githubusercontent.com/19368776/104374756-58955d00-54f0-11eb-8c9a-eff7f194aa2c.png)

**Comment by laurensvalk** [comment]
I guess that confirms it works on Mac too :smile: Thanks!

**Comment by danielgaertner** [comment]
whitch vendor id can I use!

**Comment by HeyLlama** [comment]
> whitch vendor id can I use!

Type in 0x0694 and select the Lego option
PS make sure your hub is in DFU mode

**Comment by laurensvalk** [comment]
Daniel, check out [this post above](https://github.com/pybricks/support/issues/208#issuecomment-758524669) which has some screenshots for guidance.

**Comment by danielgaertner** [comment]
I shows SecurityError: Access denied.

**Comment by laurensvalk** [comment]
At which step does it show that?

**Comment by danielgaertner** [comment]
After I tried to connect!

**Comment by laurensvalk** [comment]
Would you like to move over to this discussion forum [here](https://gitter.im/pybricks/community)?

**Comment by laurensvalk** [comment]
@HeyLlama, I think I was able to reproduce it. It was due to two distinct issues so it took a while to find it. I would be greatful if you want to test [this build](https://github.com/pybricks/pybricks-micropython/suites/1836443916/artifacts/35500786). (v3.0.0a13-5-g9a80bef6).

**Comment by HeyLlama** [comment]
> @HeyLlama, I think I was able to reproduce it. It was due to two distinct issues so it took a while to find it. I would be greatful if you want to test [this build](https://github.com/pybricks/pybricks-micropython/suites/1836443916/artifacts/35500786). (v3.0.0a13-5-g9a80bef6).

Excellent! I'll let you know :D

**Comment by HeyLlama** [comment]
v3.0.0a13-5-g9a80bef6 works! Thank you so much!!

**Comment by laurensvalk** [comment]
Yes! :rocket: Thanks for the help.

I've updated #167 to use this version instead of the latest build, just to be safe. Latest builds are only for those who know how to use recovery mode, which now includes you :wink:

**Comment by laurensvalk** [comment]
@HeyLlama, @danielgaertner: https://beta.pybricks.com/dfu/

**Comment by HeyLlama** [comment]
> @HeyLlama, @danielgaertner: https://beta.pybricks.com/dfu/

Can confirm it works :D

**Comment by laurensvalk** [comment]
The firmware zip file also contains the .bin file for Pybricks, by the way. That will give you the regular boot instead of dual boot.

**Comment by danielgaertner** [comment]
I installed build # 838! No dual boot possible! Only Pybricks! In future I will use a older build!

**Comment by danielgaertner** [comment]
I tried to restore the original lego firmware with

 "poetry run pybricksdev dfu restore ~/Downloads/96112deb24a934bfc19a13c7ea620f54.bin" 

and the error 
"dfu-util: Invalid DFU suffix signature
dfu-util: A valid DFU suffix will be required in a future dfu-util release!!!
dfu-util: No DFU capable USB device available" 

appiers!

**Comment by danielgaertner** [comment]
Now it works! I have not put the hub in DFU Mode!

**Comment by laurensvalk** [comment]
You can also restore the original firmware with that website. It's just a convenient alternative to `pybricksdev`.

Thanks for sharing that it is working for you.
