### ISSUE TITLE
[Bug] Code completion for "try:" snippets have a syntax error 

### ISSUE THREAD

**Issue by BertLindeman** [pybricks/support#213]
**Describe the bug**
Code completion snippets for `try:` are refused 

**To reproduce**
1. go to `code.pybricks.com`
2. in the source area type the word `try`
3. choose a completion snippet, see the first screenshot
4. run the code
5. See the syntax error (second screenshot)

**Expected behavior**
Correct syntax, e.g. like the third screenshot

the snippet has 
```
except Exception, e:
```

and should be:
```
except Exception as e:
```

**Screenshots**
![image](https://user-images.githubusercontent.com/8142081/104708153-9aefb180-571d-11eb-9933-c95f0d653708.png)

![image](https://user-images.githubusercontent.com/8142081/104708417-f91c9480-571d-11eb-8b04-3024da2a93aa.png)

![image](https://user-images.githubusercontent.com/8142081/104708705-53b5f080-571e-11eb-9cd5-654ac0a955d5.png)

**Comment by dlech** [comment]
The error message in the screenshot looks like a server configuration error on our side.

**Comment by dlech** [comment]
@BertLindeman would you like to make a pull request to fix this? 

Click on the edit button in https://github.com/pybricks/pybricks-code/blob/master/src/components/editor-snippets.ts

**Comment by BertLindeman** [comment]
Will try ;-)

**Comment by BertLindeman** [comment]
I do not completely understand the file, but it's not so difficult to change a comma into `as`
PR #243 made.

**Comment by dlech** [comment]
I had no doubts that you could handle it. :wink:

**Comment by BertLindeman** [comment]
Got a neat message on code.pybricks.com:
```
New content is available and will be used when all tabs for this page are closed.'
```

Did ctrl-F5 to reload.
Used all `try` variants and no more syntax errors.
Closing . . .
