### ISSUE TITLE
[Bug] Inventor hub does not boot in original os

### ISSUE THREAD

**Issue by StephanP1979** [pybricks/support#214]
I flashed an version of the pybricks firmware (~6th Jan 2021) on my inventor hub. Since then, the hub does not charge and or boot in lego os.  With an earlier version everthing was fine.
I now read that there is already a bugfix, but how can I remove the current (not running) version of the firmware without being able to boot the lego firmware?

**Comment by dlech** [comment]
Please see the discussion in https://github.com/pybricks/support/issues/208 and let us know if you run into any problems.

**Comment by laurensvalk** [comment]
There's no need to read all of #208; the bug has been found and fixed.

In principle, you just need to follow the steps on [this page](https://beta.pybricks.com/dfu/).

**Comment by StephanP1979** [comment]
Puh! Thank's a lot! First I couldn't connect, but after installing the Zadig tool, i could. => Maybe you should add a hint to your instructions on https://beta.pybricks.com/dfu/ ...?

**Comment by laurensvalk** [comment]
It's already there, was working on it as we speak :rocket: . May need to refresh the page :)

**Comment by laurensvalk** [comment]
Glad to hear you got your hub back :)
