### ISSUE TITLE
[Bug]  Not all ports on Primehub see sensor or motor devices

### ISSUE THREAD

**Issue by BertLindeman** [pybricks/support#219]
**Describe the bug**
(As an example) The SPike Color sensor is not recognized/initiated on all Primehub ports similar on inventorhub 

**To reproduce**
1. Go to code.pybricks.com and connect the primehub
at version ('primehub', '3.0.0a13', 'v3.0.0a13-5-g9a80bef6 on 2021-01-15')
2. Insert the color sensor into a port and wait 5 seconds to allow the hub to recognize the sensor
3. See if the lights on the sensor light up
4. If not lit ifs obviously not recognized
5. Run the program (see below) and see if the sensor is reported

**Expected behavior**
The sensor should be reported on each of the ports
Did the same test with a Control+ motor with similar result.

**Condensed result Color sensor:**
| port | Primehub | Inventorhub |
| ---- | -------- | ----------- | 
| A | OK | OK |
| B | not lit | not lit |
| C | OK | not lit |
| D | lit but not reported | not lit |
| E | OK | not lit |
| F | not lit | not lit |

**Screenshots**

**Spike app**

![image](https://user-images.githubusercontent.com/8142081/105026189-92191b80-5a4e-11eb-9201-a7298f3b037e.png)

**Mindstorms app**

![image](https://user-images.githubusercontent.com/8142081/105026380-bf65c980-5a4e-11eb-9e6e-9f25c10baf8e.png)

**source**
``` python
#!/usr/bin/env pybricks-micropython

# source at Z:\home\bert\py\pybricks\debug_invertorhub\debug_controlPLUSmotor.py

from pybricks.tools import wait

from pybricks.iodevices import PUPDevice

try:
    # from pybricks.pupdevices import ColorDistanceSensor
    from pybricks.pupdevices import Motor
    # from pybricks.pupdevices import ColorSensor
    # from pybricks.pupdevices import UltrasonicSensor
    # from pybricks.pupdevices import ForceSensor
except Wxcept as e:  # NOQA:  E722 do not use bare 'except'
    print("could not import all pupdevices", e)

from pybricks.parameters import Port
# from pybricks.tools import wait

# create dictionary from device.info()['id'] =-> description
__devID = {}

__devID[46] = "Technic Control+ Large Motor "
__devID[47] = "Technic Control+ XL Motor    "
__devID[48] = "SPIKE Prime Medium Motor     "
__devID[49] = "SPIKE Prime Large Motor      "
__devID[61] = "SPIKE Prime Color Sensor     "
__devID[62] = "SPIKE Prime Ultrasonic/Distance Sensor"
__devID[63] = "SPIKE Prime Force Sensor     "



def who_am_i(xport):  # noqa C901 'who_am_i' is too complex (24)
    #  try to initialize generic device:
    try:
        # print("try Port:", xport)
        device = PUPDevice(xport)
    except OSError as e:
        print("40 OSError on:", xport, ":", e)
        return
    except ValueError as e:
        print("43 ValueError Exception", e, "occurred on", xport)
        return
    except Exception as e:
        print("46 General Exception", e, "occurred on", xport)
        return
    else:
        try:
            print("%-7s device.info()['id']=%2d " % (xport, device.info()['id']), end="")
        except ValueError as e:
            print("52 ValueError Exception ", e, "occurred on", xport)
            return
        except Exception as e:
            print("55 General Exception", e, "occurred on", xport)
            return
        try:
            print(__devID[device.info()['id']], end="")
        except Exception as e:
		    pass
            # print("60 General Exception ", e, "occurred on port: ", xport)
            # return
	print()


who_am_i(Port.A)
who_am_i(Port.B)
who_am_i(Port.C)
who_am_i(Port.D)
who_am_i(Port.E)
who_am_i(Port.F)

```

[EDIT] added version

**Comment by laurensvalk** [comment]
Confirmed, thanks for reporting. This started breaking only recently.

**Comment by BertLindeman** [comment]
Thanks.

Seems like not all ports react the same each time.

**Comment by laurensvalk** [comment]
This was broken by https://github.com/pybricks/pybricks-micropython/commit/01f1e17d8e1136bbc4d525758a3d90ca71d2d20a

**Comment by laurensvalk** [comment]
The attempted fix is being built now and should be ready in a  few minutes:

https://github.com/pybricks/pybricks-micropython/runs/1727770616

**Comment by laurensvalk** [comment]
https://github.com/pybricks/pybricks-micropython/suites/1856856559/artifacts/36056567 :tada:

**Comment by BertLindeman** [comment]
> The attempted fix is being built now and should be ready in a few minutes:
> 
> https://github.com/pybricks/pybricks-micropython/runs/1727770616

Installed firmware from here (click artifacts etc..) Is the firmware on:
```
 https://github.com/pybricks/pybricks-micropython/suites/1856856559/artifacts/36056567 🎉
```
different?

Did a visual test on the primehub by inserting the Spike color sensor and later the colorDistance sensor in each port.
All lit up nicely.

If the two links point to the same firmware, this issue can be closed.

Blazing fast ;-)

**Comment by laurensvalk** [comment]
They were the same. 

> All lit up nicely.

Excellent. Thanks for reporting and testing so quickly, I appreciate it. I will update the link in the installation support issue with this new version.

**Comment by BertLindeman** [comment]
Great!
Just confirmed that the zips via both links are identical.
