### ISSUE TITLE
Writing in a pre-existing file

### ISSUE THREAD

**Issue by DLunomos** [pybricks/support#22]
I'm currently doing a project that involves calibrating a older color sensor that doesn't have support for it. I'm planning to store the raw data in a csv file. Pybricks does support data logging, but you must create a new file every time the program runs. If you could give the log or DataLog class an argument that states if it's writing in a pre-existing file, it would be a lot simpler to store larger amounts of data.

**Comment by dlech** [comment]
Do you mean that you would like to append additional data to existing data already in the file without overwriting the existing data?

**Comment by DLunomos** [comment]
Yes, that's what I intended.

**Comment by laurensvalk** [comment]
Thanks @DLunomos  for your suggestion. I've added experimental support for it earlier this morning, which might make it into the next release.

**Comment by laurensvalk** [comment]
Support added in https://github.com/pybricks/pybricks-micropython/commit/8097a97ff70d99e3b0e356aebd2e6b624b7c60f5

This will be included in the next release in a week or so.

There is now an extra keyword argument `append` when you create the `DataLog`. It is `False` by default so existing code is unaffected.

I'll keep this issue open until it's documented as well.

**Comment by laurensvalk** [comment]
Documentation added in https://github.com/pybricks/pybricks-api/commit/9ff69a54fb404c54c4576a9264780b7fdbf5cd5f.

Thank you @DLunomos!
