### ISSUE TITLE
[Bug] Link in code.pybricks Documentation frame is refused on Microsoft EDGE browser

### ISSUE THREAD

**Issue by BertLindeman** [pybricks/support#229]
**Describe the bug**
In MS EDGE a link in the Documentation frame is attempted to be loaded into this Documentation frame.
MS EDGE browser refuses this. (See the screenshots below). 
. A copy of that link opens fine in a new MS EDGE tab.
. On Google Chrome the link is automatically opened in a new tab, and no problem occurs.

**To reproduce**
1. On win10 open MS EDGE
2. Go to 'code.pybricks.com'
2. Click on 'Settings'
3. Enable `Documentation`
4. Close "Settings'
5. Scroll down to the bottom of the help text
6. Click on `support page` in 
```Got questions or issues? Please share your findings on our support page so we can make Pybricks even better.```
7. See the error (like in the screenshots)

**Expected behavior**
Only open Pybricks documentation web pages in the documentation frame. For all other pages I would expect a new tab to be opened.

**Environment**
Win10
MS EDGE Versie 87.0.664.75 (Officiële build) (64-bits)
Google Chrome Version 87.0.4280.141 (Official Build) (64-bit)

**Circumvention**
Copy the link you want to click and paste that link into a new tab.
Or use Google Chrome

**Screenshots**
![image](https://user-images.githubusercontent.com/8142081/105626682-9ddf5600-5e31-11eb-883f-30a430c4f24f.png)

![image](https://user-images.githubusercontent.com/8142081/105626076-f0b70e80-5e2d-11eb-8964-46d04f1ecd36.png)

![image](https://user-images.githubusercontent.com/8142081/105626020-ae8dcd00-5e2d-11eb-9f10-cef0be6de0f2.png)

![image](https://user-images.githubusercontent.com/8142081/105626063-d9782100-5e2d-11eb-8f3c-63de732b89e3.png)

**Comment by dlech** [comment]
Related: https://github.com/pybricks/pybricks-api/issues/21

**Comment by BertLindeman** [comment]
> 
> 
> Related: [pybricks/pybricks-api#21](https://github.com/pybricks/pybricks-api/issues/21)

Ah, Laurens already found it, but that issue has been closed, but not fixed yet.
So I did not research enough, sorry.
Is there another item that is planned to fix this (that I obviously missed) 
If so, then this issue can also be closed.

**Comment by BertLindeman** [comment]
Since 2021-01-26 this error situation no longer occurs.

Could it be that [include offline copy of docs #273](https://github.com/pybricks/pybricks-code/pull/273)
produces a different link, thus loading in a new tab?

Enough guessing, closing . . . .

**Comment by laurensvalk** [comment]
@BertLindeman, Thanks for verifying. See https://github.com/pybricks/pybricks-api/commit/adf6e03bc94d34723fb43f05df14cb2219640128

**Comment by BertLindeman** [comment]
Thanks for the link, Laurens. 
Guessing now is over ;-) 

Tested the links in the settings panel 
and the support link on the first page of the doc panel.
