### ISSUE TITLE
Using the buttons

### ISSUE THREAD

**Issue by ZPhilo** [pybricks/support#233]
**Describe the issue**
On prime/inventor hub, Button.CENTER is listed, but pressing it aborts the program

**Suggested improvement**
Link to a program snippet that allows usage of Button.CENTER in custom user interface.

**Comment by dlech** [comment]
On Prime/Inventor hubs, the center button is treated the same as the green button on other hubs. So if you really want to use it, you can catch the `KeyboardInterrupt` to use the button for input, but you have to be careful to make sure there is still a way to stop your program.

We can make an example, but we don't really want to widely encourage using it.

**Comment by ZPhilo** [comment]
Makes sense... still think that something needs to be done to clarify this in Button documentation.

**Comment by laurensvalk** [comment]
We could enable something like this. What do you think @ZPhilo?

```python

hub = PrimeHub()

hub.buttons.set_keyboard_interrupt(False)

# Now you can read the Button.CENTER too like the others!

# But of course now you have to take care of stopping yourself, or use a long press to shut down entirely.

hub.buttons.set_keyboard_interrupt(True)

# Now it works as usual again.

```

Until now, we had something more complicated in mind (e.g. a double click) that stopped us from doing it so far, but this would be quite simple.

For now, this would mean that the stop button in Pybricks Code would not work either, but we're fixing that in other ways.

**Comment by dlech** [comment]
On the one hand, I would rather not add anything to keep things super simple. On the other hand, it would be cool if it took a button (or `None`) as the argument, then you could use the Bluetooth button as a stop button instead if you wanted to.

**Comment by ZPhilo** [comment]
The simple scheme as proposed by Laurens seems fine to me. I was indeed a bit worried by the potential problem of lack of stop, but if a long press allows to take back control anyway, it's fine!

**Comment by laurensvalk** [comment]
We could put this functionality in ‘’pybricks.tools.enable_keyboard_interrupt()’’ to keep the button interface simple.

Or better yet, check which micropython module already has this function and enable that.

**Comment by laurensvalk** [comment]
> Or better yet, check which micropython module already has this function and enable that.

Guess what, it is already enabled :smile: 

```python
from pybricks.tools import wait

from micropython import kbd_intr

kbd_intr(-1)

print("Can't cancel program in the next 5 seconds!")
wait(5000)

print("Now you can stop again")
kbd_intr(3)
wait(5000)

```

So we just need to make sure we return `Button.CENTER` as well.

**Comment by laurensvalk** [comment]
@ZPhilo: I know you like the online GitHub interface, so if you want to, you can add `&pb_Button_CENTER_obj` [here](https://github.com/pybricks/pybricks-micropython/blob/bf3072b6f7dd87b60e50d7c2130ca3c393a5709f/pybricks/hubs/pb_type_primehub.c#L34).

![Screenshot from 2021-01-26 21-14-27](https://user-images.githubusercontent.com/12326241/105899878-8f549280-601b-11eb-8cfc-4b0d3f2e4326.png)

**Comment by laurensvalk** [comment]
@JanderII is probably interested in this as well. Would this suit your application?

**Comment by ZPhilo** [comment]
> @ZPhilo: I know you like the online GitHub interface, so if you want to, you can add `&pb_Button_CENTER_obj` [here](https://github.com/pybricks/pybricks-micropython/blob/master/pybricks/hubs/pb_type_primehub.c#L35).

Done!
BTW, I just noticed an error in buttons program snippet: it uses Button.BT instead of Button.BLUETOOTH

**Comment by laurensvalk** [comment]
Thank you! I think now you just need to go to [your branch](https://github.com/ZPhilo/pybricks-micropython/tree/patch-1) and click on the pull request button.

**Comment by laurensvalk** [comment]
> BTW, I just noticed an error in buttons program snippet: it uses Button.BT instead of Button.BLUETOOTH

You're right, thanks! It would be great if you want to [to change that also!](https://github.com/pybricks/pybricks-api/blob/master/examples/pup/hub_primehub/button_main.py)

**Comment by ZPhilo** [comment]
Done for both (hopefully right ;) )

**Comment by laurensvalk** [comment]
This has been added so we can close it. Thanks @ZPhilo!
