### ISSUE TITLE
pybricks-code does not auto update

### ISSUE THREAD

**Issue by xserk** [pybricks/support#235]
**Question**
Why do I get an error when trying to call hub.imu.angular_velocity() ?

**Context**
I'm trying to run a code found in the documentation using a technic hub but I get the error AttributeError: 'IMU' object has no attribute 'angular_velocity' 

Thank you

**Screenshots**
![image](https://user-images.githubusercontent.com/77755010/106137872-0735d080-6174-11eb-8609-f3a9097677ae.png)

![image](https://user-images.githubusercontent.com/77755010/106137860-fdac6880-6173-11eb-8e8c-e1d2722b00f3.png)

**Comment by laurensvalk** [comment]
Which version are you running?

To find out, run:

```python

from pybricks import version
print(version)

```

You may need to update your firmware because these methods were added only recently.

**Comment by xserk** [comment]
('technichub', '3.0.0a13', 'v3.0.0a13 on 2021-01-08')

**Comment by laurensvalk** [comment]
Yeah, try updating the firmware in that case. :)

**Comment by xserk** [comment]
I loaded the firmware via the button you have on the test page, should i drag and drop latest firmware there? Will I be able to push the play button to load the code after that? Thank you.

**Comment by laurensvalk** [comment]
Hmm, the button should give you the latest.

I wonder if you might be running an older version of our app.

Can you try doing a hard refresh using `ctrl+F5`?

**Comment by laurensvalk** [comment]
If you go to settings, and click `about`, you should see this version:

![image](https://user-images.githubusercontent.com/12326241/106139324-9390c500-616d-11eb-82b0-33b82bb6e137.png)

**Comment by xserk** [comment]
That was it! Chrome had a cached version of the page. Thank you!

**Comment by laurensvalk** [comment]
Cool!

> Will I be able to push the play button to load the code after that? Thank you.

With this option, you can:

![image](https://user-images.githubusercontent.com/12326241/106139580-e9656d00-616d-11eb-85db-1c7307f32107.png)

**Comment by dlech** [comment]
The app now has a *Check for Update* in case automatic updates are missed.
