### ISSUE TITLE
[Feature] Uninstall button for Pybricks Code

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#240]
**Is your feature request related to a problem? Please describe.**
Installing is easy now, but removing is a bit harder. 

**Describe the solution you'd like**

If installed, replace install by uninstall button.

![image](https://user-images.githubusercontent.com/12326241/106266544-d95e9380-6228-11eb-8782-f74ea239adb3.png)

**Describe alternatives you've considered**
Finding out where the uninstall button is in Chrome. We could add an explainer, but an uninstall button where the install button was, seems more intuitive.

**Comment by dlech** [comment]
I'm not aware of any APIs that will uninstall the app, so the best we can do is document where to find it in the Chromium UI.

**Comment by dlech** [comment]
We also have to consider that it won't be the same on Android vs Desktop.

**Comment by laurensvalk** [comment]
>  the best we can do is document where to find it in the Chromium UI.

This is done [here](https://pybricks.com/install/running-programs/#using-pybricks-offline), so we can close this
