### ISSUE TITLE
[Bug] ctrl-d binds to repl and cannot be used show/hide documentation

### ISSUE THREAD

**Issue by ws1088** [pybricks/support#246]
**Describe the bug**
ctrl-d binds to repl and cannot be used show/hide documentation

**To reproduce**
1. start IDE
2. press ctrl-d to show/hide documentation
3. press '>>>' to show repl
4. repeat step 2

**Expected behavior**
a shortcut key which will show/hide documentation no matter if repl is active or not

**Comment by dlech** [comment]
Make sure the text editor is focused and not the terminal. In the terminal, Ctrl-D is sent to the hub (the same applies to Ctrl-A, Ctrl-C, etc.).

**Comment by dlech** [comment]
Closing as working as expected.
