### ISSUE TITLE
[Bug] download_pybricks to flash firmware onto Spike primehub fails: allocating 173 bytes

### ISSUE THREAD

**Issue by BertLindeman** [pybricks/support#250]
**Describe the bug**
On Spike app: Running download_pybricks from [build #873](https://github.com/pybricks/pybricks-micropython/suites/1955317186/artifacts/38734417) fails with:
```
Traceback:
  File "programrunner/___init___.py" line 1, in start__program
MemoryError: memory allocation failed, allocating 173 bytes.
```
Note the Spike app does not allow copy/paste so I typed this by hand/eye. So also screenshot below.

**To reproduce**
1. (on windows) open Spike App
2. Load download_pybricks from  [build #873](https://github.com/pybricks/pybricks-micropython/suites/1955317186/artifacts/38734417)
3. Connect the hub (I used Bluetooth)
4. Click the bit yellow "run" button and wait about two minutes
5. Open the console
6. See error (in the snapshot)

**Expected behavior**
The data to be loaded after ~ 2 minutes

**Screenshots**
![image](https://user-images.githubusercontent.com/8142081/106748750-f11d8980-6625-11eb-856e-e7899d7d4ff6.png)

**environment**
win 10
Spike app 1.3.3
New firmware from  [build #873](https://github.com/pybricks/pybricks-micropython/suites/1955317186/artifacts/38734417) 
Current LEGO firmware on Spike hub: Hub OS: 3.01
Hub has dual boot onboard.

**Comment by laurensvalk** [comment]
That's the intended behavior. 

This is the only way to get a large file onto the hub using the official app: sending a large file and letting it fail. And then use a separate program to parse its contents.

I think you can probably see now why we are working on a more user friendly install from inside Pybricks Code :wink:.
