### ISSUE TITLE
[Feature] Color.NONE vs. None

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#253]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/12326241/107560730-040ffb00-6bde-11eb-9164-bd522ad71600.png)

Right now, the return value can be `None` or of type `Color`. And `None` is treated as a special case by `detectable_colors`.

This can be confusing. It also breaks things like printing `measured_color.h` to see the hue.

**Describe the solution you'd like**
It might make more sense to just define `Color.NONE = Color(0, 0, 0)` explicitly. This also makes the difference with `Color.BLACK` easier to explain.

The only issue is backwards compatibility with the 2.0 release for EV3.

**Comment by dlech** [comment]
:+1:  from me

**Comment by laurensvalk** [comment]
Implementation done. Need to verify docs and examples.

**Comment by laurensvalk** [comment]
This is now done via https://github.com/pybricks/pybricks-api/commit/68f626f1ef5778ba981becb610d701454ddffb3e and surrounding commits.
