### ISSUE TITLE
problem connecting City Hub

### ISSUE THREAD

**Issue by xblanch** [pybricks/support#269]
Hi,
I'm trying to connect a Powered Up city hub.
Days ago, I flashed the hub.
Now, I can stablish connection. Otherwise, I have another city hub with Lego original firmware and I can't flash it.
When I try connect or flash, browser display this error:

```
GATT Server is disconnected. Cannot retrieve services. (Re)connect first with `device.gatt.connect`.
```

Sometimes, the error displayed is other:
```
Connection failed for unknown reason.
```

I'm using:
Windows 10 Home, build 19042.844
Google Chrome Version 89.0.4389.82 (64 bits)
Bluetooth: Qualcomm Atheros Bluetooth 4.0

I have tried connect with Microsoft Edge and Chrome Canary with same results.
Thanks.

**Comment by dlech** [comment]
Thanks for the additional info. I've just posted https://github.com/pybricks/support/discussions/270. Could you try the suggestions there?
