### ISSUE TITLE
[Bug] Empty page on Pybricks Code on Android

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#275]
**Describe the bug**
Pybricks Code gives an empty page on a new Android 10 Phone. This is the first time opening that page on this device.

It loads just fine on my previous Android phone and PC. It appears that the favicon does load, so something is getting through at least.

**To reproduce**
1. Buy and set up a new phone :smile: 
2. Go to code.pybricks.com
3. Get an empty page.

**Expected behavior**
Pybricks Code should load.

**Screenshots**
![Screenshot_20210319-155318](https://user-images.githubusercontent.com/12326241/111800941-be290f80-88cc-11eb-9f87-30e75a761087.png)

**Comment by dlech** [comment]
Did you update all of the apps first? I got a chromebook and it did the same thing because it was on Chrome 84 or something like that. You can also enable ADB and connect it to Chrome on your computer to look at the console log to see what is going on.

**Comment by laurensvalk** [comment]
Looks like that was it, thanks!
