### ISSUE TITLE
Script with multiple files

### ISSUE THREAD

**Issue by thesynman** [pybricks/support#288]
Hi,
How do I use pybricksdev to run a script that is split across multiple files? Sorry if that should be obvious but I'm new to python and I don't fully understand how module imports work!
Thanks

**Comment by dlech** [comment]
The currently supported Powered Up hubs don't have file systems (due to limited flash memory) and therefore can't support this. You could try concatenating the files into a single file. https://stackoverflow.com/questions/13613336/python-concatenate-text-files
