### ISSUE TITLE
[bug] pybricksdev BLE download not working on Windows

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#292]
> I can confirm that pybricks-code now seems to work ok, but it's hard to be sure because of #290.
> 
> Win 10 and Chrome Version 89.0.4389.114 (Official Build) (64-bit)
> 
> @laurensvalk I've pulled the latest from pybricksdev and still seeing the same sort of errors (with the latest firmware). I'm doing:
> `poetry run pybricksdev run ble "Pybricks Hub" "print('hi there')"`
> and the outcome is inconsistent. Either a) (rarely) seems to work but the program never exits, b) I see checksum errors but the program runs but doesn't exit, c) I see checksum errors and then `Error during program download`.

> In short, pybricksdev is still not working for me.

_Originally posted by @thesynman in https://github.com/pybricks/support/issues/287#issuecomment-814050413_

**Comment by dlech** [comment]
This should be fixed now. `pybricksdev` is also now published on pypi.
