### ISSUE TITLE
[Feature] Show the version of the firmware in the popup of the download button

### ISSUE THREAD

**Issue by BertLindeman** [pybricks/support#295]
**Is your feature request related to a problem? Please describe.**
Would be nice to see the version of the firmware before the actual download

**Describe the solution you'd like**
Show the version of the firmware in the popup of the download button

**Describe alternatives you've considered**
Download the firmware and run to see what version it has :smile:
Takes some time we want to avoid spending...

**Additional context**
![image](https://user-images.githubusercontent.com/8142081/113897412-20d64280-97cb-11eb-8d50-45c9f1265fb4.png)

**Additional thought**
Only if very easy to implement and automatically filled in after that.

**Comment by dlech** [comment]
Also see https://github.com/pybricks/support/issues/173#issuecomment-812752509

**Comment by BertLindeman** [comment]
Ah thanks David, my memory is not as it was.
I even commented on that 😞 

In that case ( #173 ) this feature is not needed.

Closing
