### ISSUE TITLE
[Feature] Improve default program output

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#298]
**Is your feature request related to a problem? Please describe.**

This is overly long and pollutes the limited space in the output window.

```

Running downloaded program...

...done.
```

I believe it was intended to clarify when programs start and end, but I don't see this being any more helpful than a simple separator:

![image](https://user-images.githubusercontent.com/12326241/114377729-46769980-9b87-11eb-897c-b1e6aa454cea.png)

**Describe the solution you'd like**

A simple separator should suffice `--------------------------------------`

**Fancier solution**

Instead of letting the firmware something, we could have Pybricks Code insert something like

`Program started  at 04-12-2020 12:08:144`
`Program stopped at 04-12-2020 12:13:134`

Or perhaps:

`Program started  at 04-12-2020 12:08:144`
`Program completed in 5.131 seconds`

**Comment by dlech** [comment]
> Instead of letting the firmware something, we could have Pybricks Code insert something

I agree this would be nice, but we currently have enough race condition problems with starting and stopping the program.

> A simple separator should suffice `--------------------------------------`

I think 3 dashes would be enough.

**Comment by laurensvalk** [comment]
Or none at all, assuming we can get the download and run buttons to work well enough.

**Comment by dlech** [comment]
> Or none at all,

doing this for now

**Comment by laurensvalk** [comment]
This looks good, so closing.
