### ISSUE TITLE
[Feature] Disable flashing while programming

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#299]
**Is your feature request related to a problem? Please describe.**
At the moment, you can click flash to install the firmware on hub 2, while already programming hub 1.

This even works (mostly). The disconnect buton doesn't work in this case though. Instead of making this edge case work, maybe we could disable the flash button while connected.

![image](https://user-images.githubusercontent.com/12326241/114386522-9f4b2f80-9b91-11eb-92bd-ff1daa068b42.png)

**Describe the solution you'd like**
Disable flash button if connected to a Pybricks Hub.

**Comment by dlech** [comment]
> Disable flash button if connected to a Pybricks Hub.

It was supposed to be this way in the first place. :wink:
