### ISSUE TITLE
[Bug] Deadlock when pressing start and pressing button simultaneously

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#301]
**Describe the bug**

Buttons remain grayed out after clicking the Technic Hub button and the Pybricks Code play button at the same time.

This happens 100% of times for me on Ubuntu 18.04 and on Android 11.

**To reproduce**
See program in screenshot below. Then press  Technic Hub button and the Pybricks Code play button at the same time.

**Expected behavior**
Either one of the programs to run successfully, or nothing at all; at least no deadlock.

It's a bit of an edge case, but it may help us uncover some of the other issues we are seeing.

**Screenshots**

It happens whichever you press first.

This happens usually when physical button is pressed first:

![image](https://user-images.githubusercontent.com/12326241/114413377-39b96c00-9bae-11eb-9d38-417cae6e2e1c.png)

The other way around, you can usually get to this state:
![image](https://user-images.githubusercontent.com/12326241/114413650-77b69000-9bae-11eb-96d0-a6a979eeb4a0.png)

**Comment by dlech** [comment]
Should be fixed in beta 13

**Comment by dlech** [comment]
There is still the edge case where pressing the hub button during download "cancels" the download and prints `ValueError: incompatible .mpy file` but the buttons don't get stuck anymore.

**Comment by laurensvalk** [comment]
> Should be fixed in beta 13

Confirmed.

> There is still the edge case where pressing the hub button during download "cancels" the download and prints ValueError: incompatible .mpy file but the buttons don't get stuck anymore.

Confirmed, and this sounds fine to me.
