### ISSUE TITLE
 [Bug] Deadlock when connecting to bootloader just too late

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#302]
**Describe the bug**

If you don't keep pressing the Technic Hub button long enough, connecting fails (as expected), but the button state remains locked.

Then after a while (30 sec?), you get an unexpected error:

**To reproduce**

- For convenience, erase the firmware first (e.g. make a failed download).
- This lets you activate the bootloader with a single click.
- Click flash button, select LEGO Bootloader
- Be just too late to press connect. The browser still lets you, despite the hub already being off.

**Expected behavior**
Failed install, but ability to try again without hard refresh

**Screenshots**
![image](https://user-images.githubusercontent.com/12326241/114511982-e0e2e580-9c38-11eb-9ac9-e015873c36bd.png)

**Comment by dlech** [comment]
Operating system?

**Comment by laurensvalk** [comment]
Verified on Ubuntu 18.04 and android, using technic hub.

**Comment by dlech** [comment]
In the screen shot, it looks like the button is enabled again after the error. So I think this is working as well as can be expected.

**Comment by laurensvalk** [comment]
Sounds good to me.
