### ISSUE TITLE
[Feature] Make tools/codeformat.py consistent with flake8

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#309]
**Is your feature request related to a problem? Please describe.**
`flake8` is not too happy with long lines, but `codeformat` makes them long anyway.

For example, `codeformat` turns

```python
    assert detected == Color[name], "Expected {0} but got {1}".format(
        Color[name], detected
    )

```
into

```python
    assert detected == Color[name], "Expected {0} but got {1}".format(Color[name], detected)
```
But this is too long.

**Describe the solution you'd like**
Reconfigure `codeformat` or `flake8` or both to make them consistent for `.py` files.

**Related**
https://github.com/pybricks/pybricks-micropython/pull/53

**Comment by dlech** [comment]
The `codeformat` script uses Black, which is not really configurable, so instead, we should configure Flake to not complain. 

https://black.readthedocs.io/en/stable/compatible_configs.html#flake8

Plus we need to take into account that `codeformat` script sets the line length to 99 (comes from upstream MicroPython). And black will still allow lines longer than that if it is just a string (it doesn't split strings). So we could just disable the line length check in Flake altogether and just let Black "do the right thing".
