### ISSUE TITLE
[Feature] Add busy state to bluetooth button while connecting

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#315]
**Is your feature request related to a problem? Please describe.**
After clicking connect in the connection dialog, it can take several seconds on some PC's before the start button becomes enabled.

**Describe the solution you'd like**
It would be nice to indicate the busy state, just as during firmware install initialization.

**Describe alternatives you've considered**
Buy @martynboogaarts a new laptop :smile:

**Comment by dlech** [comment]
The firmware update button also needs to be disabled during this time.

**Comment by martynboogaarts** [comment]
understand

PS new DELL on its way ...

Op vr 14 mei 2021 om 22:34 schreef David Lechner ***@***.***>:

**Comment by laurensvalk** [comment]
Don't throw the old one out, it seems especially good at finding issues in our app 😄

**Comment by dlech** [comment]
This is done in RC2.
