### ISSUE TITLE
[Question] Every time I try to burn the new 2.0 Disk Image to my microSD, I get an error

### ISSUE THREAD

**Issue by anttesoriero** [pybricks/support#32]
**Question**
When I use balenaEtcher to burn the new stable 2.0 release to my microSD, I get an error about the image. Do you know why this would be happening? I've used the same method for other updates before and it was always fine.

**Context**
Install the new stable 2.0 release on my microSD.

**Screenshots**
<img width="315" alt="Screen Shot 2020-05-27 at 2 51 46 PM" src="https://user-images.githubusercontent.com/43342253/83060839-13d4b880-a02a-11ea-83fc-3de697902302.png">

**Comment by dlech** [comment]
What is the URL you used to download the SD card image?

**Comment by anttesoriero** [comment]
https://pybricks.com/downloads/

**Comment by dlech** [comment]
Have you tried downloading it again?

**Comment by anttesoriero** [comment]
Yes, but I figured it out kind of. For some reason it's only an issue on balenaEtcher. When I tried another application, it worked. I'm using a Mac, so I used ApplePiBaker instead.

**Comment by dlech** [comment]
Which version of balenaEtcher?

**Comment by anttesoriero** [comment]
Version 1.5.56 (1.5.56)

**Comment by laurensvalk** [comment]
Is this still an issue, @anttesoriero?
