### ISSUE TITLE
Pybricks Code connects to but does not receive information from City hub on macOS 10.10

### ISSUE THREAD

**Issue by vanessahsw** [pybricks/support#327]
I am trying to connect city hub and the firmware seems to be installed properly. Afterwards, I connect the hub via bluebooth and got a consistent blue solid light. 

However, the run and stop program buttons were greyed out so I was unable to execute anything. Just hoping to get some guidance on how to proceed forward. 

Thanks.

**Comment by laurensvalk** [comment]
Thanks for reporting this. Which operating system and browser are you using?

**Comment by dlech** [comment]
We also have a [Bluetooth troubleshooting guide](https://github.com/pybricks/support/discussions/270).

**Comment by vanessahsw** [comment]
I am using Chrome - Version 87.0.4280.88 (Official Build) (x86_64) and Mac OS 10.10.5.

This is what I saw from the device log:
```
BluetoothEvent[22:32:29] BluetoothAPI: 0x7fe013d695b0
```

No error message was seen in the developer console.

**Comment by dlech** [comment]
I have a hunch that the problem could be because of the older macOS version. Chrome system requirements say 10.11 minimum.

I am able to connect and use a city hub using Chrome 90 and macOS 11.

**Comment by dlech** [comment]
> This is what I saw from the device log:
> 
> ```
> BluetoothEvent[22:32:29] BluetoothAPI: 0x7fe013d695b0
> ```

Did you set the log level to `Debug`?

**Comment by vanessahsw** [comment]
I tried on another mac with updated OS and it was able to run. I will close the issue. Thanks for your help!
