### ISSUE TITLE
[Feature] Improve warning text for no adapter found

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#338]
**Is your feature request related to a problem? Please describe.**
Sometimes, I forget to plug in the Bluetooth dongle and I get the expected error. But pluging it in does not resolve it. You have to restart the browser also. We could tell the user about this.

**Describe the solution you'd like**
Adjust the text to something like:

*No Bluetooth adapter could be found. Please insert a compatible adapter and restart the browser.*

![image](https://user-images.githubusercontent.com/12326241/118449427-6ef83300-b6f3-11eb-90a3-0b444da63044.png)

**Comment by dlech** [comment]
Should we also mention that it requires Bluetooth Low Energy?

**Comment by laurensvalk** [comment]
Yes. Or -- I don't remember -- did we already have a "more info" link option for these notification? Maybe we could add a page to the site and link to it.

**Comment by dlech** [comment]
It shouldn't be to hard to add a button. Just need the page first. :smile:

**Comment by dlech** [comment]
We should also file a bug with Chromium. Restarting the browser should not be necessary.

**Comment by dlech** [comment]
Looks like we did this already.
