### ISSUE TITLE
Warning message "No bluetooth" on connect pop-up overlays message about "no compatible device found"

### ISSUE THREAD

**Issue by BertLindeman** [pybricks/support#339]
**Describe the bug**
The two overlayed messages are illegible.
Seen this very minor bug on Windows and on Linux.

**To reproduce**
1. Go to `code.pybricks.com`
2. Switch off Bluetooth on your PC or whatever you use to connect to the hub
3. Click on the button `connect Bluetooth`
4. See the pop-up and try to read :wink:

**Expected behavior**
Either remove the message about "no compatible device" that is obvious if no Bluetooth is available,
or place the messages on their own line on the pop-up.

**Screenshots**
![image](https://user-images.githubusercontent.com/8142081/118460647-2d6c8580-b6fd-11eb-9b00-e68cdf41d2ff.png)

**Comment by laurensvalk** [comment]
I've seen this a few times too. This may be a bug in Chromium. 

Thanks for providing a reproducible case!

**Comment by BertLindeman** [comment]
Ah, an incomplete error report by me then :wink: 
On Windows seen on ```Microsoft Edge Versie 90.0.818.56 (Officiële build) (64-bits)```

**Comment by laurensvalk** [comment]
Both Google Chrome and Microsoft Edge are built on Chromium :wink:

**Comment by BertLindeman** [comment]
Indeed Laurens: on Win10 with ```Opera Versie:76.0.4017.107``` this scenario gets a red pop-up message:

![afbeelding](https://user-images.githubusercontent.com/8142081/118474592-8511ed80-b70b-11eb-9541-cb509fbaf6cb.png)

**Comment by dlech** [comment]
Here is a helpful link: https://www.chromium.org/developers/how-tos/file-web-bluetooth-bugs

Although in this case, I don't think any logs are necessary when filing the bug.

**Comment by dlech** [comment]
Is this still a bug in chromium?

**Comment by BertLindeman** [comment]
Tested (Now on WIN11) on beta.pybricks.com 
   with MSedge - no problem
   with chrome Version 102.0.5005.63 - also no problem.
