### ISSUE TITLE
Connecting to Pybricks BLE service hangs on macOS

### ISSUE THREAD

**Issue by Patlepirate01** [pybricks/support#34]
**Question**
The run button is never active after the bluetooth activation (and the bluetooth button is not active again but I don't know if it's normal or not) ==> not sure if the bluetooth connection is successfull or if another issue after

**Context**
I'm using a macbook air with Mac OS Sierra (10.13.6) and Chrome 80 (as requested). The flashing of the hub was successfull (when I press after the green button one motor is turning very shortly). Then I try to connect Bluetooth. Icon is changing on chrome (Tab associated with a bluetooth device) but the Run button is not active

**Screenshots**
![Capture d’écran 2020-06-07 à 09 52 26](https://user-images.githubusercontent.com/45802615/83963249-c9163480-a8a4-11ea-9046-6d324cedb753.png)

**Comment by Patlepirate01** [comment]
ANd I have also tested on my imac with Catalina (10.15.5) and Google 85 and I see the device well connected in the bluetooth list but still no ccess to the run button
![Capture d’écran 2020-06-07 à 10 36 19](https://user-images.githubusercontent.com/45802615/83964167-388f2280-a8ab-11ea-815b-f8fdf0b41575.png)

**Comment by laurensvalk** [comment]
Thanks for the detailed report @Patlepirate01 ! Here are two things you can try.

### Refreshing the pybricks code cache:
Sometimes, a normal refresh not enough. You may have to clear the cache also. Here's how you can do it on Windows/Mac.

![image](https://user-images.githubusercontent.com/12326241/83967676-0c33d000-a8c4-11ea-8887-b04648851b71.png)

### Deleting the bluetooth device
1. Close your browser.
2. In your Bluetooth settings on your Mac, delete the Pybricks Hub

Can you try again after following these steps?

**Comment by Patlepirate01** [comment]
Thanks for the quick answer but unfortunately after many trials it's not working.  It looks like after the Bluetooth connection something is "blocked".  As you can see in the printscreen below: device seems to be well disconnected and reconnected (in the Bluetooth Mac settings at least) 
![Capture d’écran 2020-06-07 à 13 53 20](https://user-images.githubusercontent.com/45802615/83968071-cd534980-a8c6-11ea-8189-cf56edebfcd7.png)
![Capture d’écran 2020-06-07 à 13 53 59](https://user-images.githubusercontent.com/45802615/83968072-d04e3a00-a8c6-11ea-997b-1e7ed2bc874f.png)
![Capture d’écran 2020-06-07 à 13 54 35](https://user-images.githubusercontent.com/45802615/83968073-d2b09400-a8c6-11ea-962b-dd3bbf5ca41b.png)

**Comment by laurensvalk** [comment]
When you go to `help>about Google Chrome` as shown below, you which version do you see?

![Screenshot from 2020-06-07 14-05-31](https://user-images.githubusercontent.com/12326241/83968236-063fee00-a8c8-11ea-8c3d-5eec007c9963.png)

**Comment by laurensvalk** [comment]
Also, could you try the following?

1. In Google Chrome go to chrome://flags/.
2. Search for `Experimental Web Platform features` and enable it.

**Comment by Patlepirate01** [comment]
The Experimental Web feature was already enabled and my Google version is
![Capture d’écran 2020-06-07 à 14 08 27](https://user-images.githubusercontent.com/45802615/83968371-0c829a00-a8c9-11ea-9447-baafe4ffdb6b.png)

**Comment by Patlepirate01** [comment]
Forgot to say that I systematically test on my 2 macs (one Macbook Air with OS version 10.13  and one iMac with os version 10.15...)

**Comment by phipsitn** [comment]
How does one get access to the code.pybricks.com system to help beta test?

**Comment by laurensvalk** [comment]
> How does one get access to the code.pybricks.com system to help beta test?

Thanks for your interest! Check out the beta notes & contact here: https://docs.pybricks.com/en/latest/start_pup.html

**Comment by dlech** [comment]
I am able to reproduce the problem. Flashing firmware works but connecting to the NRF UART service after that seems to hang forever without connecting. No errors appear until device is disconnected in which case we get the expected disconnected while retrieving services error.

**Comment by dlech** [comment]
Hi Pat,

I just uploaded a new firmware with a fix. So reload the app using the instructions above and flash the firmware again. Then connecting Bluetooth should work on macOS.
