### ISSUE TITLE
[Bug] The contact email doesn't work

### ISSUE THREAD

**Issue by yuoppp** [pybricks/support#351]
**Describe the bug**
The team@pybrics.com email doesn't work. I can't send any email there.
Gmail repsonds with an error "DNS Error: 570450 DNS type 'mx' lookup of pybrics.com responded with code NXDOMAIN Domain name not found: pybrics.com"

Here where I found the email.
https://pybricks.com/about/

**Comment by laurensvalk** [comment]
Try team@pybric**k**s.com :+1:
