### ISSUE TITLE
Connecting to Pybricks BLE service fails on Android

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#37]
Now that #34 has been fixed, something similar occurs on Android.

The bluetooth button appears to reach the connected state and it stays gray. After a while, it gives up:

![Screenshot_20200608-075924](https://user-images.githubusercontent.com/12326241/83997902-c2002c80-a95f-11ea-93a0-a462f6a8995d.png)

I got the same error when initiating firmware update, but that did eventually succeed.

**Comment by dlech** [comment]
I'm guessing that it had cached the old bad values from the older firmware. Everything is working for me on Android with the v3.0.0a2 firmware.

**Comment by laurensvalk** [comment]
I'm not sure - this was after refreshing the cache and updating the firmware.

I'll try again on another Android device.

**Comment by dlech** [comment]
I meant the OS Bluetooth device cache, not the browser cache.

**Comment by dlech** [comment]
Is this still a problem?

**Comment by laurensvalk** [comment]
I think we can close because we are not actively targeting Android right now.
