### ISSUE TITLE
[Feature] Add letter beta to app icon

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#375]
**Is your feature request related to a problem? Please describe.**

It would be nice to make the Pybricks Code icon slightly different for the beta version so it's easy to see which one you use.

This is especially useful in cases where the full name is not shown.

![image](https://user-images.githubusercontent.com/12326241/123393952-e5b00800-d59e-11eb-91fc-e2136caf6d93.png)

Here's one we can use. High-res version has been pushed to our repo with logos.

![logo_beta](https://user-images.githubusercontent.com/12326241/123395391-720efa80-d5a0-11eb-946e-d25d91a4ca65.png)

**Comment by dlech** [comment]
How about just adding a badge to the icon? 
![image](https://user-images.githubusercontent.com/963645/123445289-5f46f680-d59d-11eb-9956-3133cd2244d8.png)

We could also just make the name "Pybricks Beta" so it doesn't get cut off so easily.

**Comment by dlech** [comment]
We should also have a maskable version of the icon as described [here](https://web.dev/maskable-icon/).

**Comment by laurensvalk** [comment]
A badge is good; anything to easily tell them apart will do.
