### ISSUE TITLE
[Bug] Undefined Pybricks Code state after hub.system.reset(1)

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#378]
**Describe the bug**
The run button can get stuck,  after `hub.system.reset(1)`, and stay that way even if you reconnect.

This test was done on the Technic Hub

`Pybricks Code (Beta) v1.1.0-beta.1`
`Version 91.0.4472.101 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)`

**To reproduce**

![image](https://user-images.githubusercontent.com/12326241/124109109-15f81a80-da67-11eb-8285-69f0449a08b5.png)

First run the script, then click play again. 

```python
from pybricks.hubs import ThisHub
from pybricks.tools import wait

hub = ThisHub()

print(hub.system.reset_reason())

hub.system.reset(1)
```
And this isn't too bad. 

But it remains stuck after you reconnect, so a hard refresh is required.

![image](https://user-images.githubusercontent.com/12326241/124109271-42ac3200-da67-11eb-860f-83092ba4907c.png)

**Expected behavior**
Disconnect as during a regular power-off.

**Comment by laurensvalk** [comment]
Actually, the real cause is one step back. Even though the Bluetooth button correctly shows the disconnected state, the **run** button becomes enabled again.

![image](https://user-images.githubusercontent.com/12326241/124109897-ebf32800-da67-11eb-870b-90465fa27a49.png)

So if this button were not enabled, the problem documented in the first post couldn't even occur.

**Comment by dlech** [comment]
Fix is committed.
