### ISSUE TITLE
[Feature] 88005 Light Support

### ISSUE THREAD

**Issue by bricklife** [pybricks/support#38]
I tried to use 88005 Light from Pybricks, but it seems that the device is not supported.
https://www.lego.com/en-us/product/light-88005

LEGO official applications, e.g. Powered Up app, support it. I think it's almost the same as DCMotor. The IO Type ID is `0x08` as follows:
https://lego.github.io/lego-ble-wireless-protocol-docs/index.html#io-typ

**Comment by laurensvalk** [comment]
Thank you for the request. Yes, we still have to add support for the Light.

Several others have asked the same, so it sounds like we should prioritize this one :smile:

**Comment by laurensvalk** [comment]
The API will look like this.

![image](https://user-images.githubusercontent.com/12326241/84030863-0a860d00-a995-11ea-9680-d8700ff405c4.png)

**Comment by bricklife** [comment]
Thank you for your quick response! The API looks good. I'm looking forward to it 🥰

**Comment by Patlepirate01** [comment]
I was creating similar request when I saw this one...Test is on-going now well with 2 motors and light sensor...

**Comment by laurensvalk** [comment]
Thanks! In the meantime, maybe you'll like to use the builtin light of the ColorDistanceSensor:

```python

my_sensor = ColorDistanceSensor(Port.A)
my_sensor.light.on(Color.BLUE)

```

**Comment by Patlepirate01** [comment]
Thanks. Included in my current testing. Will probably do a small video later today

**Comment by laurensvalk** [comment]
Preliminary API added in https://github.com/pybricks/pybricks-api/commit/80840396aadcfe839946ccf52242fa490b214f81

[---> Doc preview <---](https://docs.pybricks.com/en/work/pupdevices.html#light)

We'll keep this issue open until it is also implemented & released.

Thanks to @ZPhilo for the LDraw Parts!

**Comment by ZPhilo** [comment]
> Thanks to @ZPhilo for the LDraw Parts!
You're welcome ;)
Just made an updated shortcut with realistic cable length (coiled)
https://www.ldraw.org/cgi-bin/ptdetail.cgi?f=parts/22168.dat
(don't forget the subpart! https://www.ldraw.org/cgi-bin/ptdetail.cgi?f=parts/s/22168s01.dat)

**Comment by laurensvalk** [comment]
![image](https://user-images.githubusercontent.com/12326241/84072321-4b027c80-a9cf-11ea-9331-193108e82672.png)

**Comment by Patlepirate01** [comment]
Brilliant 🤓😇🥰

**Comment by ZPhilo** [comment]
fiat lux...

**Comment by laurensvalk** [comment]
Done! :bulb:  :rocket: :bulb: 

If you refresh Pybricks Code and update the firmware, light support is now included.

Run the example below for some fun tests.

**Also please note that from now on you have to include imports explicitly**

```python
from pybricks.pupdevices import Light
from pybricks.parameters import Port
from pybricks.tools import wait, StopWatch
from math import cos, pi

# Initialize the light and a StopWatch
light = Light(Port.B)
watch = StopWatch()

# Cosine pattern properties
PERIOD = 1
MAX = 100

# Make the brightness fade in and out
while True:
    # Get the time in seconds
    time = watch.time()/1000
    
    # Evaluate the cosine
    brightness = (0.5-0.5*cos(time*2*pi/PERIOD))*MAX
    
    # Turn on the light, wait, then repeat
    light.on(brightness)
    wait(10)
```

I'll close this issue when some of you have confirmed that it is working. Thanks!

**Comment by bricklife** [comment]
@laurensvalk The example works fine! Thank you very much.

![IMG_4788](https://user-images.githubusercontent.com/266357/84157129-51632800-aaa5-11ea-8bc5-a6fe59fee97b.PNG)

**Comment by laurensvalk** [comment]
Excellent, thanks for confirming!

I'll close this issue.

**Comment by Patlepirate01** [comment]
Works also well for me. Great team support. Really pleasant to test with a so great support
