### ISSUE TITLE
[Bug] Prime Hub stays on after software power-off if USB connected.

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#381]
**Describe the bug**
When triggering a soft power-off while USB is connected, it does not shut down in the same way as holding the button.

The animation freezes and Pybricks Code stays connected (but fails to run anything).

**To reproduce**
```python
from pybricks.hubs import ThisHub
from pybricks.tools import wait

hub = ThisHub()

print(hub.system.reset_reason())
wait(100)
hub.system.reset(0) # Already applied support#379, so here doing power-off

# The run animation stays on and freezes
```

**Expected behavior**
Clean shutdown, same as holding the button.

**Screenshots**

![image](https://user-images.githubusercontent.com/12326241/124122198-1d72f000-da76-11eb-8dd0-f25e19237e0d.png)

![IMG_20210701_140214468](https://user-images.githubusercontent.com/12326241/124122135-0c29e380-da76-11eb-9591-4d1fce637466.jpg)

**Comment by dlech** [comment]
`0` is supposed to reset the hub, not power off. See #382 for power off.

**Comment by laurensvalk** [comment]
See #379 as indicated in comment.

**Comment by dlech** [comment]
We need to add a new method for proper shutdown that calls `pbsys_status_set(PBIO_PYBRICKS_STATUS_SHUTDOWN);`

**Comment by laurensvalk** [comment]
This can be closed because `reset` will not be used. See #379.

See https://github.com/pybricks/pybricks-micropython/issues/58 for graceful shutdown.
