### ISSUE TITLE
[V3.1] Improved editor, Powered Up Remote, MicroPython modules

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#407]
**Introduction**
With so many people already using the Powered Up remote, it's easy to forget that this is just a beta. There have been numerous changes under the hood as well for improved performance and a better user experience.

Some of these changes aren't as visible from the outside, but they will pave the way for big upgrades coming in the near future.

We'd like to stabilize this and ship it before we work on big new features.

**What's coming in V3.1**
- New text editor within Pybricks Code.
   - Switch from `Ace` to `Monaco` for better editing experience.
   - Improved search and replace tools.
- Powered Up remote support
   - This was started as a popular end-user feature request: #186
   - Still needs to be finalized: #404.
   - Lots of bluetooth performance upgrades for future stuff (yes!)
- Improved MicroPython experience
   - Enable additional features like slicing: #140. 
   - Complete documentation of included MicroPython features, instead of referring to external documentation: https://github.com/pybricks/pybricks-api/issues/63
   - Compatibility overviews to make it easier to see what each hub supports.  https://github.com/pybricks/pybricks-api/issues/66
- Hub system attribute:
   - Disable or change stop button so you can use the center button in a script #233
   - Additional hub information #52
   - Ability to shut the hub down from a user script.
- Ability to maintain motor position between scripts. #389
- Stability improvements such as:
  - Improved shutdown behavior: https://github.com/pybricks/pybricks-micropython/issues/36
  - Firmware installation fixes like: #403

**Comment by dlech** [comment]
Release candidate is out at https://beta.pybricks.com.
