### ISSUE TITLE
[Feature] Enable reversed and enumerate on Move Hub

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#413]
**Is your feature request related to a problem? Please describe.**
Most of the features currently disabled on Move Hub can be conveniently categorized, thus keeping the documentation simple.

`reversed` and `enumerate` are exceptions to this as most other features related to iterables are enabled. If we find ourselves with enough space left after enabling Bluetooth communication, we can consider if this is worth 400 bytes.

**Comment by dlech** [comment]
My vote is no, not worth it.

**Comment by laurensvalk** [comment]
Doc consistency is resolved by https://github.com/pybricks/support/issues/413 so we won't need this.
