### ISSUE TITLE
[Question] Chrome 85: Cut & Paste

### ISSUE THREAD

**Issue by GianCann** [pybricks/support#42]
How can I copy (& paste in another place) the text from the output/log window?

CTLR+C don't work.

**Comment by dlech** [comment]
Try <kbd>CTRL</kbd>+<kbd>INSERT</kbd> for copy and <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>V</kbd> for paste (start the REPL then press <kbd>CTRL</kbd>+<kbd>E</kbd> for paste mode)

**Comment by GianCann** [comment]
> Try CTRL+INSERT for copy and CTRL+SHIFT+V for paste

No, with this shortcuts don't work.
I want to" cut & past" error messages or script print output

**Comment by dlech** [comment]
<kbd>CTRL</kbd>+<kbd>INSERT</kbd> works for me to copy from the terminal.

I just copied this:

```
('pybricks', 'cplushub', '3.0.0a3', 'v3.0.0a2-7-gb4f6e128 on 2020-06-10', 'cplushub')
```

**Comment by GianCann** [comment]
Ok, yes... now it works.
I made an error with the laptop multifunctional keyboard.
Thank you @dlech

**Comment by dlech** [comment]
FYI, there is now also a context menu when right-clicking in the terminal:
![image](https://user-images.githubusercontent.com/963645/84571964-851ba780-ad5c-11ea-8168-f313dbfe6756.png)
