### ISSUE TITLE
Flashing firmware on Android is slow

### ISSUE THREAD

**Issue by dlech** [pybricks/support#438]
**Describe the bug**
Flashing firmware on City Hub and Technic Hub using Android OS takes longer than on other platforms.

**To reproduce**
1. Get a stopwatch
2. Time firmware flashing on non-Android
3. Time firmware on Android

**Expected behavior**
Times should be reasonably close.

**Comment by dlech** [comment]
As discussed in https://github.com/pybricks/support/issues/403#issuecomment-897897102, this is caused by a bug in Chromium where the MTU is negotiated to the minimum value on Android and higher values on other platforms.

Upstream bug is https://crbug.com/1164621. There has been a preliminary patch proposed there, so we just need to get it official submitted and merged.

**Comment by dlech** [comment]
This has been fixed in Chromium 98.

We could modify https://github.com/pybricks/pybricks-code/blob/e7d44ea9a9195bc2a612a22acd84e09dfc048dac/src/firmware/sagas.ts#L382 to check for this version or just wait until most of the world has upgraded and remove the Android check there altogether.

**Comment by dlech** [comment]
Fixed in https://github.com/pybricks/pybricks-code/commit/614e0b00743d2fb07d710078a28145336d04ab04

**Comment by laurensvalk** [comment]
What is the behavior on older phones after this fix? Just slow or broken?

**Comment by dlech** [comment]
The age of the phone doesn't matter, only the version of Chrome. Firmware will fail to flash versions prior to 98 which was released over a year ago.

**Comment by laurensvalk** [comment]
Ah. I was thinking of Android not getting updates on older phones., but indeed Chrome should still be getting updates on those.
