### ISSUE TITLE
Support for SPIKE Essential hub (Technic Small Hub)

### ISSUE THREAD

**Issue by dlech** [pybricks/support#439]
**Is your feature request related to a problem? Please describe.**
LEGO Education just released a new 2-port hub.

[spec sheet](https://education.lego.com/v3/assets/blt293eea581807678a/blt8a69ecd244fee569/60fe864661f38746a5778f86/LE_SPIKE_Essential_Tech_fact_sheet_Small_Hub_45609_2HY21_Digital.pdf)

[![](https://education.lego.com/v3/assets/blt293eea581807678a/blt266196dd2a45c72b/610105a4429fb95880e5abdf/smallHub.png?auto=webp&format=png&width=800&height=536&quality=90&fit=bounds)](https://education.lego.com/en-us/products/lego-technic-small-hub/45609)

Assuming that this is similar enough to SPIKE Prime, we could potentially add support for both at the same time.

**Comment by dlech** [comment]
Give this issue a :+1: if you would like to see support for this hub added sooner rather than later.

**Comment by Vinz1911** [comment]
Awesome, this will be great with the upcoming Hub2Hub Feature. Why just 2 Ports, such a hub deserves 4, Damn Lego!!!!

**Comment by dlech** [comment]
This is done. Please open new issues for any problems encountered.
