### ISSUE TITLE
Support for SPIKE Essential Small Angular Motor

### ISSUE THREAD

**Issue by dlech** [pybricks/support#441]
**Is your feature request related to a problem? Please describe.**
LEGO Education just released a new Small Angular Motor with the new SPIKE Essential set.

[spec sheet](https://education.lego.com/v3/assets/blt293eea581807678a/blt20ee0f27f6735942/60fe86455483765886b0da3c/LE_SPIKE_Essential_Tech_fact_sheet_Small_Angular_Motor_45607_2HY21_Digital.pdf)

[![](https://education.lego.com/v3/assets/blt293eea581807678a/blt8820b8d0307ef97e/610105a4d7b6f246ab876ae7/smallMotor.png?auto=webp&format=png&width=800&height=536&quality=90&fit=bounds)](https://education.lego.com/en-us/products/lego-technic-small-angular-motor/45607)

**Comment by dlech** [comment]
Give this issue a :+1: if you would like to see support for this hub added sooner rather than later.

**Comment by laurensvalk** [comment]
Documentation: Need to add this to the render with all the motors"

![image](https://user-images.githubusercontent.com/12326241/142872798-8aa012cb-907e-42dd-9bca-a216f0e37e1d.png)

**Comment by ZPhilo** [comment]
https://www.ldraw.org/cgi-bin/ptdetail.cgi?f=parts/68488c01.dat ;)
