### ISSUE TITLE
Error message in Pybricks Code when releasing the hub button too early while flashing firmware

### ISSUE THREAD

**Issue by jjsherm2** [pybricks/support#464]
**Describe the bug**
City Hubs won't connect when trying to download Pybrick firmware.  Error message displayed: "Unexpeced error while trying to connect:  Connection failed for unknown reason."

Same issue exist for two different City Hubs trying to connect to an LG Gram laptop running windows 10 and on a Samsung Galaxy Tab 5Se.

**Comment by dlech** [comment]
Please see https://github.com/pybricks/support/discussions/270. Will will need more information, like logs, to find the source of the problem.

**Comment by jjsherm2** [comment]
The beta site has the same issue.

John Sherman
Sent from Yahoo Mail on Android 
 
  On Thu, Sep 2, 2021 at 9:01 AM, David ***@***.***> wrote:   


Also, please try https://beta.pybricks.com to see if the issue has already been fixed.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jjsherm2** [comment]
Not helpful, the only thing that applied was to reboot windows and that didn't work and there was nothing related to Samsung devices.  I am more than happy to provide additional info if you can tell me what you need and how to find it (for example: I don't know what logs you would be looking for or where they are).  Please forgive my ignorance I haven't worked with programming for many years.

Thanks
John Sherman
Sent from Yahoo Mail on Android 
 
  On Thu, Sep 2, 2021 at 8:59 AM, David ***@***.***> wrote:   


Please see #270. Will will need more information, like logs, to find the source of the problem.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dlech** [comment]
The troubleshooting guide at #270 describes what we are looking for. Are the errors in the "Developer Console"? What is in the "Chrome Device Log"? If none of those have anything to identify the problem, then "Capturing Bluetooth Packets".

**Comment by jjsherm2** [comment]
David thanks for the clarification.  attached are screen images of the Developer Console and Chrome Device Log.  I haven't been able to try the Packet capture.
Also note that on an attempt to after these logs, got the same error messages but the City Hub light started flashing red, blue, green in a continuous cycle.  It was not connected and would not leave this mode until the battery was pulled out.
thanks,
John Sherman 

    On Thursday, September 2, 2021, 12:59:22 PM PDT, David Lechner ***@***.***> wrote:  
 
 


The troubleshooting guide at #270 describes what we are looking for. Are the errors in the "Developer Console"? What is in the "Chrome Device Log"? If none of those have anything to identify the problem, then "Capturing Bluetooth Packets".

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jjsherm2** [comment]
[Issue#464.pptx](https://github.com/pybricks/support/files/7106812/Issue.464.pptx)
Here is the file.

**Comment by jjsherm2** [comment]
I have now successfully flashed both my hubs.  The issue may have been I just didn't hold the button on the hubs long enough.  You might want to consider rewording the instructions to emphasize this.  My apologies for taking up your time.
Thanks,

**Comment by dlech** [comment]
No problem. This is valuable feedback that can help us improve so we are glad you took the time to figure out what the problem was and let us know about it instead of giving up right away and not giving any feedback.

**Comment by dlech** [comment]
In addition to documenting it, we are also considering improving the firmware update process to not require users to manually start the hub in update mode, in which case holding the button should not be needed at all.

**Comment by dlech** [comment]
There is also an existing issue about improving the error messages if a hub disconnects while flashing firmware: https://github.com/pybricks/pybricks-code/issues/255

**Comment by dlech** [comment]
The UI has been improved in Pybricks Code v3.2.0b3 (Pybricks Beta v2.0.0-beta.3).
