### ISSUE TITLE
Hello, I want to install the firmware via android smart-phon on a "lego technic hub" but I always get the error message "The hub took too long to respond. Restart the hub and try again."What shall I do?

### ISSUE THREAD

**Issue by willi-cleopatra** [pybricks/support#469]
**Question**
Write your question here.

**Context**
What are you trying to accomplish that led to this question?

**Screenshots**
There is a saying that a picture is worth a 1000 words. Screenshots really help to identify and solve problems.

**Comment by laurensvalk** [comment]
Could you try this via the beta version of our app?

https://beta.pybricks.com/

It might already be working on this latest version.

**Comment by willi-cleopatra** [comment]
Thank you very much.  The installing process is done whithout error message.
The download was longer than before. But it works.
Now I will write some programms.
Best regards
willi-cleopatra
