### ISSUE TITLE
[Question] Read serial input buffer

### ISSUE THREAD

**Issue by GianCann** [pybricks/support#51]
In the 'autonomous running' mode, there is a way to read the input buffer from the nRF UART Service?
I can "print" on this service, so I can send data to other device... but if i want to receive some byte from the 'external world'?

https://youtu.be/s1B9pz1sM9U

**Comment by dlech** [comment]
It looks like we need to enable `MICROPY_PY_BUILTINS_INPUT` to get the builtin `input()` function.

**Comment by laurensvalk** [comment]
This is available in the latest build using:

```python
input()
```

**Comment by GianCann** [comment]
What am I doing wrong?

```
a=input()
print(a)
```

_('pybricks', 'cplushub', '3.0.0a3', 'b8aea4e on 2020-06-09', 'cplushub')
Traceback (most recent call last):
  File "main.py", line 7, in <module>
NameError: name 'input' isn't defined_

**Comment by GianCann** [comment]
Ah... It's not yet released?

https://github.com/pybricks/pybricks-micropython/commit/38b57c7e7683503140c8adfaaf95e006b70251f6

**Comment by laurensvalk** [comment]
You can always download the latest builds.

Click on the green check mark of any version you want, usually the latest [from master](https://github.com/pybricks/pybricks-micropython/commits/master):

![image](https://user-images.githubusercontent.com/12326241/84890104-3e021f00-b09a-11ea-8343-3f0b049702a4.png)

Then click on details and then pick the artifact you want to download:

![image](https://user-images.githubusercontent.com/12326241/84890268-799ce900-b09a-11ea-8f17-3b840ca87ee1.png)

**Comment by GianCann** [comment]
@laurensvalk It works, but not exactly as I expected.
I meant a non-blocking input/read function.
However, this is already useful as is

**Comment by laurensvalk** [comment]
That will be there in time. We might have a `Mailbox`, similar to EV3 (see docs). Would that suit your use case?

**Comment by GianCann** [comment]
> Would that suit your use case?

I try to explain one use case.
Think of a train circuit with 3 different trains.
Each train has its own pre-established schedule
Each train is viewed as a BLE serial device by another system (Arduino? Raspberry? ...)
By sending a specific command to every single train, I could change the default behavior of the main program or maybe activate a secondary one

**Comment by laurensvalk** [comment]
That sounds like the perfect use case for the Mailbox approach :+1:

**Comment by GianCann** [comment]
There is a strange behavior...

Look this very simple code:

```
from pybricks.pupdevices import Light
from pybricks.hubs import CPlusHub
from pybricks.parameters import Port
from pybricks.tools import wait, StopWatch
hub = CPlusHub()
import uos

# Initialize the light and a StopWatch
lightA = Light(Port.A)
lightB = Light(Port.B)

print(hub.battery.voltage())
print(uos.uname())

x=True
s=False 
while x==True:
    a=input()
    if a=="a1":
        lightA.on(100)
    elif a=="a0":
        lightA.on(0)
    elif a=="b1":
        lightB.on(100)
    elif a=="b0":
        lightB.on(0)
    elif a=="end":
        s=True
        x=False
    elif a=="close":
        x=False
    else:
        print(a + " not a valid command")

print("Close program")
if s==True:
    print("Shutdown the hub")
    wait(500)
    hub.shutdown()
```
1) If I run the code from the App, It works perfectly
2) If I merge the main.py with the firmware, It work perfectly using the App only as 'terminal' (running the main.py from the green button)
3) If I connect the HUB with another BLE UART client (as nRF UART App) It doesn't work... I get the initial print output (voltage battery and firmware version) but if I send a command ("a1", "end"...), the hub reply with same string, without react to the command (power on the Light or shutdown the hub).

![image](https://user-images.githubusercontent.com/45897944/84902856-a60e3080-b0ad-11ea-871a-d973b16f9e51.png)

**Comment by laurensvalk** [comment]
We don't currently support this custom interface - please check in a few days where we are with `pybricksdev`. You can learn how things work from there.

**Comment by GianCann** [comment]
ok, I thought serial communication was two-way anyway.

**Comment by dlech** [comment]
The input function reads until there is a newline character before continuing. I don't remember if the nRF app lets you send a newline character or not.

**Comment by GianCann** [comment]
> I don't remember if the nRF app lets you send a newline character or not.

I also tried with nRF Toolbox, which allows you to specify how to close the transmission: LF, CR or LF + CR

**Comment by GianCann** [comment]
I obtained it works with a my Android App that send the string with a \n\r termination!
