### ISSUE TITLE
Bluetooth GATT Client on EV3

### ISSUE THREAD

**Issue by Igi4** [pybricks/support#514]
Hi, thanks for ale the great work on Pybricks, it's a great piece of software.

Is there a way to use Micropython's low level ubluetooth module on EV3? Or, is there any other way on how to create a BLE GATT client on an EV3 brick with pybricks micropython?

When I tried to compile the vanilla micropython 1.16 on EV3, I managed to compile it with the ubluetooth module, however I ran into multiple segmentation fault errors when I tried to use the ubluetooth module in a micropython script on EV3. 

My goal is to use the EV3 as a remote control for a few Buwizz bricks and Technic Hubs. Any help / advice is appreciated.

**Comment by dlech** [comment]
This isn't a feature we plan on adding to Pybricks but if any future hackers want to know more, feel free to ask in https://github.com/pybricks/support/discussions.
