### ISSUE TITLE
How do you turn up the volume on an EV3 micropython robot?

### ISSUE THREAD

**Issue by mt042505** [pybricks/support#522]
**Question**
How do you turn up the volume on an EV3 micropython robot?

**Context**
I was trying to play some audio on the robot but I could not figure out how to turn up the volume.  So I was wondering if there was just a simple command to do it.

**Comment by dlech** [comment]
Try [speaker.set_volume()](https://pybricks.com/ev3-micropython/hubs.html#pybricks.hubs.EV3Brick.speaker.set_volume).
