### ISSUE TITLE
[Feature] Implement pybricks.hubs.MoveHub.imu.tilt

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#539]
**Is your feature request related to a problem? Please describe.**
The Move Hub has had an experimental IMU implementation for a while now. There's not enough space to implement something equivalent to the other hubs.

Since V3.1 may be the last release for Move Hub, we'll want to make sure this is working the way we want. And documented accordingly.

It may be useful to see if we can implement a crude version of tilt/roll measurement, as this is really the main use case for having the IMU enabled in the first place. The user can't really do this in their code since floating point support isn't enabled, and look-up tables in user code would take too much space.

Maybe we can use libfixmath.

**Comment by dlech** [comment]
I was able to use the existing API for the R2-D2 example without problems, so I would be fine not adding/changing anything.

**Comment by laurensvalk** [comment]
That sounds good. Also, I'm not going to have time to look at this any time soon, so let's not hang V3.1 on it.

So :shipit: :ship:

**Comment by laurensvalk** [comment]
It should be feasible to implement `tilt` using `libfixmath`.

As for base orientation specification, we can't use the `Axis` in the hub init like we do for the other hubs, but we could instead provide a `Side` argument to `tilt` to specify which side of the hub is "up" in the (0, 0) orientation.

**Comment by laurensvalk** [comment]
Also fix acceleration units as per https://github.com/pybricks/pybricks-api/issues/94

**Comment by laurensvalk** [comment]
> It should be feasible to implement tilt using libfixmath.

> As for base orientation specification, we can't use the Axis in the hub init like we do for the other hubs, but we could instead provide a Side argument to tilt to specify which side of the hub is "up" in the (0, 0) orientation.

This works quite nicely: https://github.com/pybricks/pybricks-micropython/tree/movehub-tilt

But it takes up a bit too much space: 832 bytes.

This is partly due to bringing in fix16 trigonometry. This may not be worth it unless we use it for other things like https://github.com/pybricks/pybricks-micropython/pull/93

**Comment by laurensvalk** [comment]
I'm going to give this a final push for this release:
- It makes sensor for our upcoming code editor --- hub init and acceleration reads would all be the same
- Since the Move Hub has BLE broadcast, broadcasting tilt makes it a great contender for remote control.

**Comment by laurensvalk** [comment]
https://www.facebook.com/reel/1404526097073489

**Comment by laurensvalk** [comment]
Fixed by https://github.com/pybricks/pybricks-micropython/commit/c42a85fe75d503a12309e387b0d7fca944a60977 and https://github.com/pybricks/pybricks-micropython/commit/5e2d65de29cb15f70aa5a43c5056dfd0c82749fb
