### ISSUE TITLE
Not able to upload firmware on Imac[Bug] 

### ISSUE THREAD

**Issue by Patlepirate01** [pybricks/support#55]
**Describe the bug**
I try to reinstall last version of the firmware (after using again standard lego firmware in the past days) without success

**To Reproduce**
1. Go to 'Flash HUB firmware'
2. I push the green button, select the hub in the list and associate the Hub
3. Light is flashin Green, Red, Blue,.... as expected but no upload....
4. I stop after 10'...

**Expected behavior**
Firmware upload

**Comment by dlech** [comment]
Can you please check the console log and report back the last few errors listed there after it gets stuck?

If you need step-by-step instructions on how to do this: https://support.google.com/docs/thread/1873663?hl=en

**Comment by dlech** [comment]
Possibly same problem as  #44.

**Comment by Patlepirate01** [comment]
Will check later. In the meantime I have tried on my other iMac and it seems to be working...

**Comment by Patlepirate01** [comment]
Would be good to have a message at the end of the firmware upload.... Updated successful (if it's the case I didn't receive it...)

**Comment by dlech** [comment]
We are working on it :smile: Also working on better error notification.

**Comment by Patlepirate01** [comment]
Not able to get the checksum...

![Capture d’écran 2020-06-17 à 20 47 14](https://user-images.githubusercontent.com/45802615/84937287-cb199800-b0db-11ea-9814-9595e59c36e8.png)

**Comment by Patlepirate01** [comment]
Working iMac: OS Catalina 10.15.5 with Chrome 85.4.41.73.0
Non working Mac Book Air with : OS High Sierra 10.13.6 with Chrome 85.4.41.73.0

**Comment by dlech** [comment]
I have made some changes that could affect this. Could everyone please test again?

**Comment by Patlepirate01** [comment]
It works. I have tested the upload on Cplus and City hubs and both are working well... It's a good present for my Holidays that will start in a few hours.... Will have more time for testing .

**Comment by Patlepirate01** [comment]
For me issue is closed
