### ISSUE TITLE
[Question] ability to change the speed for 42099

### ISSUE THREAD

**Issue by MrPawelCz** [pybricks/support#553]
How do I add to the "http://pybricks.com/projects/sets/technic/42099-off-roader/powered-up-remote/" http://pybricks.com/projects/sets/technic/42099-off-roader/powered-up-remote/ code the ability to change the speed at which the vehicle is moving and to change the steering angle?

There are two red buttons on the controller, I thought it would be nice to be able to set 3 speeds, LOW, MEDIUM and HIGH.

How to write such a program? I have not found a description in the documentation of how to use these buttons.

**Comment by MichalBrylka** [comment]
try using "dc" function from Motor class:
https://docs.pybricks.com/en/stable/pupdevices/motor.html#pybricks.pupdevices.Motor.dc
Low can be 30, Medium 60 and high as 100, optionally multiplied by -1 if you want to go back 

As per buttons:
https://docs.pybricks.com/en/stable/pupdevices/motor.html#pybricks.pupdevices.Motor.dc

red buttons are called LEFT and RIGHT respectively: 
https://docs.pybricks.com/en/stable/parameters/button.html#Button
