### ISSUE TITLE
[Question] bluetooth connection problem at macOS 

### ISSUE THREAD

**Issue by ErikLundJensen** [pybricks/support#554]
**Question**
I try to run pybricks at MacBook Pro 2019 macOs 12.0.1, however, pybricks can't pair with LEGO Technic Hub.
In chrome://bluetooth-internals I can connect and get GATT Connected so it does not seem to be a Chrome nor Mac issue to form pair.

There are no errors from pybricks - just nothing happens when trying to connect -- keeps on waiting for pairing.

I'm new to pybricks, but should I expect bluetooth problems when using macOS with pybricks?

**Context**
Connecting to Technic Hub from macOs 12.0.1

**Comment by dlech** [comment]
Did you flash the Pybricks firmware first?

**Comment by ErikLundJensen** [comment]
The flash dialog also hangs without getting a connection.

**Comment by laurensvalk** [comment]
Did you put the hub in update mode by holding the hub button until it blinks purple?

Instructions and a video can be found here: https://pybricks.com/install/technic-boost-city/

**Comment by ErikLundJensen** [comment]
I tried that, the purple continues to flash and the hub is not shown in UI. I'll try with another Technic hub later this month.

**Comment by dlech** [comment]
Are you clicking the firmware flash button or the Bluetooth button in Pybricks Code?

**Comment by ErikLundJensen** [comment]
the firmware flash button.

**Comment by dlech** [comment]
It sounds like you are doing it right. We have some other troubleshooting tips in #270 but I'm not sure what could be wrong in this case.

**Comment by injeniero** [comment]
@dlech @ErikLundJensen I had to enable chrome://flags/#enable-experimental-web-platform-features for it to work. I'm running on MacBook Pro 2019 macOs 12.1.0 with chrome Version 97.0.4692.71 after enabling the flag and restarting the browser, I was able to connect.

**Comment by dlech** [comment]
> I had to enable chrome://flags/#enable-experimental-web-platform-features for it to work.

This should only be required on Linux. If you turn it back off does it still work?

**Comment by injeniero** [comment]
I just tried disabling it and it continues to work. I can only guess by setting this it forced me to restart chrome and that made it work.

**Comment by dlech** [comment]
Closing since this issue is a few years old and lots has changed since then. Any future visitors experience connection issues on macOS: please log Bluetooth packets and share them in #938 so we can try to figure out what is going on.
