### ISSUE TITLE
[Bug] Install as app button missing

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#560]
**Describe the bug**
The "Install as app" button appears to be missing

This was first reported on [Facebook](https://www.facebook.com/Pybricks/posts/917696542199160?comment_id=917972045504943), and at a glance I think I might see the same.

I'm not sure this is since the new release or whether this was the case for a while.

**To reproduce**
1. Uninstall Pybricks Code and Beta via the ⋮button.
2. Restart or hard refresh
3. Install as app button is still not there.

![image](https://user-images.githubusercontent.com/12326241/147050344-a0f4487d-b173-4ce1-8039-2551905a6a63.png)

**Comment by dlech** [comment]
There was a bug that produced an incorrect manifest.json file that only affected non-beta versions. I have manually fixed the file on the web server.
