### ISSUE TITLE
[Bug] Powered up remote connection task can get stuck in loop

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#567]
**Describe the bug**

When running the code below the City Hub gets stuck. It cannot be stopped with the hub button, nor with Pybricks Code stop button.

The hub light is still fading so `pbio` is still running. The remote light stays solid white.

**To reproduce**

Install firmware on City Hub with `Pybricks v3.1.0 (Pybricks Beta v1.2.0-beta.1)`.

Run this program from Pybricks Code.

After a few prints, turn on the remote. Then everything stops.

```python
from pybricks.pupdevices import Remote
from pybricks.tools import wait

from uerrno import ETIMEDOUT

for i in range(1000):
    print("Attempt", i)
    try:
        remote = Remote(timeout=100)
        print("Connected!")
    except OSError as e:
        if e.errno != ETIMEDOUT:
            raise e
```

**Expected behavior**
This program should print `Attempt X` every 100 ms until the remote is turned on. Then it should print `"Connected!"`.

**Additional context**
Above example was inspired by the discussion _Originally posted by @serkiri in https://github.com/pybricks/support/issues/566#issuecomment-1003046198_

When running this on Essential Hub, it doesn't hang but fails with `EBUSY`.

**Comment by dlech** [comment]
Many Bluetooth tasks are currently not properly cancelable and don't have proper error detection. With this small of timeout, the Bluetooth chip probably doesn't even have time to start scanning. It probably would have been better if we would have left out the timeout parameter.

**Comment by SpudGunMan** [comment]
I do find the timeout handy might just need a documentation details about this?

**Comment by laurensvalk** [comment]
This also happens for the default 10 second timeout eventually.
