### ISSUE TITLE
[Question] DriveBase.straight( wait=False) keyword arguments?

### ISSUE THREAD

**Issue by shihhaoyang** [pybricks/support#57]
I am teaching kids to use micropython for FLL, they really enjoyed and excited using Pybrick.

**Question**
We know in Motor class there is a "wait=" keyword argument for parallel tasking. But when we use DriveBase, we can not find this in the documentation. Is there any other method that is easier for kids to do the parallel tasking in DriveBase or they have to use threading.Thread() method?

**Comment by dlech** [comment]
There is an experimental function to run multiple task in parallel.

https://github.com/pybricks/pybricks-micropython/blob/master/bricks/ev3dev/modules/pybricks/experimental.py

https://github.com/pybricks/support/issues/80#issuecomment-653425765
