### ISSUE TITLE
SPIKE USB installer crashes the browser if another app is using the hub

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#592]
This issue was reported for https://install.pybricks.com/

> As soon as a process is running on the hub (e.g. because the official loge MINDSTORMS / SPIKE app is still open (connection attempts)) the following error appears when clicking on "connect":
--> Failed to connect. Please wait 60 seconds and try again. Make sure that no other apps are using the hub."
The entire browser crashes (Edge, Windows 11). There are no entries in the Windows "event log"

> Thank you for your help. The browser(s) (also affects chrome) do not freeze, they simply crash.
This is partly also when you click on the "Install" button. However, the problem cannot be reproduced for me (sometimes it works, sometimes it doesn't).

_Originally posted by @DanNetor in https://github.com/pybricks/support/issues/591#issuecomment-1012967894_

**Comment by laurensvalk** [comment]
> Failed to connect. Please wait 60 seconds and try again. Make sure that no other apps are using the hub

This is the expected behavior. All other apps that use the hub must be closed.

> The browser(s) (also affects chrome) do not freeze, they simply crash.

I can't seem to reproduce this unfortunately.

**Comment by dlech** [comment]
If the entire browser crashes, then the issue needs to be reported to Microsoft. There is nothing we can do about it.

**Comment by laurensvalk** [comment]
We are now using DFU for installation, so we can close this.
