### ISSUE TITLE
[Bug] Clean install error for Mindstorm RI Hub

### ISSUE THREAD

**Issue by poldolot** [pybricks/support#598]
During installation on MacOS, Chrome browser I've got this error:
```
Something went wrong. Please try again.
from _firmware.install_pybricks import install; install()
Starting installation script.
Checking installation files.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "_firmware/install_pybricks.py", line 151, in install
  File "_firmware/install_pybricks.py", line 134, in get_file_hash
OSError: [Errno 2] ENOENT
>>> 
```

**Comment by laurensvalk** [comment]
This looks like #597. Can you hard refresh the page?

**Comment by poldolot** [comment]
I'm php programmer, so I do hard refresh every time, but to be sure I've also tried on second MacBook and the installation went through with no error, that's weird ;>

**Comment by laurensvalk** [comment]
If you want to take a screenshot of the page, it should be easy to find out.

Or maybe it had refreshed the page, but not the resources.

**Comment by laurensvalk** [comment]
This will all be taken care of when it's integrated in our main app, which checks for the right versions. :)

Sorry for the trouble.
