### ISSUE TITLE
[Bug] Can not restore BETA Inventor HUB

### ISSUE THREAD

**Issue by Nurech** [pybricks/support#603]
Following instructions to restore Inventor HUB fails. Although the program itself ran very nice.

Fails on step 3

```
1. Power the hub via USB.
2. Go to Pybricks beta and connect to the hub.
3. Run the following script:

from pybricks.experimental import restore_firmware

restore_firmware()

4. Wait a few minutes and the original firmware will start automatically.
```

```python
https://beta.pybricks.com/

from pybricks.experimental import restore_firmware
restore_firmware()

Traceback (most recent call last):
  File "main.py", line 2, in <module>
OSError: [Errno 1] EPERM: 

The requested operation is not valid in the current state:
--> Check the documentation for required conditions.
--> Check the line in your script that matches
    the line number given in the 'Traceback' above.
```

To resolve, I had to go into DFU mode and following instructions I was able to recover.
https://dfu.pybricks.com/index.html

**Comment by laurensvalk** [comment]
Thanks for reporting this. We've just released a fix.

I've also added a link to the DFU page so others can find it too in case there are problems.

If you want to try it, please refresh the page (CTRL+F5 or open in a private window), and repeat the installation.
