### ISSUE TITLE
[Question] Is there a way to connect to the internet via WiFi

### ISSUE THREAD

**Issue by TheGreyDiamond** [pybricks/support#61]
**Question**
Is it possible to connect to the internet via WiFi with the EV3? 

**Context**
I want to get the contents of a specific github file via WiFi.

**Screenshots**
_Nothing to screenshot here!_

**Comment by dlech** [comment]
There sure is. Have a look at https://www.ev3dev.org/docs/networking/.

**Comment by TheGreyDiamond** [comment]
Am I able to use the default python functionalities to query data etc?

**Comment by dlech** [comment]
It depends. Pybricks uses MicroPython, which can't do everything Python can. But it can do quite a bit.
