### ISSUE TITLE
[Question] How to call a function on a running program?

### ISSUE THREAD

**Issue by Nurech** [pybricks/support#616]
Either directly or changing some variable to trigger such action. Essentially sending upstream data to a running program. Is this possible? If so, which documentation covers this?

**Comment by dlech** [comment]
Please see https://github.com/pybricks/support/issues/262.

**Comment by Nurech** [comment]
So it's in the works. Good luck! Closing this for now.

**Comment by Novakasa** [comment]
In the meantime, maybe something like this is what would work for you: https://github.com/pybricks/support/issues/470#issuecomment-917070340

**Comment by Nurech** [comment]
> In the meantime, maybe something like this is what would work for you (communicating with the hub via the `pybricksdev` python library): [#470 (comment)](https://github.com/pybricks/support/issues/470#issuecomment-917070340)

Thank you! At first glance that looks very promising.

**Comment by laurensvalk** [comment]
There is now a tutorial here: https://pybricks.com/projects/tutorials/wireless/hub-to-device/pc-communication/

[![hub-to-device](https://user-images.githubusercontent.com/12326241/197725270-d815adc6-23f2-4459-9189-7978fcfa93de.png)](https://pybricks.com/projects/tutorials/wireless/hub-to-device/pc-communication/)

So we can close this issue.
