### ISSUE TITLE
[Question] Is the MoveHub integrated motor usable?

### ISSUE THREAD

**Issue by bestimmaa** [pybricks/support#620]
Since there is no mention in the API docs for the MoveHub - is it possible to use the integrated motor of the MoveHub?

**Comment by laurensvalk** [comment]
Yes, you can use them like any other motor. They are labeled as A and B on the hub.

It is mentioned in a few places, but maybe we can make it clearer.

**Comment by bestimmaa** [comment]
Thanks for your reply! If you don't mind: Where is this mentioned exactly? Maybe I overlooked this. I assumed it's a property of the hub class but the only features mentioned were lights, accelerometer and such.

**Comment by dlech** [comment]
We should probably add it to this picture.

![motor image from docs](https://docs.pybricks.com/en/stable/_images/pupmotors_label.png)

**Comment by laurensvalk** [comment]
It's linked in the caption of the motor overview:

![image](https://user-images.githubusercontent.com/12326241/151626133-4240f808-8002-4dde-803b-53f3cb56079d.png)

It doesn't really fit well in the picture since we need to show both sides.

**Comment by dlech** [comment]
Looks OK to me.

![image](https://user-images.githubusercontent.com/963645/151627089-9793e84e-7786-4bad-ba32-e41b965cb652.png)

**Comment by bestimmaa** [comment]
Thanks for taking the time, I definitely missed this!
