### ISSUE TITLE
[Question] Are Chromium and Opera working on macOS?

### ISSUE THREAD

**Issue by pqhf5kd** [pybricks/support#635]
**Question**
Does PyBricks work with Chromium or Opera on macOS?
Chromium tells me that it is scanning but my hub doesn't appear.

Opera tells me 'No Bluetooth adapter could be found'. 
#enable-web-bluetooth doesn't appear to exist anymore. I tried enabling both #enable-web-bluetooth-new-permissions-backend and #enable-bluetooth-spp-in-serial-api, but neither helped. 

Chrome was working fine on the same machine (although I uninstalled it before I tried Opera and Chromium

**Comment by dlech** [comment]
Chromium should work the same as Chrome AFAIK. I'm not sure what the status of Opera is. [This](https://github.com/WebBluetoothCG/web-bluetooth/blob/main/implementation-status.md#opera) suggests that Opera has its own flag that needs to be enabled.

We also have some troubleshooting tips: https://github.com/pybricks/support/discussions/270
