### ISSUE TITLE
[Bug] Hub stays connected when closing Pybricks Code in Ubuntu 22.04

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#646]
**Describe the bug**
The hub stays connected when closing Pybricks Code in Ubuntu 22.04.

**To reproduce**
1. Connect to the hub (tested with Technic Hub)
2. Close Pybricks Code app window or browser

Hub LED stays solid white. It also stays connected in the Ubuntu UI:

Disconnecting from there does work.

![image](https://user-images.githubusercontent.com/12326241/164942728-93627db6-16e1-408f-b338-0d7a706af731.png)

This is on a clean Ubuntu 22.04 install with Chrome Version 100.0.4896.127 (Official Build) (64-bit)

**Expected behavior**
Disconnect on closing the browser.

**Comment by laurensvalk** [comment]
This also happens when clicking the disconnect button.

**Comment by dlech** [comment]
logs:
![image](https://user-images.githubusercontent.com/963645/171941815-2510ded5-4613-4200-adc2-48922783c9c3.png)

**Comment by dlech** [comment]
Upstream bug: https://crbug.com/1332640

**Comment by dlech** [comment]
This should be fixed in chromium v104.

**Comment by dlech** [comment]
Confirmed fixed in chromium 104.

**Comment by laurensvalk** [comment]
Is this related to disconnecting being quite slow now or is that a separate issue? On Ubuntu it can take up to 5 seconds now for the disconnect button to complete.

**Comment by dlech** [comment]
> Is this related to disconnecting being quite slow now or is that a separate issue? On Ubuntu it can take up to 5 seconds now for the disconnect button to complete.

The 5 second delay is intentional as workaround for a different upstream bug. https://github.com/pybricks/pybricks-code/commit/509c635a07d1267d9417601f3929c5675befe080
