### ISSUE TITLE
[Suggestion] Change the script in main.py

### ISSUE THREAD

**Issue by GianCann** [pybricks/support#65]
Actually, the default code in main.py (in the xxx-firmware.zip file) contains:

```
motor = Motor(Port.B)
motor.run_angle(1000, 90)
```

This code cannot work now. See #41 

I suggest to change with:
```
import uos
print(uos.uname())
```

**Comment by dlech** [comment]
We were actually thinking about printing something like that when Bluetooth is connected.

If that is the main program and Bluetooth is not connected, then running the program will seem like it does nothing. Maybe it would be better to blink the light or something like that in the default main program?

**Comment by GianCann** [comment]
> Maybe it would be better to blink the light or something like that in the default main program?

Yes, is a good idea.
If no custom program is present, is useful to have a simple feedback "All it's ok" by Pybricks.
- BLE Connection present? LED blink + message
- BLE Connection not present? Only LED blink

**Comment by laurensvalk** [comment]
This has been resolved for now. Thanks for the pull request!
