### ISSUE TITLE
[Bug] DriveBase's drive command has an incorrect argument named "drive_speed"

### ISSUE THREAD

**Issue by markovian72** [pybricks/support#68]
**Describe the bug**
Using The EV3's **DriveBase** library's **drive** command, the tooltip shows "**drive_speed**" as an argument name. Upon running my script an error is generated which shows that the argument name should instead by "**speed**". After changing the argument name to "speed" the script to run correctly.

p.s. I installed pybricks-stubs 2.0.2 to get Intellisense auto-completions on my Manjaro installation.

**To Reproduce**
1. Create a DriveBase object:
`tank = DriveBase(left_motor=left_motor, right_motor=right_motor, wheel_diameter=32.6, axle_track=142)`
2. Execute a drive command with an argument named "drive_speed":
`tank.drive(drive_speed=500, turn_rate=25)`
3. An exception is generated at the drive line number:
`Starting: brickrun --directory="/home/robot/snatch3r_test1" "/home/robot/snatch3r_test1/main.py"

```
----------
Traceback (most recent call last):
  File "/home/robot/snatch3r_test1/main.py", line 30, in <module>
TypeError: 'speed' argument required
----------
Exited with error code 1.
```

**Screenshots**
![DriveBase_drive_parameter_name_error](https://user-images.githubusercontent.com/13371815/85812129-d0a35d80-b72d-11ea-9015-b29eafc8f490.png)

**Comment by dlech** [comment]
Also reported at https://github.com/pybricks/pybricks-api/issues/23

**Comment by laurensvalk** [comment]
This is fixed in https://github.com/pybricks/pybricks-api/commit/82b16dc8de8064baa1af9ca8e7adf70081f9469e. Thank you for reporting!
