### ISSUE TITLE
[Bug] Breakpoints can get caught in the wrong file by the same name

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#684]
**Describe the bug**
I've been having issues getting breakpoints to work *sometimes* for a while now. Now I might have found out why.

It seems that it sometimes gets caught in a file by the same name, if the same line number exists and is run. The latter isn't always the case, causing it to often fail silently.

When jumping to files from the terminal output, VS Code seems to have trouble dealing with files of the same name anyway (it always makes you choose), so maybe we should just rename the tests.

**To reproduce**
Nothing consistent yet.

**Expected behavior**
Breakpoint should work in the file where it was set.

**Screenshots**
This is in `lib/pbio/src/trajectory.c`, and the terminal output (not shown here) shows that the print statement hits.
![image](https://user-images.githubusercontent.com/12326241/178460092-6c7785fa-2837-4ce2-826c-3b2f043ffdbc.png)

This is in `lib/pbio/test/src/trajectory.c`
![image](https://user-images.githubusercontent.com/12326241/178460177-8f14b32b-9ba3-4822-8041-66e92be863f0.png)

**Comment by dlech** [comment]
Sounds like an issue with relative vs. absolute paths. VS Code tools seem to work better with absolute paths in my experience. But I'm not sure how to do that with makefiles without making a mess. So renaming test files to `test_xyz.c` indeed might be the quick and easy solution.
