### ISSUE TITLE
beta.pybricks.com fails to load

### ISSUE THREAD

**Issue by dlech** [pybricks/support#689]
**Describe the bug**
With the update today, https://beta.pybricks.com shows a blank page.

This only happens if you have visited the site previously.

The console log shows the following error error:

    Failed to load resource: the server responded with a status of 404 () main.01b44ba1.js:1  

**Woraround**

Refresh the page with <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>R</kbd> (<kbd>CMD</kbd>+<kbd>SHIFT</kbd>+<kbd>R</kbd> on Mac).

**Expected behavior**
Pybricks Beta should not be blank and should notify that there is an updated.

**Screenshots**
![image](https://user-images.githubusercontent.com/963645/181586203-d2404095-657f-4cc1-b747-b615e85096f2.png)

**Comment by dlech** [comment]
Looks like the problem was inadvertently introduce in https://github.com/pybricks/pybricks-code/commit/9cdd10247721d2f5544ab3e8500b1fd34e99b7c9.

**Comment by dlech** [comment]
This has been fixed in v3.2.0b3 (Pybricks Beta v2.0.0-beta.5).

But I'm going to leave the issue open for a while since people who have used older versions of Pybricks Beta will still experience this bug when upgrading to the fixed version (because the old buggy version is already on their computer).

**Comment by laurensvalk** [comment]
Not sure it is the same, but maybe this was also happening on Pybricks Code. See https://bricks.stackexchange.com/questions/17234/pybricks-on-android-tablet/17322#17322

**Comment by dlech** [comment]
This particular bug has only been released on https://beta.pybricks.com, not https://code.pybricks.com like mentioned in the stackexchange question. But the same workaround is probably still applicable.

**Comment by dlech** [comment]
I think it has been long enough now that we can close the issue.
