### ISSUE TITLE
DriveBase doc suggestions

### ISSUE THREAD

**Issue by dlech** [pybricks/support#698]
**Describe the issue**
What is wrong or unclear?

**Suggested improvement**
How can we fix it or make it clearer?

- [x] `DriveBase` class initializer: mention that wheel diameter is often printed on the side of the LEGO tire (if it says A mm x B mm, which is diameter?) and pin holes in beams are approx 8mm center-to-center in case you don't have a ruler handy, you can use that to estimate. 
- [x] The intializer API doc should also link to the "Measuring and validating the robot dimensions" section, otherwise it is easy to miss.
- [x] Methods that don't have a speed parameter should mention the `settings()` method as the way to set the speed.
- [x] The `settings()` method should mention the default values.
- [x] Methods should document possible exceptions. For example, you get a `ValueError` if the `angle` in `turn()` is too large, but what is the largest allowable angle?

**Comment by laurensvalk** [comment]
- [ ] Explain that you can change the default turning direction by reversing the left and right motor arguments.
- [ ] Consider allowing sub-millimeter (floating point) dimensions. The low-level code implicitly supports this already anyway.
- [ ] Add code examples.

**Comment by laurensvalk** [comment]
Fixed and/or deferred to separate issues as needed.
