### ISSUE TITLE
[Question] Normal Boot & Bootloader: How it works?

### ISSUE THREAD

**Issue by GianCann** [pybricks/support#70]
I'm continuing to study the Pybricks firmware and now I'm trying to understand the hub startup procedure.

(https://github.com/pybricks/pybricks-micropython/blob/master/lib/pbio/platform/cplus_hub/sys.c)

```
// Bootloader reads this address to know if firmware loader should run
uint32_t bootloader_magic_addr __attribute__((section(".magic")));
#define BOOTLOADER_MAGIC_VALUE  0xAAAAAAAA
(...)
void pbsys_reboot(bool fw_update) {
    if (fw_update) {
        bootloader_magic_addr = BOOTLOADER_MAGIC_VALUE;
    }
    // this function never returns
    NVIC_SystemReset();
}
```

My questions are:
The bootloader to flash a new firmware, is a (LEGO) firmware in another space of memory?

Where is it decided which of the two firmware (bootloader or pybricks) should be loaded?

**Comment by laurensvalk** [comment]
This appears to have been aswered. Thanks for asking!
