### ISSUE TITLE
Bluetooth question

### ISSUE THREAD

**Issue by legotronic** [pybricks/support#703]

**Comment by legotronic** [comment]
We do not connect to Bluethooth. 😣

On the hub is firmware V4.0.0.7.

We can connect to the VSC, but not to the pybricks app.

Have already tried on several computers - without success. 😒

What else can we do?

**Comment by laurensvalk** [comment]
Which hub are you using?

The EV3 is only supported in vscode.

For SPIKE and MINDSTORMS robot inventor, see http://beta.pybricks.com/

**Comment by legotronic** [comment]
> Which hub are you using?
> 
> The EV3 is only supported in vscode.
> 
> For SPIKE and MINDSTORMS robot inventor, see http://beta.pybricks.com/

We work with SPIKE - and the beta.pypricks of course.

the hub is listed in the Bluethooth overview (active) - but the pybricks app does not find any hardware.

![grafik](https://user-images.githubusercontent.com/108725396/184556390-4a3543b2-2a37-499b-ba6c-9310b0646d66.png)

It cranks endlessly - according to the picture

**Comment by dlech** [comment]
Did you install the Pybricks firmware on the SPIKE hub first?

**Comment by legotronic** [comment]
> 

We had first updated the firmware via the SpikePrime app - and then wanted to load the other firmware with the pyBrick app - but if we can't get a connection, then it's going to be difficult => chicken/egg problem.... 

Is/was our procedure wrong?

**Comment by dlech** [comment]
You have to flash the firmware using USB before connecting with Bluetooth.

<img width="300" alt="image" src="https://user-images.githubusercontent.com/963645/184665632-e1e0d34a-b566-4a38-90c8-da92ad886f6a.png">

**Comment by dlech** [comment]
You should have also seen this message when you cancel/close the Bluetooth search after not finding your hub.
<img width="706" alt="image" src="https://user-images.githubusercontent.com/963645/184666164-23c1d7ae-e97f-4cae-906d-8cbe8313ef80.png">

Did this message not appear?

**Comment by dlech** [comment]
It should appear when you cancel or otherwise close the "endless" scanning dialog.

You can use either method pictured to flash the firmware.

**Comment by legotronic** [comment]
> It should appear when you cancel or otherwise close the "endless" scanning dialog.
> 
> You can use either method pictured to flash the firmware.

Ok - we try again...

**Comment by legotronic** [comment]
so now it is also clear where the difference between the online and the offline version of the byBricks app is...  😆

**Comment by legotronic** [comment]
one last question:

 - firmware-change byBricks => check
 - beta.bypricks.com             => check
 - pybricks offline                 => Upload works => Message "new firmware version is available  => Cancel
 
 - After F5 => Error-Message "ValueError: incompatible .mpy file" => we do something wrong?
 
 
from pybricks.ev3devices import Motor
from pybricks.parameters import Port
from pybricks.tools import DataLog, StopWatch, wait

# Create a data log file in the project folder on the EV3 Brick.
# * By default, the file name contains the current date and time, for example:
#   log_2020_02_13_10_07_44_431260.csv
# * You can optionally specify the titles of your data columns. For example,
#   if you want to record the motor angles at a given time, you could do:
data = DataLog('time', 'angle')

# Initialize a motor and make it move
wheel = Motor(Port.B)
wheel.run(500)

# Start a stopwatch to measure elapsed time
watch = StopWatch()

# Log the time and the motor angle 10 times
for i in range(10):
    # Read angle and time
    angle = wheel.angle()
    time = watch.time()

    # Each time you use the log() method, a new line with data is added to
    # the file. You can add as many values as you like.
    # In this example, we save the current time and motor angle:
    data.log(time, angle)

    # Wait some time so the motor can move a bit
    wait(100)

# You can now upload your file to your computer

**Comment by legotronic** [comment]
And: VSC and pyBricks => it works...?

**Comment by laurensvalk** [comment]
> pybricks offline => Upload works => Message "new firmware version is available => Cancel
> After F5 => Error-Message "ValueError: incompatible .mpy file" => we do something wrong?

This shouldn't happen if the firmware was installed using https://beta.pybricks.com/. How did you install it?

> Create a data log file in the project folder on the EV3 Brick.  => it does'nt work for SPIKE...?!

The `DataLog` class is not available on SPIKE. If you'd like to see that supported on SPIKE one day, you could ask about it in a new issue.

**Comment by legotronic** [comment]
> > pybricks offline => Upload works => Message "new firmware version is available => Cancel
> > After F5 => Error-Message "ValueError: incompatible .mpy file" => we do something wrong?
> 
> This shouldn't happen if the firmware was installed using https://beta.pybricks.com/. How did you install it?
> 
> > Create a data log file in the project folder on the EV3 Brick.  => it does'nt work for SPIKE...?!
> 
> The `DataLog` class is not available on SPIKE. If you'd like to see that supported on SPIKE one day, you could ask about it in a new issue.
> 
> > And: VSC and pyBricks => it works...?
> 
> There are ways to do it, but we strongly recommend using https://beta.pybricks.com/


The installation of the firmware was done with https://beta.pybricks.com/ - therefore also surprised by the said message.

in fact the DataLog class is for the EV3 hardware - we overlooked that in the heat of the moment.

We would like to write log data from SPIKE - so will set a ticket accordingly. After all, we have no other way to do this.

And regarding VSC => we would like to work with versioning in the background - therefore VSC would be our preferred engineering suite. Or else pyCharme.

**Comment by legotronic** [comment]
and: Are you also familiar with this link? https://bit.ly/3pn8Euy 😲

**Comment by laurensvalk** [comment]
> ValueError: incompatible .mpy file

Does this keep happening, or did it only happen the very first time after installing the firmware?

Does it happen when you run a program via the editor, or only if you start the program with the button?

**Comment by Harry-cheong** [comment]
Hi. Is there a way to run python files on spike prime via a command line? I have tried many methods to connect the spike prime to VSC but to no avail.

**Comment by dlech** [comment]
You can run Pybricks programs on a SPIKE Prime that is running Pybricks firmware from a command line using `pybricksdev`. If you are using the official LEGO firmware on the SPIKE Prime, you will need something else.
