### ISSUE TITLE
Implementation and driverless usage of `I2cDevice`

### ISSUE THREAD

**Issue by txvvgnx** [pybricks/support#704]
**Question**
Does the usage of `I2cDevice` https://docs.pybricks.com/en/v3.0/iodevices/i2cdevice.html require the existence of an ev3dev driver for that device, or can it be used driverless? 

If it can be used driverless, how does it interact with the device? (which special files in the linux filesystem)

**Comment by laurensvalk** [comment]
It can be driverless.

- [I2CDevice class implementation](https://github.com/pybricks/pybricks-micropython/blob/master/pybricks/iodevices/pb_type_iodevices_i2cdevice.c).
- It's methods are wrappers around [this file](https://github.com/pybricks/pybricks-micropython/blob/master/bricks/ev3dev/pbsmbus.c), which in turn uses `smbus`.

If an ev3dev driver is available, you can use the [Ev3devSensor](https://docs.pybricks.com/en/v3.0/iodevices/ev3devsensor.html) class instead.
