### ISSUE TITLE
[Question] Port Configuration

### ISSUE THREAD

**Issue by GianCann** [pybricks/support#71]
I'm trying to study in depth the operation of the firmware because I'm curious to understand also the hardware part.
Reading the file https://github.com/pybricks/pybricks-micropython/blob/master/lib/pbio/platform/cplus_hub/platform.c I would like to ask why PC12 and PB12 are put on high level.

    // Keep main power on (PC12)
    gpio_init.Pin = GPIO_PIN_12;
    gpio_init.Mode = GPIO_MODE_OUTPUT_PP;
    HAL_GPIO_WritePin(GPIOC, GPIO_PIN_12, GPIO_PIN_SET);
    HAL_GPIO_Init(GPIOC, &gpio_init);

    // Turn VCC_PORT on (PB12)
    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_12, GPIO_PIN_SET);
    HAL_GPIO_Init(GPIOB, &gpio_init);

**Comment by laurensvalk** [comment]
This has been answered, so we can close the issue.
