### ISSUE TITLE
[Feature] Add short sha to CI build artifact name

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#712]
Like https://github.com/pybricks/pybricks-micropython/commit/37e69699507fce28a89bdb155d1496446729be75, but also add the short hash.

``${{ github.sha }}`` is available, but that's too long. [A shorter version could be done like this.](https://stackoverflow.com/questions/59810838/how-to-get-the-short-sha-for-the-github-workflow)

**Is your feature request related to a problem? Please describe.**

Users are now reporting build numbers to report versions, but this means developpers have to dig through the actions or artifacts to find out which commit this belongs to. It would be nice to have a short sha appended as well.

It also makes it easy for the user to verify that installing was successful because they can compare it against `pybricks.version`.

**Comment by dlech** [comment]
If we are going to do that, we might as well scrape the entire firmware version from `bricks/${{ matrix.hub }}/build/genhdr/mpversion.h `
