### ISSUE TITLE
[Report] Flashing CityHub successful

### ISSUE THREAD

**Issue by GianCann** [pybricks/support#72]
After some problems in setting up the work environment, I managed to compile and load the firmware for the CityHub.

The working environment is Ubuntu 18.04, running in Virtualbox on Windows 10.

I noticed that pairing with code.pybricks.com does not happen if the Hub has a connected device.
You have to do the pairing first, and then connect the motor.

**Comment by laurensvalk** [comment]
Please post all new issues in `support`. We reserve the other issue trackers for actual bug reports that need to get fixed.

That makes it easier for us to know what to fix.

Thanks!

**Comment by laurensvalk** [comment]
> I noticed that pairing with code.pybricks.com does not happen if the Hub has a connected device.
You have to do the pairing first, and then connect the motor.

If you find this to happen consistently, please do open an issue for that as well. Nice find!
