### ISSUE TITLE
Can you uninstall The firmware that the app flash on to the brick?[Question] 

### ISSUE THREAD

**Issue by luke-e-gibson-1** [pybricks/support#720]
**Question**

Can you uninstall The firmware that the app flashes onto the brick?
if I don't want the pybrick firmware any more?

**Comment by luke-e-gibson-1** [comment]
I found a way to reflash with lego firmware here in this articale https://www.eurobricks.com/forum/index.php?/forums/topic/179604-how-did-you-fix-your-technic-hub-firmware-being-updated-every-time/

**Comment by laurensvalk** [comment]
> **Question**
> 
> Can you uninstall The firmware that the app flashes onto the brick? if I don't want the pybrick firmware any more?

If anyone else is looking for this in the future, this is also covered on the installation instructions: https://pybricks.com/install/technic-boost-city/#restoring-the-original-firmware
