### ISSUE TITLE
[LOW-PRIORITY] [Doc] Action buttons are too big

### ISSUE THREAD

**Issue by tiagorangel2011** [pybricks/support#726]
**Describe the issue**
The blue action buttons at the top are to big.

**Suggested improvement**
Make them smaller.

**Comment by laurensvalk** [comment]
Could you add some information about your setup? What kind of device do you use? How big is the screen? Do you use an on-screen keyboard?

**Comment by tiagorangel2011** [comment]
Hi! I'm currently using Windows 11 on a laptop, but I think this happens on
any computer.
You can find my browser details at https://whatismybrowser.com/w/5Y7ERX2

> Message ID: ***@***.***>
>

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
09/25/22,
11:24:26 AM

**Comment by dlech** [comment]
Why do you think they are too big? Is it just aesthetics or is it causing a problem?

**Comment by tiagorangel2011** [comment]
Ha, It's not causing any problems! 🤣 The only thing about it is that it
minimizes the coding area and it's a little difficult to concentrate. I
have marked this as low-priority

**Comment by dmusican** [comment]
Yes, this is fantastic, thank you! I'll open this up in a new issue.
