### ISSUE TITLE
[Bug] Bluetooth status

### ISSUE THREAD

**Issue by GianCann** [pybricks/support#74]
**Describe the bug**
The Bluetooth button on "Pybricks Code" lost the actual status

**To reproduce**
1. Go to code.pybricks.com
2. Click on Bluetooth button
3. Connect with smart hub
4. Run some code...
5. Now, refresh the page
6. the Bluetooth button is now in the "not connected" status.
7. If you click again on the button, you see the hub already paired.

![IMG_20200630_090746](https://user-images.githubusercontent.com/45897944/86096395-81ee1e80-bab3-11ea-988d-222a14095a32.jpg)

8. You have to click to again on "Pairing" (Accoppia, in Italian) to get the hub works.

**Expected behavior**
Maintaining the Bluetooth "connection" status, across refreshing the page

**Comment by laurensvalk** [comment]
It is expected that refreshing causes the hub to disconnect. Think of it like restarting the Powered Up app - then it disconnects too.

Please note that paired does not mean connected. Paired just means it is in your computer's "address book", usually because you've connected to it before.

**Comment by GianCann** [comment]
Thank you @laurensvalk  for the clarification
