### ISSUE TITLE
[Feature] Include Displayed Image and runtime since program start in SPIKE Prime decoded data

### ISSUE THREAD

**Issue by PhoBricks** [pybricks/support#76]
**Is your feature request related to a problem? Please describe.**
If a program is running on the SPIKE, the output uses also the last two values, it would be great to integrate them also into the connection.py 

**Describe the solution you'd like**
Example Output:
{"m":0,"p":[[0, []], [0, []], [0, []], [0, []], [0, []], [0, []], [-9, -4, 988], [-1, 5, 0], [-1, 0, 0], "09090:99999:99999:09990:00900", 5005]}}
Actual Displayed Image->"09090:99999:99999:09990:00900"
Runtime in ms since program start -> 5005

**Describe alternatives you've considered**
-
**Additional context**
-

**Comment by laurensvalk** [comment]
Closing and merging this with #75.
