### ISSUE TITLE
[Bug] Use correct scale for hub renders in Pybricks Code

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#773]
**Describe the bug**
The hub pictures render at a different scale.

![image](https://user-images.githubusercontent.com/12326241/199715518-0906c49b-25f3-4059-9810-5fa0b3e99c09.png)

**Suggested fix**
We could render the images with a fixed width or height so we don't have to make it complicated in Pybricks Code.

**Comment by dlech** [comment]
> We could render the images with a fixed width or height so we don't have to make it complicated in Pybricks Code.

Would you mind doing this? The app is currently scaling them to 64x64 pixels.

**Comment by laurensvalk** [comment]
Yeah, was already working on it, forgot to assign.

I'll just make them square.

We can export at 64x64 if you like as well, or anything else for that matter. I'll have a look at what comes out right.

**Comment by dlech** [comment]
> If we find that the relative scale makes the small hubs look too small, I propose to scale down only Move Hub.

Currently looks like this (for anyone that wants to share their opinion):
![image](https://user-images.githubusercontent.com/963645/200635954-78b28339-0658-4030-88ed-54979df3e31e.png)

**Comment by laurensvalk** [comment]
Hopefully this helps a bit, otherwise feel free to re-open.
