### ISSUE TITLE
[Feature] Replace documentation toggle with icon on left menu bar.

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#778]
This was suggested by @botbench.

**Is your feature request related to a problem? Please describe.**
It takes a couple of clicks to toggle the docs, and you end up with the settings menu left open.

![image](https://user-images.githubusercontent.com/12326241/200173333-344d93eb-71cd-4bc4-8874-b9eb4fccd923.png)

**Describe the solution you'd like**
Remove it from the settings menu. Instead, add an icon on the left bar (e.g a book) to toggle it.

**Additional context**
The documentation toggle stems from the Pybricks 3.0 release where we did not yet have the menu.

**Comment by dlech** [comment]
There is already a keyboard shortcut to toggle the docs without having to open the settings.
