### ISSUE TITLE
Documentation not showing correctly on IntelliJ

### ISSUE THREAD

**Issue by laviRZ** [pybricks/support#788]
I'm not sure whether it's a pybricks or an IntelliJ problem, but only the parameters of the documentation shows when hovering over a function name.
![image](https://user-images.githubusercontent.com/29277997/201296341-a249555f-ea6b-4932-8a5e-0a99818c1f20.png)
![image](https://user-images.githubusercontent.com/29277997/201296411-49e285fa-2dde-4ec9-878a-f5eef0e4a36e.png)

**Comment by dlech** [comment]
> IntelliJ

Isn't this a Java IDE? So I wouldn't expect it to work with Python. Or do you mean PyCharm? As far as I know, documentation follows Python standards and is picked up by Pyright/Pylance and Jedi so if it isn't getting picked up, it seems likely to be a problem with the IDE or whatever static analysis tool it uses.

**Comment by laviRZ** [comment]
Nope, IntelliJ
They allow working with python with a plugin that makes it behave
functionally the same to PyCharm.

**Comment by dlech** [comment]
Closing since we don't officially support IntelliJ/PyCharm.

Happy to answer additional questions at https://github.com/orgs/pybricks/discussions or review a pull request https://github.com/pybricks/pybricks-api to improve compatibility.
