### ISSUE TITLE
remote not paring to hub after latest update

### ISSUE THREAD

**Issue by tdamsma** [pybricks/support#793]
After running the recommenced firmware update on my boost hub  today on the beta channel I couldn't get the remote to pair. It did work before  (on the beta channel), but now I had to revert to stable to get it working again.

**Comment by dlech** [comment]
Can you please share the exact firmware version and an example program to reproduce the problem?

**Comment by tdamsma** [comment]
The firmware is whatever is pushed as latest on beta.pybricks.com as of today. The example program to reproduce is just call `Remote()` to initiate a pairing. I tried also with `Remote(timeout=None)` and that was just stuck.

**Comment by dlech** [comment]
We just published a new version today, so depending on what time of day it could be a different firmware version. So without an exact version number, we can only guess which version is being used. You can find the version here:
![image](https://user-images.githubusercontent.com/963645/201416347-e1e9a5ed-5131-4d6d-ae2b-95118b1ebd26.png)

 or `from pybricks import version; print(version)`.

With Pybricks firmware v3.2.0b5 on a Technic hub and the hub connected to Pybricks Beta on Linux, I am able to get the remote connected to the hub.

Which hub and operating system are you using? Do you turn on the remote before of after you start the program on the hub?

**Comment by dlech** [comment]
Oops, I should read more carefully, I see that you said the BOOST Move hub already.

**Comment by dlech** [comment]
I'm able to reproduce the problem with a move hub, so we will look into it.

**Comment by dlech** [comment]
It appears to be working when not connected to Pybricks Beta:

Steps:
- download and run program with Pybricks Beta (doesn't work but needed to copy program to hub)
- disconnect hub from Pybricks Beta
- press button on hub to start program
- press button on remote to connect remote

```python
from pybricks.hubs import MoveHub
from pybricks.pupdevices import Motor, ColorDistanceSensor, Remote
from pybricks.parameters import Button, Color, Direction, Port, Stop
from pybricks.robotics import DriveBase
from pybricks.tools import wait, StopWatch

hub = MoveHub()

remote = Remote()

hub.light.on(Color.GREEN)
remote.light.on(Color.GREEN)

while True:
    print(remote.buttons.pressed())
    wait(1000)
```

**Comment by dlech** [comment]
Found and fixed the problem. You can use [this firmware](https://github.com/pybricks/pybricks-micropython/suites/9262937254/artifacts/433639636) until the next beta release.

**Comment by tdamsma** [comment]
Well that was quick! Won't be able to test until Monday
