### ISSUE TITLE
[Feature] Access RSSI (Received Signal Strength Indicator) from nearby hubs (or other devices)

### ISSUE THREAD

**Issue by pbochynski** [pybricks/support#801]
The recent [implementation of broadcast](https://github.com/pybricks/pybricks-micropython/pull/80) gives access to advertising data from nearby devices. It would be great if I could access the latest RSSI data from discovered devices. 

Usually, there is plenty of BLE devices around, so reading should be limited to subscribed names/ids. Alternatively, we could get RSSI data along with `Broadcast.receive`.

I know that RSSI data is not accurate and can be distorted by absorption, interference, or diffraction but could be used to calculate a distance from another hub or device. My idea is to build a return-to-home function or even a kind of indoor navigation using triangulation (3+ devices nearby).

**Comment by laurensvalk** [comment]
Thanks for opening this issue. I was chatting about this with @nstrijbosch last week.

We thought it might be useful to add an `info(topic)` method to get additional info about signals. This could perhaps return a tuple or dictionary of:

- RSSI
- Timestamp (so you can choose to ignore old messages)
- Received counter
- Anything else?

A single `info()` method is still fairly minimal and would keep the `receive` API simple.

**Comment by pbochynski** [comment]
Yes - info method would be perfect.

**Comment by NStrijbosch** [comment]
https://user-images.githubusercontent.com/67324303/208315652-74a0d290-aa9a-446d-ac63-b029bbe3e3d0.mp4

A quick test where the inventor hub reads the RSSI value corresponding to the advertising data of the technic hub. It could be pretty usable to distinguish between being close or far away. The values do not seem stable enough such that they can be used to estimate distance.

**Comment by laurensvalk** [comment]
Awesome!

Good use for the tiles :smile:

**Comment by NStrijbosch** [comment]
> It could be pretty usable to distinguish between being close or far away. The values do not seem stable enough such that they can be used to estimate distance.

To visualize this argument a plot of the distance vs RSSI value. This was an experiment with a city hub that advertises data and a primehub that measures the distance with the UltrasonicSensor and reads the RSSI values:
![RSSI_distance_Prime_measuring_City_hub](https://user-images.githubusercontent.com/67324303/209682073-5b7ffab2-9a99-40d8-b910-e27240e9970f.png)

**Comment by pbochynski** [comment]
Definitely, it is not accurate, but the trend is visible. I think it still can be useful for larger distances and slow movements. I mean aggregating several measurements, e.g. min(RSSI) of 10 measurements should give better estimates (like <0.5m, ~1m, ~2m, >3m). Thanks for updating the PR - I will do some experiments with it.

**Comment by dlech** [comment]
Another alternate with an API to get RSSI is at https://github.com/pybricks/pybricks-micropython/pull/158.
