### ISSUE TITLE
pybricks.eth button in sponsors dialog does nothing

### ISSUE THREAD

**Issue by dlech** [pybricks/support#806]
**Describe the bug**
There is a `pybricks.eth` button in the sponsors dialog, but clicking it does not do anything.

**To reproduce**
1. Go to beta.pybricks.com
2. Click on the heart icon
3. Click the pybricks.eth button
4. Nothing happens

**Expected behavior**
It should link to an external page like the other buttons.

**Screenshots**
![image](https://user-images.githubusercontent.com/963645/202781360-0ecec184-3cbc-45a8-a35a-b32bee83a3dc.png)

**Comment by laurensvalk** [comment]
This was intentional. It's really just intended as an option for people who know how this works.

It doesn't need to be a button actually.

But if we want to make it nicer, we could make it copy that domain name to the clipboard.

**Comment by dlech** [comment]
It would be nice if it linked to a page or had a pop up that explained what it is for those who don't know how it works.
