### ISSUE TITLE
[Doc] Link DFU page to Pybricks Code

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#815]
Once Pybricks Beta moves over to Pybricks Code, we won't need https://dfu.pybricks.com/ anymore.

But the page seems to be used more than anticipated. I've seen posts like these on more than one occasion: 
https://www.facebook.com/groups/mindstormsrobotinventor/posts/877148313298124/

Instead of removing it altogether, maybe we could leave a few lines of instructions on how to accomplish recovery with Pybricks Code.

**Comment by dlech** [comment]
This has been completed.
