### ISSUE TITLE
Raising SystemExit in user program prints "Stop button pressed"

### ISSUE THREAD

**Issue by dlech** [pybricks/support#836]
**Describe the bug**
When an uncaught `SystemExit` is raised in a user program, "Stop button pressed." is printed to stdout even if the source of the `SystemExit` was not the stop button.

**To reproduce**

Firmware v3.2.0b6-5-g45cc21fe.

1. Create a program with the single line `raise SystemExit`.
2. Run the program on a hub using Pybricks Code.
3. Observe the output in the terminal pane.

**Expected behavior**
The hub should only report that the stop button is pressed if the button on the hub or the stop button in Pybricks code was pressed.

**Comment by laurensvalk** [comment]
If we want to keep this simple, we could just make it say: 

```
The program was stopped (SystemExit)
```
