### ISSUE TITLE
Compatibility icons don't scale well for narrow-width docs

### ISSUE THREAD

**Issue by dlech** [pybricks/support#838]
As seen in the screenshot, when the docs are viewed on a narrow-width frame, the compatibility icons become too small to see clearly.

![image](https://user-images.githubusercontent.com/963645/206305436-f9ab5c3d-435f-4c88-8da7-dc5e66f9d3e8.png)

To make it more clear, the checkmark or exmark should be nearly as large as the entire image.

The images completely disappear when the docs are too narrow.
![image](https://user-images.githubusercontent.com/963645/206306589-01e22db7-2e79-4e9a-9187-78e529ccc720.png)

**Comment by laurensvalk** [comment]
Now I just need a way to get the css right to get some padding on the background image.

**Comment by laurensvalk** [comment]
End result:

![image](https://user-images.githubusercontent.com/12326241/206649185-1df44ec2-c8d5-4e40-abb9-9117fd302f62.png)

small screen:


![image](https://user-images.githubusercontent.com/12326241/206649150-190a5437-6f21-4761-aee2-6c9c772e2fbe.png)
