### ISSUE TITLE
images are skeqwed on small screens in documentation

### ISSUE THREAD

**Issue by dlech** [pybricks/support#844]
When viewed on a narrow screen, some images in the docs get skewed so that the image looks distorted

normal
![image](https://user-images.githubusercontent.com/963645/206527753-837244a6-ece8-4bf8-b435-63708ac700ca.png)

squished
![image](https://user-images.githubusercontent.com/963645/206527990-8149290b-7015-4dd0-9363-d6aea68e78b1.png)

We probably need to figure out some sort of responsive styling so that the width and height are scaled proportionally.

**Comment by laurensvalk** [comment]
It doesn't happen on all images. I have a hunch it only happens on images where we specified the height. We don't actually need to do that (anymore). So we may be able to fix it by just using width everywhere.

**Comment by laurensvalk** [comment]
Yep:

```
.. figure:: ../../main/cad/output/hub-spike-inventor.png
    :height: 15 em

.. figure:: ../../main/cad/output/hub-spike-inventor.png
    :width: 75%
```

 
![image](https://user-images.githubusercontent.com/12326241/206542736-e03cb4c3-c945-46f5-9cb1-9ed750a5916d.png)
