### ISSUE TITLE
[Feature] Rename app description in meta data

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#845]
**Is your feature request related to a problem? Please describe.**

When sharing a link to Pybricks Code you usually get a preview like this:

![image](https://user-images.githubusercontent.com/12326241/206549693-e90024bd-f3f3-45ca-a163-ab56f6c29afc.png)

But not everyone knows what Powered Up and perhaps IDE means. It is not well known that Powered Up also spans SPIKE and MINDSTORMS.

**Describe the solution you'd like / ideas**

Pybricks: MicroPython coding for LEGO® hubs.

MicroPython coding for LEGO® hubs.

MicroPython coding for robotics.

**Comment by dlech** [comment]
For facebook we can add open graph tags: https://developers.facebook.com/docs/sharing/webmasters#markup
