### ISSUE TITLE
[Bug] UART sensor issues with hub-to-hub communication demo firmware

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#850]
> Great idea and it works! Thank you for this ingenious solution!
I tried it on several hub configurations. The broadcast frequency is suitable for real-time vehicle control when both hubs are disconnected from PC. I've built a holonomic platform with RI Hub, controlled by a Technic Hub with an angular motor connected. All three control parameters (drive, side, turn) are transferred and interpreted with minimal latency.
Unfortunately Color & Distance Sensor 88007 is not really supported by this experimental firmware. Especially if two of them are connected to the same hub. With this built-2178 firmware initializing the second 88007 sensor hangs up the code execution without error message. At this point the hub enters a somewhat critical state: steady blue light, and after pressing hub button, light begins blinking at 4-5Hz and hubs become fully unresponsive, only removing battery helps. This can happen as well when having only one 88007 sensor connected, or sometimes code execution becomes buggy, interrupted with various and irrelevant error messages (syntax error on simple motor commands like motor.run(speed) that runs correctly on current beta firmware).
It-s a pity, given the great usability of this really cheap and versatile sensor (3 operating modes!)
It would be very useful to include this experimental Broadcast in the current beta versions or even release candidates for offering an alternative until true hub-to-hub communication will be implemented.

_Originally posted by @vardayzsolt in https://github.com/pybricks/pybricks-projects/commit/5e8fd75f7e21f19a1a10ddffbb553ed9631a25b1#commitcomment-92717448_

**Comment by laurensvalk** [comment]
Thanks for sharing your findings!

This may be something we'll explore for future releases. See also #262.

> It would be very useful to include this experimental Broadcast in the current beta versions or even release candidates for offering an alternative until true hub-to-hub communication will be implemented.

I think you have just found out why we don't include it in the beta firmware just yet :)

**Comment by NStrijbosch** [comment]
@vardayzsolt can you share a short code snippet to reproduce your issue?
I just tried to reproduce your issue with two ColorDistanceSensors connected to port A and port B on the TechnicHub and PrimeHub and did not have any issues. 

Are you experiencing this issue with the Technic Hub with the sensor connected to Port D? In this experimental build this port is still used for debugging and therefore not usable for sensors/motors.

**Comment by vardayzsolt** [comment]
> In this experimental build this port is still used for debugging and therefore not usable for sensors/motors.

That's it! When I unplugged drive motor from Port D and bypassed drive motor references in code everything worked as expected. Here you have both programs: the one with self-driving rc car with all ports used, causing unresponsive hub; and the one with unused Port D and no drive motor connected.
[rccar_test.ZIP](https://github.com/pybricks/support/files/10304830/rccar_test.ZIP)

It would be very useful to mention this port usability limitation for technic hubs in the Hub-to-Hub communication by BT Broadcasting Tutorial. Do we have similar port limitations due to port reservation for debugging on other hubs as well?

**Comment by vardayzsolt** [comment]
I tried and found no port-limitation on City-hub, both ports have normal functionality with built-2178 experimental firmware.
Would you please make available all four ports on Technic-hub as well in an updated version of this firmware? Or just implement in current beta version the Broadcast class from pybricks.experimental? Thanks!
