### ISSUE TITLE
[Bug] Pybricks Code connection gets stuck halfway

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#851]
**Describe the bug**
Quite frequently my hub (Prime/Technic) gets through the initial connection phase only partially.

The hub light turns solid blue (indicating a connection), but the Play/REPL buttons remain disabled.

Then I try to connect again with the Bluetooth Button. The hub shows up there as "paired". This isn't supposed to work, but connecting to that usually does make it work (?).

**To reproduce**
I don't know yet.

I'm using Ubuntu 22.04 with Google Chrome.

**Comment by laurensvalk** [comment]
This was also reported by @mattytrentini.

**Comment by laurensvalk** [comment]
This also happens on Windows.

**Comment by laurensvalk** [comment]
it can also get stuck in this state, possibly different issue.

![image](https://user-images.githubusercontent.com/12326241/207075703-43b73711-ea90-4d81-8589-51b3650251fe.jpg)

**Comment by dlech** [comment]
Anything in the Chome console? Wireshark logs?

**Comment by dlech** [comment]
does this still happen?

**Comment by laurensvalk** [comment]
I think so, occasionally.

**Comment by laurensvalk** [comment]
I haven't seen this happen in a long time, so let's close this.
