### ISSUE TITLE
[Bug] Pybricks Code can get stuck in infinite connection loop

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#852]
This doesn't seem to be entirely fixed.

https://user-images.githubusercontent.com/12326241/207012280-e791a11d-2b33-4600-85f6-62172cfb5b11.mp4

This is on Ubuntu 22.04 with Pybricks Code V3.2-c1. I don't have logs yet.

> Getting out of the infinite loop in Pybricks Code might be worth doing though?

_Originally posted by @laurensvalk in https://github.com/pybricks/support/issues/600#issuecomment-1287484792_

**Comment by laurensvalk** [comment]
This might also be due to #849.

**Comment by dlech** [comment]
Is there a reproducible test case or can we close this one?
