### ISSUE TITLE
[Feature] code.pybricks.com enhancement

### ISSUE THREAD

**Issue by GianCann** [pybricks/support#87]
I suggest this enhancement:

- "Clear terminal" button: to delete all the text in the terminal windows.

- "Add to snippet" button: to add a selected text in the editor to the snippets library

- "Change editor font size" setting: to change the font size of the editor

**Comment by laurensvalk** [comment]
To change the font size, zoom in/out using the usual ctrl +/- or ctrl scroll.

**Comment by Nelvarion** [comment]
I'd love the ability to copy from the terminal frame.

**Comment by dlech** [comment]
> I'd love the ability to copy from the terminal frame.

This works already. Try click-and-drag to select and then right-clicking to get a menu.

**Comment by Nelvarion** [comment]
> > I'd love the ability to copy from the terminal frame.
> 
> This works already. Try click-and-drag to select and then right-click to get a menu.

Ctrl+Shift+C it is!

**Comment by dlech** [comment]
I split this into one issue per suggestion. #103, #104
