### ISSUE TITLE
Motor(Port.D) freezes hub. (technic hub running hub to hub experimental firmware on beta.pybricks.com)

### ISSUE THREAD

**Issue by AngusCrump** [pybricks/support#871]
**Describe the bug**
What is the problem?
Initialising port D as motor causes hub to freeze.

**To reproduce**
Run any code with Motor(Port.D) in it, or run Motor(Port.D) in REPL.

**Expected behavior**
What did you expect to happen instead?
Port D is Initialised as a motor.

**Screenshots**
Here you can see that after entering the command, the REPL stops but the bluetooth stays connected (you can't see the blinking cursor but it is on the line under the command).
<img width="1800" alt="Screenshot 2022-12-22 at 11 54 28 am" src="https://user-images.githubusercontent.com/121205522/209032149-c42e5be1-cdb9-4acc-8aa7-0db9e3b6c02b.png">

This is what happens to the hub after entering the command, or when it tries to run it in a program:
https://user-images.githubusercontent.com/121205522/209032635-7a92e71f-c66f-4de6-88a5-d93e8bf32d2d.mp4
The only way you can do anything else with the hub afterwards is taking out the batteries and putting them back in again.

Before anyone asks, no, this does not happen on any of the other ports, and yes i have done the exact same thing on another technic hub with the exact same results.

**Comment by dlech** [comment]
I see you are using a custom firmware v3.2.0b4-58-g84e5308d. I'm guessing this is the experimental Bluetooth hub-to-hub firmware. It has port D disabled for debugging.

**Comment by AngusCrump** [comment]
Ah, I see. I'm using the bluetooth hub to hub but I could probably find a workaround. The hub to hub communication works very well, do you have any idea when it will come out in an offical release?

**Comment by dlech** [comment]
We don't have an exact timeline right now.
