### ISSUE TITLE
Use named tuples for limits and settings.

### ISSUE THREAD

**Issue by dlech** [pybricks/support#883]
**Is your feature request related to a problem? Please describe.**
It is not very clear that `Motor.control.limits()[2]` is the `torque` limit.

**Describe the solution you'd like**
If we create a named tuple for this, we could write `Motor.control.limits().torque` instead (without breaking existing code).

**Describe alternatives you've considered**
As a workaround, we can create a local constant for the index.

```python
TORQUE = 2

m = Motor(...)
print(m.control.limits()[TORQUE]
````

**Additional context**
We could make this optional and exclude it on move hub to save firmware size.

**Comment by laurensvalk** [comment]
The recommended way to read these settings currently is:

```python
speed_limit, acceleration, torque_limit = motor.control.limits()
```

**Comment by dlech** [comment]
That doesn't really work for cases like this:

```python
sum([m.control.limits()[2] for m in motors])
```

**Comment by laurensvalk** [comment]
In regards to the recommended usage, perhaps we can make the signatures clearer like this.

Current:

![image](https://user-images.githubusercontent.com/12326241/209449768-12d9c657-1d26-4f28-8894-c9d75ba7a31d.png)


idea:

![image127](https://user-images.githubusercontent.com/12326241/209449913-6250ac8b-4685-4c56-a601-f4d393bdde8a.png)

**Comment by laurensvalk** [comment]
> That doesn't really work for cases like this though:
> 
> ```python
> sum([m.control.limits()[2] for m in motors])
> ```

I would argue this to be a fairly advanced use case. The main uses of these methods is setting values to improve defaults.
