### ISSUE TITLE
[Question] Exit from program

### ISSUE THREAD

**Issue by GianCann** [pybricks/support#90]
I see there is not present the 'sys' module, so it's not possibile to use the sys.exit() function to exit from the program.

I can use `raise RuntimeError("Closing program..")`.

Is this correct to do?
There is a better method for "close" a program?

**Comment by dlech** [comment]
`raise SystemExit` is the same as `sys.exit()`

This might even print the message.

    raise SystemExit("Closing program..")

**Comment by laurensvalk** [comment]
This looks to be resolved, so closing.
