### ISSUE TITLE
Robot Inventor Hub refuses to connect to pybricks app to install firmware

### ISSUE THREAD

**Issue by ODog2028** [pybricks/support#905]
I am trying to install the pybricks firmware on my robot inventor hub but I get an error when connecting the hub to the software. The error I get is:
```
Error: Failed to execute 'open' on 'USBDevice': Access denied.
```

**Comment by dlech** [comment]
What operating system?

**Comment by dlech** [comment]
How are you trying to flash the firmware?

**Comment by ODog2028** [comment]
I am using ChromeOS and I have tried from both code.pybricks.com and dfu.pybricks.com but got the same error.

**Comment by ODog2028** [comment]
I have figured out the issue and I uploaded the firmware!

**Comment by laurensvalk** [comment]
Glad to hear it worked. What was the issue?

**Comment by ODog2028** [comment]
ChromeOS was trying to give access to the hub to android and chrome at the same time.

**Comment by laurensvalk** [comment]
Thanks! That helps clear it up in case anyone with the same issue finds this later.

Have fun coding now :)

**Comment by ODog2028** [comment]
Thanks!
