### ISSUE TITLE
[Bug] Horizontal scrollbar in sample code not visible unless vertically scrolled to bottom.

### ISSUE THREAD

**Issue by davecparker** [pybricks/support#907]
In the Samples/Tutorials, in the code samples, the horizontal scrollbar is not visible or usable unless the code sample is also scrolled vertically to the bottom, making it not possible to see cut-off lines in the middle of the program.

**To reproduce**
For example, 
1. (I am using Chrome or Safari on Mac)
2. Open the Quick Reference for Robot Inventor (https://pybricks.com/projects/sets/mindstorms-robot-inventor/other-models/quick-reference/)
3. Look through the program code
4. See that you cannot use the horizontal scrollbar until vertically scrolled to the bottom.

** Expect **
Scrollbar should always be visible and usable. 
I will also suggest a wider display area overall to minimize scrolling in a separate issue.

**Screenshot**
<img width="724" alt="Screen Shot 2023-01-10 at 8 19 20 AM" src="https://user-images.githubusercontent.com/14863546/211605154-5cc1d4da-99c0-4730-b2f2-d1c46ba93420.png">

**Comment by dlech** [comment]
> I will also suggest a wider display area overall to minimize scrolling in a separate issue.

FYI, we already had this discussion when we started the site. The resolution was that we should wrap code at 70 columns so that it fits the current width without having to scroll horizontally.
