### ISSUE TITLE
[Bug] hub.imu.heading() is not implemented

### ISSUE THREAD

**Issue by davecparker** [pybricks/support#912]
Just a friendly reminder that hub.imu.heading() is not yet implemented, and putting this issue here so that I can add heading() and reset_heading() to the quick reference sample when they arrive.

**Comment by laurensvalk** [comment]
See also https://github.com/pybricks/pybricks-micropython/pull/135 for a possible contribution.

**Comment by laurensvalk** [comment]
This is continued in https://github.com/pybricks/support/issues/989, so closing this.
