### ISSUE TITLE
[Feature] Jump to file and/or line on syntax error

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#924]
**Is your feature request related to a problem? Please describe.**
When compilation fails due to an error in an included module, focus stays in the main program.

**Describe the solution you'd like**
It would be nice if it opened the failed program, possibly with the cursor at (technically, just _near_) the problem.

I suppose this could be difficult if the file is already open in another window. In that case maybe don't try to jump.

**Screenshots**
![image](https://user-images.githubusercontent.com/12326241/214378600-3a33a278-565b-48b7-bb61-73c5c3b4d87f.png)

**Comment by dlech** [comment]
This works as expected for me as long as the file is not open in another window. In that case, we should show an error.
