### ISSUE TITLE
[Bug] Acceleration and angular velocity garbage data

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#932]
**Describe the bug**
Something seems to have gone wrong with some of the changes in https://github.com/pybricks/pybricks-micropython/pull/140

**To reproduce**

My hub is stationary, so these values are wrong:

```
>>> hub.imu.acceleration() / 9810
Matrix([
    [  -1.682],
    [  -3.810],
    [  -0.437],
])
>>> hub.imu.angular_velocity()
Matrix([
    [ -35.805],
    [-680.960],
    [ -44.765],
])
```
**Expected behavior**
Acceleration magnitude about 9810, gyro about 0 when stationary.

**Comment by laurensvalk** [comment]
This was introduced in https://github.com/pybricks/pybricks-micropython/commit/5942831fb45b906658cb4978dbac1c70d3daeda8, reverting works around it.

**Comment by dlech** [comment]
Oh dear. I was working on it so long, by the end I was probably just seeing that the numbers were changing and not looking at the actual values. :disappointed:

**Comment by dlech** [comment]
Apparently, this is working correctly on the Technic hub but not on the SPIKE Prime hub.

**Comment by dlech** [comment]
It turns out that MicroPython has a quite old STM32F4 HAL (with bugs that have since been fixed upstream) but a newer STM32L4 HAL which is why it worked on Technic hub but not SPIKE.
