### ISSUE TITLE
The editor does not type properly on a Tablet or Mp[Bug] 

### ISSUE THREAD

**Issue by davek61** [pybricks/support#934]
When using the Python editor on a Tablet or Mobile Phone the letters do not appear properly but rather appear to be overlaid on top of themselves.  It can usually be rectified but often additional characters are left on the line.  This is only an issue on a Tablet or Phone.
Because of the nature of this bug it is not possible to provide a screen shot example.

**Comment by davek61** [comment]
When using the Python editor on a Tablet or Mobile Phone the letters do not appear properly but rather appear to be overlaid on top of themselves.  It can usually be rectified but often additional characters are left on the line.  This is only an issue on a Tablet or Phone.
Because of the nature of this bug it is not possible to provide a screen shot example.

**Comment by dlech** [comment]
When you say "Python editor", I assume you mean https://code.pybricks.com?

I've noticed this issue too on my Android 12 phone. I think this has to do with the automatic completion of the keyboard in Android. If I switch to a different keyboard like [this one](https://play.google.com/store/apps/details?id=com.gazlaws.codeboard) the problem goes away.

**Comment by dlech** [comment]
![Screenshot_20230203-152050.png](https://user-images.githubusercontent.com/963645/216713483-607f29ff-7cf0-4312-b8b4-ac6d1059c1ab.png)

Here is a screenshot showing a missing "r" in "run".

**Comment by davek61** [comment]
Hello David,

Thank you very very much for your prompt response and really useful support
information.
I tried that keyboard and it works fine on my phone too now.

This is really helpful and will mean that I can use cheap tablets for
students using Pybricks.

I donated some money to Pybricks yesterday and it was definitely money well
spent! :-)

Kind regards,

David Kempton

**Comment by dlech** [comment]
I think the actionable item here is to document the recommendation of https://play.google.com/store/apps/details?id=com.gazlaws.codeboard for Android when an external keyboard is not available.

Info could go in the same place as #921.
