### ISSUE TITLE
[Doc] pybricks python package - stubs usage

### ISSUE THREAD

**Issue by kai-morich** [pybricks/support#937]
I succesfully installed latest pybricks on EV3 with the help of #648.
To have python stubs in vs-code I initially used the `pybricks-stubs` package, but that does only documents v2.0.

Later I found out, that `pybricks` package is even better, but
- it is only mentioned in the title, that it can be used for that purpose, not in the body, so I missed it.
- should be mentioned, that syntax highlighting has to be enabled in the generated projects by removing the `"python.languageServer"="None"` line in `.vscode/settings.json`

Should i make a PR on https://github.com/pybricks/pybricks-api/blob/master/README.rst ?

**Comment by dlech** [comment]
Yes, always happy to have someone else do the work. 😄
