### ISSUE TITLE
[Bug] Pybricksev flashing not working?

### ISSUE THREAD

**Issue by Vinz1911** [pybricks/support#973]
**Describe the bug**
Currently im struggling with flashing firmwares using pybricksdev. Am I missing here something? I'm using the latest version:
`pybricksdev v1.0.0a38`
See image below 

**To reproduce**
Flash image using pybricksdev

**Expected behavior**
that it works

**Screenshots**
<img width="704" alt="pybricks-flash" src="https://user-images.githubusercontent.com/21056653/223195065-a179ac33-c72b-4eae-a712-11355526f655.png">

**Comment by dlech** [comment]
Operating system?

**Comment by dlech** [comment]
Should be fixed in v1.0.0a39.
