### ISSUE TITLE
[Bug] Code not running

### ISSUE THREAD

**Issue by Xylar52** [pybricks/support#978]
**Describe the bug**
when i run a code, it start for like a milisecond and get back to normal. it doenst run. (MicroPython, spike prime)

**To reproduce**
1. have a code
2. run it

**Expected behavior**
the code to run

**Screenshots**

https://user-images.githubusercontent.com/90038318/224109963-f34c7960-7313-4ac5-95d2-9442a5057713.mp4

**Comment by laurensvalk** [comment]
When your program ends, the motors stop.

Try adding something so that your program doesn't end right away, such as waiting a few seconds or waiting for a sensor condition.
